### ISSUE TITLE
Require module inside another module

### ISSUE THREAD

**Issue by iamvdo** [substack/node-browserify#1005]
I'm requiring autoprefixer and want to get caniuse data from it, without installing it.

I basically do:

```javascript
var data = require('autoprefixer-core/node_modules/caniuse-db/features-json/rem');
```

It works with Node but Browserify fails to require this module when creating a standalone version of my module.

I also tried `../` or `./` at the beginning of the path, but nothing works.

What am I doing wrong?

**Comment by jmm** [comment]
@iamvdo If this is still a problem, please open a new issue with a minimal reproduction (the code you're browserifying, your bundling script or CLI command, browserify version).
