### ISSUE TITLE
Bad require resolve

### ISSUE THREAD

**Issue by Delagen** [substack/node-browserify#1007]
The following project structure
`a/a.js`
```
module.exports = function() {
 console.log("a a")
};
```
`a/b.js`
```
module.exports = function() {
 console.log("a b")
};
```
`a/index.js`
```
module.exports = {
	a: require("./a"),
	b:  require("./b")
};
```
`b/a.js`
```
module.exports = function() {
 console.log("b a")
};
```
`b/b.js`
```
module.exports = function() {
 console.log("b b")
};
```
`b/index.js`
```
module.exports = {
	a: require("./a"),
	b:  require("./b")
};
```
`index.js`
```
module.exports = {
	a: require("./a"),
	b: require("./b")
};
```

`browserify ./index.js`
Produces output that replaces `b/index.js` with strange 
```
arguments[_][_][_].apply(exports,arguments)
```
which resolves to `a/index.js` and brokes the code.

**Comment by Delagen** [comment]
This is critical fail.

**Comment by substack** [comment]
`a/index.js` and `b/index.js` are getting deduped to be the same file, but they have different relative references. This was a bug in the past but I thought it was fixed. It seems not.

**Comment by Delagen** [comment]
Any fix?

**Comment by Delagen** [comment]
Any progress?

**Comment by Delagen** [comment]
Seems to be fixed, with some dedupe hack. So can be closed for now. But it sometimes makes unpredicted result which I cannot catch for test data for a while.
