### ISSUE TITLE
Do package.json transforms get applied when browserifying programmatically?

### ISSUE THREAD

**Issue by domenic** [substack/node-browserify#1011]
Can't quite figure this out myself...

I have a test directory with `package.json` and `entry.js`. `package.json` contains:

``` json
{
    "browserify": {
        "transforms": [
            ["jadeify", { "self": true }]
        ]
    }
}
```

To test this, I am chdiring to that directory, then running `browserify().add(fullPathToEntryJs).bundle()`. However, when I modify the jadeify source to output any options passed to it, I get nothing (just `{ _flags: {} }`).

**Comment by trusktr** [comment]
+1 for an alias.
