### ISSUE TITLE
-r fails when requiring the same file from multiple folders

### ISSUE THREAD

**Issue by marcboscher** [substack/node-browserify#1020]
Take this project for example:
/util.js 
/main.js --> require('./util'), require("./a/submodule")
/a/submodule.js --> require('../util')

Run: `browserify -r ./util.js main.js > bundle.js`

The bundle.js will not run because the resolved dependencies for util.js point to undefined. E.g.
`{"./a/submodule.js":1,"./util.js":undefined}`
`{"../util":undefined}`

Now run:`browserify -r ./util.js:./util main.js > bundle.js` 

The bundle.js still won't run but only one of the two resolved dependencies is undefined
`{"./a/submodule":1,"./util":"./util"}`
`{"../util":undefined}`

This seems like a bug to me, but I could just be misunderstanding this whole thing. A sample project to reproduce can be found here: https://github.com/marcboscher/browserify-test

Using browserify 7.0.0 on Windows 7

Thanks

**Comment by marcboscher** [comment]
Confirming it's fixed for me as of 8.0.3

**Comment by FractalizeR** [comment]
Isn't it reproducing again in 8.1.3? I have the same problem with including modules from the same directory.
