### ISSUE TITLE
Feature request: Bundle scoped "globals"

### ISSUE THREAD

**Issue by fkling** [substack/node-browserify#1024]
Maybe this has been discussed before, maybe this is even possible already, but I havn't found any information about it.

With "bundle scoped globals" I mean variables that are accessible within every module, without requiring them explicitly, but are not exposed outside of the bundle.

The main motivation comes from working with transpilers. Most transpillers include some kind of runtime. The better transpillers let you choose where / how you want to include it and even how to expose it. E.g. 6to5 lets you specify a namespace for the runtime and all you have to do is provide the runtime through that namespace.

However, since the runtime is only relevant inside the bundle, I don't want to provide the runtime as true global. I also don't want to require the runtime in every file since the transpilation process should be transparent.

I want to be able to say "make this module available to every other module via that name/variable".

**Comment by fkling** [comment]
Not relevant anymore.

**Comment by jmm** [comment]
@fkling I was thinking about something kind of along these lines recently. What made this not relevant anymore? `runtime` transformer?

**Comment by fkling** [comment]
@jmm: Yep. I think if a transform works with browserify, it's not too unreasonable to assume that they could also inject a `require` call to any runtime they might need.

**Comment by jmm** [comment]
@fkling Ok, thanks for the feedback.
