### ISSUE TITLE
Modules with identical content are not distinguished

### ISSUE THREAD

**Issue by pluma** [substack/node-browserify#1027]
If two modules have the same content, their names are treated as synonymous. This can lead to weird bugs when modules have state.

Example:

example/x.js

``` js
var i = 0;
module.exports = function () {return i++;};
```

example/y.js (identical to x.js)

``` js
var i = 0;
module.exports = function () {return i++;};
```

example/index.js

``` js
var x = require('./x');
var y = require('./y');
console.log(x());
console.log(x());
console.log(y());
console.log(y());
```

Actual output:

```
0
1
2
3
```

Expected output:

```
0
1
0
1
```

**Comment by Delagen** [comment]
This is not fixed due #1007 and even when files is in different paths.
