### ISSUE TITLE
Version 8.0.2 broke my build with gulp

### ISSUE THREAD

**Issue by burmisov** [substack/node-browserify#1044]
Not sure weather this is a browserify issue, but versions prior to 8.0.2 used to work fine (including 8.0.1).

Now it exits with this error:
```
Error: write after end
    at writeAfterEnd (D:\code\webgis\node_modules\browserify\node_modules\labeled-stream-splicer\node_modules\stream-spl
icer\node_modules\readable-stream\lib\_stream_writable.js:161:12)
```

Here is my build code:
```js
var browserify = require('browserify');
var rename = require('gulp-rename');
var transform = require('vinyl-transform');
var reactify = require('reactify');
var size = require('gulp-size');
gulp.task('scripts-debug', function () {
    var browserified = transform(function (filename) {
        var b = browserify(filename, {
            debug: true,
            extensions: ['.js', '.jsx']
        });
        b.transform(reactify);
        return b.bundle();
    });

    gulp.src('src/js/app.js')
        .pipe(browserified)
        .pipe(rename('bundle.js'))
        .pipe(gulp.dest('build/js'))
        .pipe(size({ showFiles: true }));
});
```

**Comment by cortesi** [comment]
Just a quick note that our build scripts have been broken by this issue too. So... bump.

**Comment by romeovs** [comment]
Same here. works on `8.0.1` but not on `8.0.2`.

**Comment by davidmerrique** [comment]
Same here :
```javascript
b.transform('coffeeify'); // Broken in 8.x.x
b.transform({ global: true }, coffeeify); // Works in 8.0.1, broken in .0,.2,.3
```

**Comment by jmm** [comment]
I don't pretend to fully understand everything involved in this, but I believe what's happening is that as of browserify 8.0.2, when it finishes running transforms it causes the pipeline to `end()`, meaning that `bundle()` no longer returns a writeable stream, as vinyl-transform relies on. I will be curious to see what @substack has to say about this, but I believe there are at least 2 workarounds if you need to use browserify >= 8.0.2 in the meantime:

Where `entry`, `dest`, `b_opts`, and `some_xform` are whatever you want.

Refactor usage of vinyl-transform as described in hughsk/vinyl-transform#1:

```js
gulp.task('whatever', function () {
  var b, browserified;

  b = browserify(b_opts)
    .transform(some_xform);

  browserified = transform(function (filename) {
    b.add(filename);
    return b.bundle();
  });

  gulp.src(entry)
    .pipe(browserified)
    // ...
    .pipe(gulp.dest(dest));
});
```

Use vinyl-source-stream instead:

```js
gulp.task('whatever', function () {
  var b = browserify(entry, b_opts)
    .transform(some_xform);

  b.bundle()
    .pipe(vss('bundle.js'))
    // ...
    .pipe(gulp.dest(dest));
});
```

**Comment by aymanrady** [comment]
I got around this without vinyl-transform or vinyl-source-stream
```js
gulp.src('./src/index.js')
	.pipe(through2.obj(function (file, enc, next){
			browserify(file.path)
				.transform('stripify')
				.bundle(function(err, res){
					// assumes file.contents is a Buffer
					file.contents = res;
					next(null, file);
				});
		}))
	.pipe(gulp.dest('./build/'))
```
hope this helps

**Comment by clineamb** [comment]
@aymanrady - awesome solution!  Tried this out and it works great for me. (:

**Comment by blacksonic** [comment]
same issue here when i use the ```browserify(file.path).require('moment')``` command
makes requiring external libraries a pain

**Comment by burmisov** [comment]
@aymanrady - thanks for the idea, worked for me too.

**Comment by blacksonic** [comment]
@aymanrady - works fine, but some solution may get into the library

**Comment by Josh-a-e** [comment]
:+1:

**Comment by jmm** [comment]
@aymanrady @clineamb @blacksonic @burmisov  
What exactly do you gain from this technique over just using browserify and the `fs` module or vinyl-source-stream? E.g.:

```js
browserify('./src/index.js')
  .transform(whatever)
  .bundle()
  .pipe(fs.createWriteStream('./build/whatever.js'));
```

* This only allows you to `gulp.src` one entry file per bundle, right?

* You're not even using globbing.

* This only allows you to apply gulp plugins to that one file or the whole bundle output.

* Without additional effort doesn't this name the bundle after the single entry file?

**Comment by clineamb** [comment]
@jmm I *am* using globbing and have multiple bundles for different parts of sites I build typically.. I have different file names for each bundle...  The browserify+fs way doesn't handle globs by default like gulp does.  I use globs to select the various bundles I need.  I also typically `require()` in-file, since different files may have different dependencies, not every single bundle has the same needs. In addition, with the gulp flow, I'll get to apply various other plugins (uglify, rename, whatever) to each file individually...

My structure is usually like this when it comes to stuff I want to browserify for bigger builds that have different bundles...

```
/src
  /libs
  /models
  /etc...
  bundle1.js
  bundle2.js
  bundle3.js
    ...etc...
/public
  /js 
...etc...
```

Task ends up looking like this:

```js
gulp.src("./src/*.js")
   .pipe(<browserify through2 style>)
   .pipe(uglify())
   .pipe(rename({extname: ".min.js"}) // if we're doing production, for example
   .pipe(gulp.dest("./public/js"))
;
```

I'll get my individual bundles this way.  I also would prefer to have my tasks all gulp-y since I use gulp for a lot of other things (less compile, hint/linting, etc.).  I have the browserify task built out in another file that I just require in my gulp file, so I can essentially do `var browserify = require('./tasks/gulp-browserify.js');` and then the pipe would be as such: `.pipe(browserify())`.  (In gulp-browserify.js would be requiring through2 and browserify doing the solution @aymanrady posted.)

**Comment by jmm** [comment]
@clineamb Thanks for the feedback.

I guess there's some argument for doing that if you're globbing in entry files, but that only works if you have 1 entry file per bundle, right? In other words you get a separate bundle for each file that's globbed, right?

> I also typically `require()` in-file, since different files may have different dependencies, not every single bundle has the same needs.

Sorry, I'm not sure what you mean here.

> In addition, with the gulp flow, I'll get to apply various other plugins (uglify, rename, whatever) to each file individually...

To each entry file or bundle file, right?

If it works for you I guess it's better than using vinyl-transform, which I believe only ever accidentally worked the way you guys were using it.

**Comment by aymanrady** [comment]
> that only works if you have 1 entry file per bundle, right?

@jmm you can create a bundle from multiple entries, here is a rudimentary example on how to achieve that 
```js
gulp.task( 'default', function() {
	var bundler = function() {
		var b = browserify(),
      		stream = through2.obj( function( file, enc, next ) {
				// add each file to the bundle
				b.add( file.path );
				next();
			}, function( next ) {
				b.bundle( function( err, src ) {
					// create a new vinyl file with bundle contents
					// and push it to the stream
					stream.push( new vinyl( {
						path: 'bundle.js', // this path is relative to dest path
						contents: src
					} ) );
					next();
				} );
			} );
		return stream;
	};
	return gulp.src( 'src/js/**/*.js' )
			// multiple entry files going to bundler
			// you can apply jslint, jsbeautify on src files here
			.pipe( bundler() )
			// single bundle file
			// apply minification or/and rename bundle file here
			.pipe( gulp.dest( 'build/js' ) );
} );
```

**Comment by clineamb** [comment]
@jmm -- some clarifications/answers:

To first point about in-file, I don't typically require() files programmatically (`browserify().require()` or `.add()`) in a .js file it looks like a node.js file setup:

```js
var $ = require('jquery'),
    _ = require('underscore'),
    Backbone = require('Backbone')
;

var example = Backbone.Model.extend({...});

// do more code, etc.
```

for example.  I'm just more used to it this way since I also do a lot of node programming.

As for applying other gulp plugins, it's usually post-browserify-bundling.  

I actually find the through2 way much cleaner than the vinyl-transform way that broke.  I've also found the through2 way to be more forward compatible with versions of browserify that have come out (I did some tests on versions from 7 - 8+).

**Comment by darth10** [comment]
Got the same `write after end` error with reactify. Following this :+1:

**Comment by KpyacaH** [comment]
If anyone reads this, please notice that code snippets above are very useful and awesome, but they skip error handling in browserify "bundle" method callback. Don't forget to do that, as I did.

**Comment by kevinsimper** [comment]
I needed to browserify multiple files and end up with multipe browserified files, so @aymanrady solution was not right for me, but thanks for letting me in the through2 direction!

My solution ended up looking like this 
```
gulp.task('browserify', function() {

  var bundler = function() {
    var stream = through2.obj(function(file, enc, next) {
      var b = browserify();
      // add each file to the bundle

      b.add(file.path);
      b.transform(reactify)
      b.bundle( function(err, src) {
        if(err) console.log(err);
        // create a new vinyl file with bundle contents
        // and push it to the stream
        stream.push( new vinyl({
          path: file.path.replace('/www/js', ''), // this path is relative to dest path
          contents: src
        }));
        next();
      });
    });
    return stream;
  };
	return gulp.src(browserifyFiles)
    .pipe(bundler())
    .pipe(gulp.dest('www/build/'))
});
```

**Comment by pikeas** [comment]
Would really like to use browserify + vinyl-transform. Is this a browserify bug or a `wontfix`?

**Comment by jmm** [comment]
@aymanrady @clineamb Thanks for the feedback and sorry for the delayed reply. Your participaton in the discussion is helpful for understanding what people are doing and why and identifying the pros and cons of various techniques. This thread is a good opportunity to hash out what works and what doesn't, which ideas are keepers and which aren't. The vinyl-transform one (at least the original incarnation @burmisov posted about) is clearly not, as it misapplies vinyl-transform and results in the problem discussed here.

@aymanrady
> you can create a bundle from multiple entries, here is a rudimentary example on how to achieve that

Yes, thanks for the additional example. You can of course adapt it to do more at the expense of more code / greater complexity. By the time you're going to as much trouble as your latest example to get globbing via `gulp.src()`, it's worth considering just bypassing gulp for the globbing, like:

```js
gulp.task('default', function (cb) {
  var
    glob = require('glob'),
    b = browserify();

  // If desired, can apply transforms to entry file(s) and deps
  b.transform(whatever);

  // If you want multiple entry files => single bundle. Move some logic from
  // `end` to `match` if you want a bundle for each entry file.
  (new glob.Glob('./src/js/**/*.js'))
    .on('match', function (filename) {
      // add each file to the bundle
      b.add(filename);
    })
    .on('end', function () {
      b.bundle()
        // Name bundle whatever you want here
        .pipe(vss('bundle.js'))
        // single bundle file
        // apply minification or/and whatever bundle file here
        .pipe(gulp.dest('build/js').on('finish', cb));
    });
});
```

> multiple entry files going to bundler
> you can apply jslint, jsbeautify on src files here

Is it common that you'd want to apply those things to just your entry file(s) and not the files in the dependency graph?

Here is a variation on yours that does use `gulp.src()`, but eschews manually creating a vinyl object in favor of vinyl-source-stream:

```js
gulp.task('default', function (cb) {
  var
    through2 = require('through2'),
    b = browserify();

  b.transform(whatever);

  gulp.src('src/js/**/*.js')
    // multiple entry files going to bundler
    // you can apply jslint, jsbeautify on src files here
    .pipe(through2.obj(
      function write (file, enc, next) {
        b.add(file.path);
        next();
      },
      function end (next) {
        b.bundle()
          .pipe(vss('bundle.js'))
          .pipe(gulp.dest('build/js').on('finish', cb));

        next();
      }
    ));
});
```

@clineamb
> To first point about in-file, I don't typically require() files programmatically (browserify().require() or .add()) in a .js file it looks like a node.js file setup:

I think what you're saying is that you typically only have 1 entry file per bundle, right?

> As for applying other gulp plugins, it's usually post-browserify-bundling.

Ok, so it sounds like the pivotal issue for you is being able to do globbing to select 1 entry file per bundle.

> I actually find the through2 way much cleaner than the vinyl-transform way that broke. I've also found the through2 way to be more forward compatible with versions of browserify that have come out (I did some tests on versions from 7 - 8+).

The vinyl-transform way may never have been a good fit, but it certainly isn't now.

**Comment by jmm** [comment]
@pikeas 
> Would really like to use browserify + vinyl-transform. Is this a browserify bug or a wontfix?

It's not a browserify bug. `browserify().bundle()` is documented as returning a *readable* stream. vinyl-transform is for wrapping a *transform* stream. While `bundle()` may technically return a writable stream, it's not intended to be written to from outside of browserify (and that's not even how the vinyl-transform technique works when it does work).

For the time being I recommend you take a look at the various techniques suggested in this thread (by others and myself) and see if one of them works for you. If not, please post more information about your situation. vinyl-transform is not a good fit for this no matter what, but if you're really intent on using it for some reason it may work by re-arranging your code as discussed in one of my earlier posts.

**Comment by jmm** [comment]
This issue is due to use of vinyl-transform in a way that doesn't make sense. Please note that I'm not pointing fingers at anyone for doing it, I know everyone is just trying to figure out how to integrate browserify with gulp and that's one of the techniques that's been promoted. But it was a poor choice of technique that only worked as a fluke.

For that reason I'm closing the issue. However, for the time being we can continue to use this thread to discuss ways of integrating them that *do* make sense.

Also note that as of browserify v9.0.5 / v9.0.6 use of vinyl-transform in any variation discussed in this thread will fail 100% of the time, I believe. See #1187 and #1191.

**Comment by blacksonic** [comment]
Finally what is the solution? vinyl-source-stream ?

**Comment by terinjokes** [comment]
Just a reminder that a gulp task is just a stream, and that there are other possible ways to construct the stream than just `gulp.src`. I believe the following is idiomatic:

```javascript
var browserify = require('browserify');
var gulp = require('gulp');
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');
var uglify = require('gulp-uglify');

gulp.task('default', function () {
    return browserify(['./entry.js']).bundle()
        .pipe(source())
        .pipe(buffer())
        .pipe(uglify())
        .pipe(gulp.dest('dist/'));
});
```

If you have multiple input files, passing the output of something like `globby.sync(['./entries/*.js'])` to the browserify function should work in most cases.

**Comment by jmm** [comment]
> globby.sync(['./entries/*.js'])

Or if you don't want the globbing to hold up parallel tasks, my earlier post shows an example with async globbing.

**Comment by terinjokes** [comment]
> there are other possible ways to construct the stream

Another possible way of constructing a bundle with multiple entries, that I personally think is easier to understand than using through in the middle of a `gulp.src` constructed stream (though that's not wrong, if you decide you like it).

```javascript
var through = require('through2');
var globby = require('globby');
var browserify = require('browserify');

gulp.task('default', function() {
  var bundledStream = through();

  bundledStream
    .pipe(source('app.js'))
    .pipe(buffer())
    .pipe(gulp.dest('dist/'));

  globby(['./entries/*.js'], function(err, entries) {
    if (err) {
      bundledStream.emit('error', err);
    }

    var b = browserify(entries);
    b.bundle().pipe(bundledStream);
  });

  return bundledStream;
});

**Comment by jmm** [comment]
@terinjokes 

> that I personally think is easier to understand than using through in the middle of a `gulp.src` constructed stream (though that's not wrong, if you decide you like it).

I don't know if you're speaking to me or just in general, but putting a through stream in the middle of a `gulp.src()` constructed stream wasn't my suggestion originally. Yesterday I posted a [comment](https://github.com/substack/node-browserify/issues/1044#issuecomment-88980045) with two code examples for using multiple entry files. One was a variation on @aymanrady's suggestion to put a through stream in the middle of `gulp.src()` where I eliminated manually constructing a vinyl object in favor of using vinyl-source-stream. The other was an example of not using `gulp.src()` or a through stream. It's similar to what you just posted except it doesn't use a through stream at all, has a more linear relationship between source code order and event order, and I chose to illustrate calling `b.add()` for each match instead of waiting for all matches and passing them to `browserify()`.

**Comment by terinjokes** [comment]
@jmm It was to the thread in general, as a continuation of my earlier comment. I wanted it to be taken as another alternative to vinyl-transform that worked with multiple input files, addressing my cliff ending "globby.sync" comment I made as I was trying to rush out an answer so I could get to work.

Please accept my apologies for the misunderstanding.

**Comment by ConAntonakos** [comment]
@terinjokes, thanks for the logic regarding constructing a bundle with multiple entries. Unfortunately, I'm also having an issue when I try to add a `require('./relative-path-to-filename')` in one of those files. I'll get a console error stating that it cannot find that module. I'll look at the compilation, and the local file(s) that I wanted to require are seen as `undefined` as seen below. What am I doing incorrectly?

![screen shot 2015-05-18 at 3 17 56 pm](https://cloud.githubusercontent.com/assets/1504302/7688233/1fa291a2-fd71-11e4-892b-d83a2fbb8860.png)

**Comment by sandermarechal** [comment]
How can @aymanrady's through2 solution be used in combination with watchify? I am trying to compile multiple source files to multiple destination files and use watchify, but I can't make it work :-(

**Comment by blacksonic** [comment]
@sandermarechal i also started with @aymanrady 's through2 solution but was unable to put in watchify and started to search for new solutions and then found this blog post about multiple bundles: http://fettblog.eu/gulp-browserify-multiple-bundles/
It helped me a lot to make it easier and to understand it.
Implemented a watchify solution based on that blog post: https://github.com/emartech/boar-tasks/blob/master/tasks/client.js
The ```buildScripts``` function is where i implemented it. Have a look and have fun :)

**Comment by sandermarechal** [comment]
@blacksonic Thanks. I did manage to geth watchify working with throught2 though:

    var bundler = through2.obj(function (file, enc, next) {
        var b = browserify(file.path);

        if (watch) {
            b = watchify(b, {poll: true});

            b.on('update', function () {
                gutil.log('Updated', gutil.colors.magenta(file.path));

                b.bundle(function (err, res) {
                    file.contents = res;
                    // Do not call next!
                });
            });

            b.on('log', gutil.log);
        }

        b.bundle(function (err, res) {
            file.contents = res;
            next(null, file);
        });
    });

    return gulp.src(JS_APP)
        .pipe(plumber())
        .pipe(bundler)
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(uglify({mangle: false, preserveComments: 'some'}))
        .pipe(sourcemaps.write('./maps'))
        .pipe(gulp.dest('./HTML/js'));

The important part is that for updates, do not call the next() function. This works flawlessly so far.

**Comment by mogelbrod** [comment]
@sandermarechal: I don't seem to be able to get updates to work with your code. Not calling `next()` in the  `update` event callback means that no changes are written, or am I missing something? I'll check out the [example](https://github.com/marcello3d/gulp-watchify/blob/master/examples/uglified/gulpfile.js) in gulp-watchify next to see how it works.

**Comment by sandermarechal** [comment]
@mogelbrod I haven't quite figured it out myself. I get updates on the files listen in JS_APP in my example, but not in any of the code they require.

**Comment by JetFault** [comment]
This is what I did to get watchify and @aymanrady's through2 way to work:

```
var cachedBundles = {};
​
function bundleEntry(onUpdate) {
  var transformation = through2.obj(function(file, enc, next) {
    var filename = file.path;
    var config = {
      entries: [filename],
      transform: []
    };
​
    function onBundleCB(err, res) {
      if (err) {
        return next(err);
      }
​
      file.contents = res;
      next(null, file);
    }
​
    // Watchify configs
    if (shouldWatch) {
      if (cachedBundles[filename]) {
        // Already created a watched bundle, just rebundle
        return cachedBundles[filename].bundle(onBundleCB);
      } else {
        config.cache = {};
        config.packageCache = {};
        config.debug = true;
      }
    }
​
    var b = browserify(config);
​
    b.on('error', handleError); // No idea if this is needed (just calls this.end)
​
    if (shouldWatch) {
      b = watchify(b);
      cachedBundles[filename] = b;
      b.on('update', function() {
        onUpdate(filename);
      });
    }
​
    b.bundle(onBundleCB);
  });
​
  return transformation;
}

gulp.task('build', function() {
  var bundles = ['scripts/popup.js', 'scripts/contentscript.js', 'scripts/background.js', 'scripts/options.js'];
​
  function buildScripts(files) {
    return gulp.src(files)
    .pipe(bundleEntry(buildScripts))
    .pipe(buffer())
    .pipe($.if(minify, $.uglify({preserveComments: $.uglifySaveLicense}).on('error', handleError)))
    .pipe(gulp.dest('./dist/chrome/scripts'));
  }
​
  var scripts = buildScripts(bundles);
​  return scripts;
});
​```

Although, to be honest, I haven't tried what will happen when browserify fails...
