### ISSUE TITLE
require does not work in script loaded from browser field

### ISSUE THREAD

**Issue by majgis** [substack/node-browserify#1047]
In package.json:

    "browser": "./browser.js"

in browser.js:
    
    require('./index');

results in this error:

    Uncaught Error: Cannot find module './index'

I was able to get require working by adding the following to package.json:

      "browser" : {
          "index.js":"./browser.js",
          "./index":"./index.js"
      }
Can anyone explain why require isn't working by default?

**Comment by substack** [comment]
I think `require('./')` is more true to the node resolve algorithm. If you want to make `require('./index')` and `require('./')` work you can do:

```
"browser": {
  "./": "browser.js",
  "./index": "browser.js"
}
```
