### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by webpro** [substack/node-browserify#1049]
Just saying, currently I get this:

```
❯ npm i browserify
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "browserify"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package bn.js does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer miller-rabin@1.1.2 wants bn.js@^0.16.0
```

I understand it's not an issue in Browserify itself, but some dependencies. Looking into it a bit, I'm seeing @guybedford is [having a go at it](https://github.com/guybedford?tab=activity). I've opened this issue so other people know about it if they search when having the same issue.

**Comment by guybedford** [comment]
It's just these dependencies left that need updating:

* https://github.com/calvinmetcalf/browserify-sign/pull/5
* https://github.com/calvinmetcalf/createECDH/pull/1
* https://github.com/calvinmetcalf/diffie-hellman/pull/4

**Comment by webpro** [comment]
Thanks, nice to have this overview.

**Comment by brenoferreira** [comment]
I'm having the same problem here. Any workarounds?

**Comment by TiddoLangerak** [comment]
Workaround I also mentioned in the [diffie-hellman issue](https://github.com/calvinmetcalf/diffie-hellman/issues/5):

> For anyone having this problem, you can temporary work around it by installing miller-rabin@1.1.1 as a peer-dependency in your own project (npm install miller-rabin@1.1.1 --save-peer). This ensures bn.js@0.15 is used instead.

**Comment by sergeyzenchenko** [comment]
Same issue.

**Comment by jonathandion** [comment]
Same issue.

**Comment by flaviomori** [comment]
Same issue.

**Comment by cliftonc** [comment]
Very broken, and the work around suggested above doesn't work for me.

**Comment by TiddoLangerak** [comment]
@cliftonc - Does it work if you first completely remove the `node_modules` folder?

**Comment by cliftonc** [comment]
@TiddoLangerak yes - that worked, thanks.

**Comment by briandeheus** [comment]
Same issue.

**Comment by marcio** [comment]
Same issue

**Comment by brenoferreira** [comment]
`rm -rf node_modules && npm install miller-rabin@1.1.1 --save-peer && npm install` worked for me.

**Comment by TiddoLangerak** [comment]
@brenoferreira - The "fix" I outlined above (with `--save-peer`) isn't actually a full workaround: the `--save-peer` flag doesn't exist, and additionally it apparently doesn't work when installed as a peer dependency. I've updated the comment with a real workaround: the `miller-rabin` package should be installed as a regular dependency with a fixed version number (`1.1.1`).

My previous suggested workaround only works the first time, when you later try to do a clean install it will still fail with the same error.

**Comment by brenoferreira** [comment]
:+1:

**Comment by andywhite37** [comment]
It seems to be working now with this change in miller-rabin: https://github.com/indutny/miller-rabin/tree/v1.1.4.

Is there anything else that needs to be done?

**Comment by yamalight** [comment]
works good for me now

**Comment by brenoferreira** [comment]
It seems to be working now! Thanks guys :)

**Comment by ughitsaaron** [comment]
Just had this issue in v12.0.1. `rm -rf node_modules && npm install miller-rabin@1.1.1 --save-peer && npm install` worked as a workaround.
