### ISSUE TITLE
Idea: Let packages specify their own transforms?

### ISSUE THREAD

**Issue by trusktr** [substack/node-browserify#1050]
Instead of requiring a parent package to do so? For example, I want to tell my friend "Hey, this is my package. Install it, then use it with browserify" without having to also say "Oh yeah, also make sure you add this fooify transform to your package.json browserify.transform array and your dependencies".

An example: Browserify projects that depend on [famous](http://github.com/Famous/famous) also depend on the famousify transform to sanitize require() statements. It'd be nice if famous could specify this it it's own package.json, then a project that depends on famous doesn't have to.

**Comment by trusktr** [comment]
IMHO, a better approach than the current would be to let packages specify their own transforms, but also make it easy for a package to override or remove transforms of it's dependencies.

**Comment by feross** [comment]
> For example, I want to tell my friend "Hey, this is my package. Install it, then use it with browserify" without having to also say "Oh yeah, also make sure you add this fooify transform to your package.json browserify.transform array and your dependencies".

This is exactly how browserify transforms work. Each package specifies its transforms.

The real issue is with famous encouraging users to use `require` incorrectly. Why do they say `require('./core/Context.js')` for example, when the correct path is `require('./src/core/Context.js')`? Try the latter in your own code and it'll work just fine.

If you want their weird `require` magic to work *in your own module*, then you need to add their transform *to your own module*.

They should just axe their `src/` folder and move everything to the top level and get rid of the famousify transform entirely. Why do people love to make simple things complicated?

**Comment by substack** [comment]
Closing since browserify can already do this as explained. Perhaps you should raise this issue with the famous maintainers?

**Comment by trusktr** [comment]
@feross You're missing my idea. Currently, *parent* packages specify transforms to use on *child* packages (i.e. dependencies). It'd be nice if the child packages (the dependencies) could specify their own transforms instead. Also, the famousify transform prevents you from have to use `src` 100% of the time, which actually is quite nice.

**Comment by trusktr** [comment]
@substack You also missed my idea. xD ^

**Comment by trusktr** [comment]
A good approach would be to assume that someone who wants to use a library just wants to use the library, not worry about what transforms the project also needs to have for the dependencies to work. Maybe this is a special scenario, but I tried specifying the transform in the famous package itself, which doesn't work.

**Comment by TheAlphaNerd** [comment]
The src folder in famous is not going anywhere for the time being, it was necessary as the main folder was becoming very crowded and it wasn't clear which folders were source code versus support material. 

Further, while famous supports browserify, the framework officially supports require js first class (as you can tell by the anonymous define). In truth famousify itself is a hack to allow browserify to support code written identically in both environments. 

Transforms as they currently exist are very elegant and allow modules to be self contained, not knowing about how they are being used. Hijacking all requires in the parent module would be quite dangerous, filled with edge cases, and not nearly as elegant.

**Comment by TheAlphaNerd** [comment]
We currently include deamdify on the package.json so that you never have to worry about it. 

Transforming he code before handing it off, good idea. Hijacking require before dealing with code, bad idea

**Comment by trusktr** [comment]
Oh I see. I get it, so the relative paths in famous don't get detected by famousify, is that the reason it doesn't work putting famousify into famous package.json directly?

Your last idea there @TheAlphaNerd sounds good, instead of hijacking (which is why I suggested making it easy for a parent to override, for the edge cases).

**Comment by trusktr** [comment]
@substack @feross @TheAlphaNerd So is it then possible to modify famousify so that it lives inside the famous package instead of in a package depending on famous?

**Comment by TheAlphaNerd** [comment]
It doesn't work because if you try and require a file that doesn't exist
everything will explode.

Transforms work by processing the code you plan on browserifying prior to
compilation.

Deamdify works in famous becomes it processes the code inside of famous
before it gets compiled. Famousify wouldn't work because it would need to
process the code in the parent module, which is an abstraction violation

**Comment by TheAlphaNerd** [comment]
If famousify lived in famous the parent module would have no clue what it
was trying to require because the files it would be printing to do not
exist.

It is a bit of sugar for compatibility

**Comment by trusktr** [comment]
@TheAlphaNerd Oh ok, I totally get it now. What about that idea "Transforming the code before handing it off"? Would it be possible to make famousify do that instead?

**Comment by TheAlphaNerd** [comment]
Nope. Famousify is not processing famous code, it is processing your code
by modifying the require statements before browserify injects the
appropriate code.
