### ISSUE TITLE
need a little help about "--exclude"

### ISSUE THREAD

**Issue by xchl** [substack/node-browserify#1087]
sorry,my english is not good.pleases try to read.

   browserify -r jquery -r iscroll > bundle.js

   list.js :
      var $ = require('jquery');
      var iscroll = require('iscroll');

    browserify list.js --exclude jquery >  ./static/list.js     //this is ok.
    browserify list.js --exclude jquery iscroll >  ./static/list.js     //this is not ok. it's not supported?

**Comment by danzajdband** [comment]
You need to specify the option for each dependency. You can do either:

`browserify list.js --exclude jquery --exclude iscroll >  ./static/list.js`
or
`browserify list.js -u jquery -u iscroll >  ./static/list.js`

**Comment by xchl** [comment]
@danzajdband  thank you a lot. very helpful. └(^o^)┘
