### ISSUE TITLE
.npmignores / reducing install bloat

### ISSUE THREAD

**Issue by mattdesl** [substack/node-browserify#1093]
A fresh install of browserify produces around 26.6 mb of bloat. Most of it is coming from tests, and tests of dependencies. Not a big deal for a global install, but when you are using browserify as a local dependency for WebGL/DOM testing across several dozens of modules, it starts to add up.

Some of the heavy hitters, sorted from lowest to highest in filesize:

```
384	shasum/
392	duplexer2/
416	resolve/
440	through2/
528	concat-stream/
560	buffer/
720	labeled-stream-splicer/
816	glob/
944	browser-resolve/
1176	JSONStream/
1272	browser-pack/
3144	umd/
5280	crypto-browserify/
5344	browserify-zlib/
5544	syntax-error/
7008	insert-module-globals/
12328	module-deps/
```

I could start submitting PRs for some of these, as they are easy changes.

**Comment by adam-lynch** [comment]
+1

cc @4ver

**Comment by sindresorhus** [comment]
:+1:

**Comment by kevva** [comment]
:+1:

**Comment by jeromedecoster** [comment]
:+1:

**Comment by blacksonic** [comment]
start pushing the merge requests for this

**Comment by substack** [comment]
Those sizes are in *bytes*:

```
$ curl -s https://registry.npmjs.org/module-deps/-/module-deps-3.7.2.tgz | wc -c
13747
```

This doesn't seem worth optimizing.

**Comment by substack** [comment]
If the issue is size on disk after unpacking, 1) disk is pretty cheap 2) you can use symlinks if you've got lots of browserify copies of the same files floating around 3) you can `find -name test -or -name example -exec rm -r {} \;` after installing to save some room on disk.

**Comment by substack** [comment]
I'm also not saying the slowness problem isn't real, but I think the best place to solve it will be in the npm client and registry to reduce the number of round-trips, since the size of the payload seems rather small.

**Comment by maxogden** [comment]
I could be wrong, but I think this issue is more about stuff like `acorn` including it's test directory on npm.

For example, here's Disk Inventory X output on the `browserify` folder after a fresh `npm install --save` (e.g. no devDeps)

![screen shot 2015-02-22 at 1 49 29 pm](https://cloud.githubusercontent.com/assets/39759/6320687/b59276b6-ba99-11e4-82a5-1c70b7843957.png)

Here are the top offending modules in terms of on-disk usage:

![screen shot 2015-02-22 at 1 51 25 pm](https://cloud.githubusercontent.com/assets/39759/6320696/f5e3bdb0-ba99-11e4-844a-f627aa1bd77a.png)

**Comment by substack** [comment]
On-disk size is very misleading since everything under `node_modules` is included in that calculation. Over-the-wire sizes give a much better indication of package heft:

```
~ $ curl -s https://registry.npmjs.org/acorn/-/acorn-0.11.0.tgz | wc -c
423153
~ $ curl -s https://registry.npmjs.org/syntax-error/-/syntax-error-1.1.2.tgz | wc -c
3374
~ $ curl -s https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.1.4.tgz | wc -c
64977
```

Ignoring the test directory on a 13k package seems pointless but slimming down acorn seems reasonable.

**Comment by maxogden** [comment]
I just looked at my own dev computer, and I have over 200 copies of browserify installed taking up a total of over 4GB of space

![screen shot 2015-02-22 at 1 58 28 pm](https://cloud.githubusercontent.com/assets/39759/6320775/fcd4162c-ba9b-11e4-8b2b-e1d3c88a143b.png)

Some are just folders called browserify, hence the 264 number, but I checked and all the folders included that arent actual copies of browserify take up only 8kb each.

**Comment by mattdesl** [comment]
looks like acorn will be ignoring tests soon
https://github.com/marijnh/acorn/commit/2b6f24ea86de8e8c1cadd676087a331816743448

**Comment by zertosh** [comment]
@mattdesl Without the acorn tests the size should drop ~2MB https://github.com/marijnh/acorn/pull/211. Also from browserify v8 to v9, you should've seen another ~1MB drop https://github.com/ForbesLindesay/umd/pull/20
