### ISSUE TITLE
Incompatible with restify

### ISSUE THREAD

**Issue by u84six** [substack/node-browserify#1097]
After installing browserify with npm (e.g. npm install -g browserify), when I do a simple command line bundle like this: "$ browserify src/index.js > bundle.js" I get the following error:

Error: Cannot find module 'dtrace-provider' from 'C:\development\node-projects\my-project\node_modules\restify\lib'

Why does it care about restify module? Looks like some strange dependency issue.

**Comment by jmm** [comment]
Is `restify` somewhere in the dependency graph of `src/index.js`?

Also, please mark up code as applicable.

**Comment by u84six** [comment]
Sorry, my dumb fault. I was assuming it would bundle anything, not realizing that the whole idea behind this bundler is to use node style require. So it looks like if it is not a module, it throws this error. I suppose it would be nice to show a more meaningful error, but I'll go ahead and close this.
