### ISSUE TITLE
Browserify.prototype._json adds a module.exports without testing if it's dedupe code or not

### ISSUE THREAD

**Issue by tetsuo** [substack/node-browserify#1101]
encountered this while trying to rebuild `crypto-browserify` with watchify. one of its dependencies (`elliptic`) requires a `package.json` somewhere.

hotfix here: https://github.com/tetsuo/node-browserify/commit/9978df3a1c6fe0abbcdac9b1f2729fbbb3687b04

**Comment by evNN** [comment]
I can confirm this as well, using Browserify @ 8.1.3 and Watchify @ 2.3.0. @tetsuo's hotfix worked for me as well.

**Comment by mgmorcos** [comment]
:+1:

**Comment by substack** [comment]
Published the hotfix in 9.0.3. Thanks for the fix!
