### ISSUE TITLE
Strategy for a browserified angular library

### ISSUE THREAD

**Issue by thaiat** [substack/node-browserify#1102]
Hi,

I have written an angular module, that uses internally browserify.
The package.json of this library module contains browserify-shim as well as npm dependencies

Now i want to publish it to npm so users can require it.

I can't find a way to do so

If i require the bundle.js of the library i end up loading angular twice
If i require the index.js of the library, it does find angular

Can you help ?

**Comment by bendrucker** [comment]
Happy to help but you should close this. Doesn't need to be open on browserify.
