### ISSUE TITLE
How to deal with case sensitivity?

### ISSUE THREAD

**Issue by kentor** [substack/node-browserify#1104]
On Mac filenames are case insensitive which means both `require('./moduleA')` and `require(./'modulea')` would work. But I deploy to linux systems and the browserify build will blow up if I get the casing wrong. Does anyone have a way to deal with this, like warn or fail in dev if the casing is wrong?

**Comment by zertosh** [comment]
@kentor I built this plugin that'll do what you're asking  https://github.com/zertosh/dep-case-verify. It'll make the build fail if the case doesn't match `fs.readdir` for each part of the path.

**Comment by kentor** [comment]
@zertosh Thank you! :guitar:
