### ISSUE TITLE
browserify.transform() can't find transformation packages.

### ISSUE THREAD

**Issue by nicroto** [substack/node-browserify#1107]
Hi,

First of all - thank you for this awesome tool.

The problem I have is connected with the way browserify search for transform modules. In my project, I have a dependency, which has browserify as a dependency. This means that running my project, my Current Working Dir is a level above the dir containing transform dependencies.

Here is how the fs structure, roughly looks like:

project-root
--------app.js
--------node_modules
----------------browserify-dependable-package
------------------------node_modules
--------------------------------browserify
--------------------------------brfs(the brfs transform package)

With this structure, if I run the app with these conditions:
 - uses my *browserify-dependable-package*
 - browserifying a file.js
 - using the brfs transform
 - with cwd `/Users/nicroto/repos/project-root/` (OS X)

the **resolve** package, which is supposed to get the location of brfs, gets (in passed opts) basedir path `/Users/nicroto/repos/project-root/` and is unable to find brfs searching in:
 - `/Users/nicroto/repos/project-root/node_modules`
 - `/Users/nicroto/repos/node_modules`
 - `/Users/nicroto/node_modules`
 - `/Users/node_modules`
 - `/node_modules`

If I could always run it with this cwd, I would place the brfs module in `/Users/nicroto/repos/project-root/node_modules`, but my app is started with process.cwd `/` so this hack isn't really an option for me.

So I traced the place where basedir is picked for all transforms, which currently looks like this:
```javascript
Browserify.prototype.transform = function (tr, opts) {
    // ...
    var basedir = defined(opts.basedir, this._options.basedir, process.cwd());
    // ...
};
```
and I changed it to this (node-browserify/index.js):
```javascript
Browserify.prototype.transform = function (tr, opts) {
    // ...
    var basedir = defined(__dirname, opts.basedir, this._options.basedir, process.cwd());
    // ...
};
```

This resolved the issue, but a few tests blew up, so I decided to ask here if I am on the right track before spending more time on the issue.

Is this the right way to approach the issue and why do we need all of the fallback variants for basedir there?

**Comment by nicroto** [comment]
I can't pass a basedir in the opts, because this means that app.js should know where exactly on the fs is browserify-dependable-package, which doesn't seem right.

```javascript
var b = browserify();
b.add( filePath );
b.transform( "brfs", {
    basedir: path.resolve( __dirname, "node_modules", "browserify-dependable-package" )
} );
```

**Comment by nikku** [comment]
You may accidently pass `basedir` as an empty string.

It is a breaking change from browserify 8 -> browserify 9 that basedir must either be undefined or an actual path (`''` will raise `Module not found` errors).

**Comment by nikku** [comment]
Cf. https://github.com/nikku/karma-browserify/commit/d15ea4520a1e7648fbbbecdab2f56f3967740b4f

**Comment by nikku** [comment]
Seems like I misunderstood your problem.

Browserify will always search for transforms in the package that contains the files to be bundled. This is intentional, because different projects you bundle may specify the transforms they need independently. 

You may pass the resolved `brfs` transform directly though:

```
var brfs = require('brfs');

var bundle = browserify();
bundle.transform(brfs());
```

**Comment by nicroto** [comment]
This works for me, thanks @nikku!

Still the default algorithm uses process cwd which isn't always set to the running node app.

__dirname still seems like the best option for resolving transforms paths...

Anyways, I am closing the issue, since there is a perfectly fine alternative and because I am not sure, if unset process.cwd (pointing to "/") is a regular use-case.

Thanks.
