### ISSUE TITLE
process.nextTick shim should use Promise.resolve().then(fn) if available

### ISSUE THREAD

**Issue by domenic** [substack/node-browserify#1109]
This is currently the fastest cross-environment way of creating a microtask. But more interestingly, it works in environments like the V8 shell where there is no setTimeout available to fall back to. (Why do I need browserify bundles to run inside the V8 shell you ask? MAD SCIENCE!)

**Comment by substack** [comment]
This task is delegated to the process module: https://www.npmjs.com/package/process
It might be good to raise the issue over there, but it looks like the nextTick() was stripped down significantly at some point.

**Comment by domenic** [comment]
Thanks, moved over there.
