### ISSUE TITLE
ENOTDIR error for require('*.json') 

### ISSUE THREAD

**Issue by ritch** [substack/node-browserify#1111]
```
Error: ENOTDIR, stat '/ ... /node_modules/instructions.json/package.json'
```

When doing...

```js
bundle.require(' ... /instructions.json', {expose: 'instructions'});
```

I'm fairly certain that [browser-resolve](https://github.com/defunctzombie/node-browser-resolve/releases/tag/v1.7.0) is the culprit.

**Comment by thomaswilburn** [comment]
We're seeing this as well when loading transforms from a relative path instead of a module. Reverting the `browser-resolve` package to 1.6.0 fixed it, so it's definitely something introduced in that revision.

**Comment by scottwhite** [comment]
I got this as well
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOTDIR, stat '/Users/scott/workspace/gmj-console-ui/node_modules/pouchdb/lib/index.js/node_modules/es3ify'
```
Downgrading to browser-resolve@1.6.0 fixed it.

**Comment by mabrin** [comment]
Same here. Downgrade to 1.6.0 solved the problem.

**Comment by substack** [comment]
This is the same issue as https://github.com/substack/node-browserify/issues/1133 which was just fixed upstream in resolve: https://github.com/substack/node-resolve/commit/503c746a6e64d50f2c9b18b4476ffcfed49947f2
