### ISSUE TITLE
UNIX command line guidelines whatever?

### ISSUE THREAD

**Issue by bucaran** [substack/node-browserify#1113]
I would like to know if there was a specific reason why:

```
browserify [entry files] {OPTIONS}
```

was not made to follow the UNIX [guidelines](http://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap12.html) ([more](http://pubs.opengroup.org/onlinepubs/7908799/xbd/utilconv.html) and [also](http://pubs.opengroup.org/onlinepubs/7908799/xbd/utilconv.html)) for command line utilities, where options always appear before operands. This is not _really_ a problem, and to be fair, there are many newer and well-established (`curl` comes to mind) utilities that do break the rules sometimes.

Cheers!

**Comment by substack** [comment]
Both work. You can put the options wherever you want with a decent options parser.
