### ISSUE TITLE
"browser" field not always being respected for dependencies

### ISSUE THREAD

**Issue by AgentME** [substack/node-browserify#1119]
I'm using the [asap](https://github.com/kriskowal/asap) module, which is made for nodejs and browsers. It has several file overrides in the "browser" section of its package.json. They are not always respected.

```
npm i --save browserify asap@2.0.0
echo "require('asap');" >index.js
./node_modules/.bin/browserify index.js -o bundle.js
grep requestErrorThrow bundle.js
```

The grep call should find the string "requestErrorThrow", which is present in asap's `browser-asap.js` file, but it does not for me. For some reason, asap's node version of `asap.js` is being bundled along with the browser version of `browser-raw.js`.

A few days ago I had the opposite problem where `browser-asap.js` was being bundled along with the node version of `raw.js`. After deleting my node_modules folder and reinstalling asap and browserify, I've been getting this new issue. I assume the change either has to do with sub-dependencies changing or with the filesystem ordering. In case it has to do with sub-dependencies, here's an [npm shrinkwrap](https://gist.github.com/AgentME/0ed2a46e6c72039a80bc) showing the versions of all of my dependencies and subdependencies.

Browserify 8.1.3

**Comment by AgentME** [comment]
I'm on OS X if that makes a difference.

I'm now using Browserify 9.0.3, and getting the node versions of both asap.js and raw.js being built into the bundle.

**Comment by AgentME** [comment]
I've not had any issues with ASAP since this commit: https://github.com/kriskowal/asap/commit/b0c9021a2306dcecefcc7f1159f66bcc064a29e8 .

It seems like Browserify works inconsistently for package.json browser entries that lack file extensions. It would be useful if Browserify was more consistent, and errored or logged a warning for "browser" entries that improperly a file extension if it chooses to not support them.

**Comment by jmm** [comment]
@AgentME I wanted to acknowledge your report and say thanks for submitting it.

> It would be useful if Browserify was more consistent

Agreed!

> It seems like Browserify works inconsistently for package.json browser entries that lack file extensions.

I haven't fully debugged your issue or other issues with the browser field, but I did make some related comments over at #1088 in case you're interested. node-browser-resolve, the module that processes the `browser` field, does pseudo-resolve keys in the browser field, but then try to lookup values using actually resolved absolute paths from `require()` calls, which probably explains why the asap commit you linked to solved your problems.

**Comment by substack** [comment]
fixed upstream in https://github.com/defunctzombie/node-browser-resolve/pull/75
