### ISSUE TITLE
Add moduleDirectory option from node-resolve to Browserify

### ISSUE THREAD

**Issue by jgoux** [substack/node-browserify#1125]
Hello,
is there a way to add webpack's modulesDirectories ability to browserify ? http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories
It would be awesome and simplify a lot the code for shared modules.
Inspired by : https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346#shared-module-resolution

**Comment by jmm** [comment]
I think you can do that right now if you pass a `moduleDirectory` option to browserify. That's an option on node-resolve and I think browserify will pass it through.

**Comment by jgoux** [comment]
@jmm Thanks for your help. How can I pass this option to browserify with the CLI ?

**Comment by jmm** [comment]
@jgoux I'm not sure if that's possible right now.

**Comment by jgoux** [comment]
After looking at the source, it seems that the option isn't available.
I hope the opts.moduleDirectory from node-resolve will be configurable from Browserify. (https://github.com/substack/node-browserify/blob/master/index.js#L155)

**Comment by substack** [comment]
I don't understand the use-case for this feature. We already have:

* `node_modules` directories already work, see also [avoiding ../../../](https://github.com/substack/browserify-handbook#avoiding-)
* browser field mapping
* `opts.paths` - I don't personally like this approach but it's already there

Why do we need something else?

**Comment by jgoux** [comment]
Hello @substack ,
- node_modules impose a folder name
- symlinking isn't portable
- browser field doesn't look for ancestors
- opts.paths isn't really clean, as you said
For the exact use case of ryan florence's application structure, how would you do it with browserify ?
I agree that renaming all "shared" folders to node_modules would work, but as the moduleDirectory is there for this exact use case, it would be a good point to make it available.

**Comment by substack** [comment]
I think it's better to flow with the module system rather than trying to fight it with too many special-cases.

**Comment by substack** [comment]
Update: @jgoux implemented this in userland and the solution is pretty compact: https://gist.github.com/jgoux/cd6cab26e2c28f20d9ca

**Comment by asbjornenge** [comment]
@jgoux nice! I added a comment on the gist if you have a sec.
@substack one argument against node_modules is that transpilers typically ignore it (e.g. babelify)
