### ISSUE TITLE
Syntax errors reported when multiple requires are declared at once

### ISSUE THREAD

**Issue by admackin** [substack/node-browserify#1129]
I'm getting a syntax error when I try and run `browserify` in a module which requires [d3-geo-projection 0.2.13](https://github.com/d3/d3-geo-projection/tree/v0.2.13). The problem seems to be down to a line in its [index.js](https://github.com/d3/d3-geo-projection/blob/v0.2.13/index.js). 

    var fs = require("fs"),
        path = require("path");

    module.exports = new Function("d3", fs.readFileSync(path.join(__dirname, "d3.geo.projection.js"), "utf-8"));

If I replace the first two lines with 

    var fs = require("fs");
    var path = require("path");

`browserify` runs without complaint.

**Comment by admackin** [comment]
It seems this is due to https://github.com/substack/brfs/issues/35 ? In that case, I'll take your word that it's fixed.

**Comment by jasondavies** [comment]
It happens without brfs, so I think another fix is needed.
