### ISSUE TITLE
Absolute path ending up in build

### ISSUE THREAD

**Issue by oliverwoodings** [substack/node-browserify#1132]
Got a bit of a weird issue that I can't work out. I've got my build set up so it uses relative paths as opposed to absolute paths in the build output. This works fine everywhere in the app except for one instance for the es6-promise module which ends up like this:

```js
...
module.exports = when;
},{"../constants/status":58,"underscore":90}],84:[function(require,module,exports){
module.exports=require(42)
},{"/Users/oliverwoodings/Documents/repos/<project>/node_modules/es6-promise/dist/es6-promise.js":42,"_process":50}],85:[function(require,module,exports){
///
```

Does anyone have any idea why this might be happening? I've tried setting a basepath and setting fullPath to false but nothing seems to remove this one absolute reference.

**Comment by jmm** [comment]
What version of browserify? Where's the code where you're `require()`ing this module?

**Comment by oliverwoodings** [comment]
Browserify 8.0.3

I require the es6-promise module at the top of a module like this:

```js
require("es6-promise").polyfill();
```

**Comment by jmm** [comment]
Thanks. Are you able to create a minimal test case that will reproduce it?

**Comment by oliverwoodings** [comment]
Hm I'm going to have to do some more experimenting. Tried to create a test case but haven't been able to replicate it, and I can't share the project I'm working on.

**Comment by oliverwoodings** [comment]
I reinstalled all my node_modules and this issue went away. Weird!
