### ISSUE TITLE
bug in resolving JSON files within module dependencies

### ISSUE THREAD

**Issue by tmcw** [substack/node-browserify#1133]
I've made a reduced test case for this:

* https://github.com/tmcw/require-bug

Requiring JSON files within modules from subdirectories of a project fails and the error message indicates that browserify is looking for a `/package.json` file after the json file path. I can replicate this newly in new installs of browserify 8.x so it's likely this is because of an update in one of browserify's dependencies.

**Comment by tmcw** [comment]
bisected down to this commit in node-resolve: https://github.com/substack/node-resolve/commit/5b737d58b38ce891ef3f06d600d0562dbbc8539c

**Comment by joeybaker** [comment]
It's not limited to json files. Requiring a regular old `.js` file has the same problem.

**Comment by substack** [comment]
Fixed in https://github.com/substack/node-resolve/commit/503c746a6e64d50f2c9b18b4476ffcfed49947f2

**Comment by joeybaker** [comment]
Cheers!
