### ISSUE TITLE
can't use browserify on browserified module

### ISSUE THREAD

**Issue by anvaka** [substack/node-browserify#1140]
I'm using browserify to bundle [vivagraph](https://github.com/anvaka/VivaGraphJS) into standalone module. It works fine and I can use it from iojs:

```
npm install vivagraphjs
```

``` javascript
// filename: foo.js
console.log(require("vivagraphjs"));
```

However when I try to browserify it:

```
browserify foo.js
```

I'm getting this:
```
Error: Cannot find module './version.js' from '/Users/anvaka/temp/mmds_page_rank/node_modules/vivagraphjs/dist'
    at /Users/anvaka/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/anvaka/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/anvaka/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/anvaka/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:73:15)
```

```
browserify -v
9.0.3
```

I see [version is required here](https://github.com/anvaka/VivaGraphJS/blob/72f7c86ec688357f36cbed4aa4ba7d5ac5d895f3/dist/vivagraph.js#L23), it [receives index 63](https://github.com/anvaka/VivaGraphJS/blob/72f7c86ec688357f36cbed4aa4ba7d5ac5d895f3/dist/vivagraph.js#L119) in the browserify metadata and is exported under the [same number here](https://github.com/anvaka/VivaGraphJS/blob/72f7c86ec688357f36cbed4aa4ba7d5ac5d895f3/dist/vivagraph.js#L6802). It is the last module in the list. 

Not sure why browserify cannot find it.

**Comment by jmm** [comment]
This is a pretty common issue. Can you take a look at this [stackoverflow answer](http://stackoverflow.com/a/28176927/1034448) and it see if it helps you? Particularly the `noParse` option (or if you're using the CLI `--noparse`).

**Comment by substack** [comment]
Just set the main field in package.json to `src/viva.js`.

**Comment by anvaka** [comment]
Thank you guys! I've updated `main` entry to use `src/viva.js` and the problem is fixed.
