### ISSUE TITLE
Exporting another file

### ISSUE THREAD

**Issue by henit** [substack/node-browserify#1144]
I have a strange case of require file cross linking. I have two different files in the same directory, that export two different sets of RefluxJS actions. Something like

    var Reflux = require('reflux');
    
    module.exports = Reflux.createActions({
        //...
    });

Both files look something similar to that, but with different sets of actions.

Then when the application is built with Browserify, it suddenly decide it is a good idea to just require the first file when referring to the second one:

    (...)
    ,"/path/to/app/actions/first.js":[function(require,module,exports){
    
    var Reflux = require('reflux');
    
    module.exports = Reflux.createActions({
        // ...
    });
    },{"reflux":"/path/to/app/node_modules/reflux/index.js"}],"/path/to/app/actions/second.js":[function(require,module,exports){
    module.exports=require("/path/to/app/actions/first.js")
    },{"/path/to/app/actions/first.js":"/path/to/app/actions/first.js"}],
    (...)

Do you have any idea why the second action-file just require the first one? I have doublechecked my require statements, files and everything, and see no reason in the code for why it should be doing this.

**Comment by xincici** [comment]
Just run into the same question, waiting for a solution or an explanation.

**Comment by xincici** [comment]
It seems that the browserify v9.0.3 has solved this problem.

**Comment by nikku** [comment]
@henit Could you create an example project / setup that reproduces the issue you are seeing?

**Comment by henit** [comment]
@nikku That might be hard. The issue occurred some times, but other times it worked as expected. If I tried to recreate an example project, the issue might not occur at all.

**Comment by xincici** [comment]
for example below:
aa.js
```javascript
var cfn = require('./fn');
module.exports = new cfn();
```
bb.js
```javascript
var cfn = require('./fn');
module.exports = new cfn();
```
fn.js
```javascript
function cfn(){
    this.$1 = {};
}
cfn.prototype.show = function(text){
    console.log(text);
};
module.exports = cfn;
```
main.js
```javascript
var a = require('./aa');
var b = require('./bb');
window.a = a;
window.b = b;
console.log( a === b );
```
above files are all in the same folder, then when you run command in the folder:
```shell
browserify main.js > bundle.js
```
the bundle.js will have such content in it: (code piece)
```javascript
{1:[function(require,module,exports){
var cfn = require('./fn');
module.exports = new cfn();

},{"./fn":3}],2:[function(require,module,exports){
module.exports=require(1)
},{"./fn":3,"/Users/linye/nodeTest/tb/aa.js":1}],3:[function(require,module,exports){
function cfn(){
    this.$1 = {};
}
cfn.prototype.show = function(text){
    console.log(text);
};
module.exports = cfn;

},{}],4:[function(require,module,exports){
var a = require('./aa');
var b = require('./bb');

window.a = a;
window.b = b;

console.log( a === b );

}
```
it makes the window.a === window.b result to true.
below conditions are indispensable.
1. content of aa.js and bb.js are exactly the same.
2. browserify of a previous version, not v9.0.3 (v9.0.3 has solved this problem)

**Comment by nikku** [comment]
Looks like a deduplication issue. Just add a simple comment to each file to make them look differently for browserify and you should be doing fine.

Nice to hear it has been solved in the latest version.

**Comment by nikku** [comment]
@henit does 9.0 fix the issue for you?

**Comment by henit** [comment]
I went for another solution. Thanks for investigating.
