### ISSUE TITLE
Don't attempt to resolve dependencies that will never be used

### ISSUE THREAD

**Issue by kentcdodds** [substack/node-browserify#1145]
Given I have code like this:

```javascript
var x;
if (false) {
  x = require('./some-file');
}
```

Don't attempt to resolve the require statement because that code will never be run. I realize that this looks ridiculous, but this type of thing happens with projects that use webpack to distribute their modules using the `DefinePlugin`. For example: https://github.com/formly-js/angular-formly/issues/186

Aside from that, trying to be smarter about what require statements to attempt to resolve would lead to better perf and smaller output (in some cases).

**Comment by substack** [comment]
To support this fully would require solving the halting problem.

**Comment by zertosh** [comment]
@kentcdodds I built [`unreachable-branch-transform`](https://github.com/zertosh/unreachable-branch-transform) that does just that. it removes unreachable code by performing static analysis on conditionals, so `require`s like the one in your example won't get bundled

**Comment by kentcdodds** [comment]
That's great @zertosh, thanks!
