### ISSUE TITLE
standalone does not support _ and $

### ISSUE THREAD

**Issue by chunpu** [substack/node-browserify#1149]
```sh
browserify . -s _
browserify . -s $
```

will both throw error

```sh
/usr/local/lib/node_modules/browserify/node_modules/umd/node_modules/uglify-js/lib/parse.js:197
    throw new JS_Parse_Error(message, line, col, pos);
```

but sometime we may need to use _ like underscore, can this be fixed? Thanks

**Comment by danzajdband** [comment]
It is working for me using browserify 9.0.3. Which version of browserify are you using?

**Comment by substack** [comment]
Can you provide any more context? What happens when you do `browserify .` ? How did you narrow the problem down to standalone mode?

**Comment by chunpu** [comment]
Oh sorry! I use very old browserify, it is ok after I updated browserify!

**Comment by farzher** [comment]
I had the same issue. Updating `browserify` fixed it +1
