### ISSUE TITLE
browserifyV9.0.3 does not respect --ignore-missing

### ISSUE THREAD

**Issue by davydog187** [substack/node-browserify#1152]
After a very frustrating experience, it has come to my attention that browserify no longer respects --ignore missing. What is not clear is whether or not this feature was removed intentionally or not.

There exists a test here for ignoreMissing: https://github.com/substack/node-browserify/blob/47c6933e711567de761c73fe81165223c7873433/test/ignore_missing.js

Also, ignore missing is accepted as a command line argument here: https://github.com/substack/node-browserify/blob/master/bin/args.js#L87

I see no mention of `ignoreMissing` in `index.js`, so it appears that this feature was removed. Can someone shed some light as to the status of this feature? The documentation still explicitly mentions it with no mention of deprecation.

**Comment by substack** [comment]
It does! The test still passes. The implementation lives in module-deps, not browserify core: https://github.com/substack/module-deps/blob/master/index.js#L86

**Comment by davydog187** [comment]
Lets not be so hasty to close this, in my experience it does not work correctly.

I have code that I am ignoring, but rather than browserify replacing it with `module.exports = {}` as the documentation states, it just appears as `undefined` in the lookup table.

Using `ignoreMissing` did not have any effect on this, which leaves me to believe that there is a bug abound here.
