### ISSUE TITLE
Is there a way to specify a file extension to be treated like json

### ISSUE THREAD

**Issue by philstrong** [substack/node-browserify#1156]
I have avro files that are just json.  browserify I believe is detecting json files and wrapping them in module.exports

Is there a way to say treat *.avsc like json?

**Comment by jmm** [comment]
You could try one of the following:

```js
var t2 = require('through2');

// 1)
b.transform(function (file) {
  var write, first = true;

  if (/\.avsc$/.test(file)) {
    write = function (chunk, enc, cb) {
      if (first) this.push("module.exports=");
      this.push(chunk);
      cb();
      first = false;
    }
  }

  return t2(write);
});

// 2)
b.pipeline.get('deps').push(t2.obj(function (rec, enc, cb) {
  rec.file = rec.id.replace(/\.avsc$/, ".json");
  this.push(rec);
  cb();
}));

**Comment by jmm** [comment]
There doesn't seem to be any further action available here so I'm closing this. Please open a new issue if necessary.

**Comment by 0815fox** [comment]
Hi,
I just stumbled over the same. On my opinion, browserify is behaving differently from node.js here. Node.js detects automatically, whether a file with an arbitrary extension contains js or json. 

Wouldn't it be better, if browserify did the same?
@jmm : Should I open a new issue for this or can this one be reopened?

**Comment by jmm** [comment]
Hello @0815fox 
> Node.js detects automatically, whether a file with an arbitrary extension contains js or json.

Not to the best of my knowledge. If that's the case please provide a reference and / or minimal reproduction.

**Comment by 0815fox** [comment]
Hi, just noticed my mistake and edited my comment before you published it. I think I dreamt it yesterday, that this was working...
So this is the proof, that I was wrong: https://github.com/nodejs/node-v0.x-archive/issues/6073

**Comment by jmm** [comment]
@0815fox Ok, thanks.
