### ISSUE TITLE
Load My Own Modules Using Browserify

### ISSUE THREAD

**Issue by realph** [substack/node-browserify#1159]
I'm trying to load some modules with Browserify that aren't available over npm. For whatever reason, I can't get it to work with [fluidbox.js](https://github.com/terrymun/Fluidbox/blob/master/jquery.fluidbox.js).

**fluidbox.js**

    var jQuery = require('jquery');

    module.exports = function() {
      
      // pasting fluidbox.js inside here
      
      (function($,sr){
        ...
    };

**app.js**

    var $ = require('jquery');
    var fb = require('./vendors/fluidbox.js');

    fb();

    $('.gallery a[rel="lightbox"]').fb({
       viewportFill: 0.9,
       immediateOpen: true
    });

I'm requiring jQuery correctly, but I seem to be doing something wrong as it's not working in my browser.

I'm getting a "Uncaught TypeError: undefined is not a function" error on this line:

    $('.gallery a[rel="lightbox"]').fb({

Any help with this is appreciated. Thanks in advance!

**Comment by jmm** [comment]
Where does `.fb` come from -- doesn't it attach itself as `$().fluidbox`?

**Comment by realph** [comment]
@jmm Ahh! I thought you had to attach it with the var name. My god, so stupid of me!
