### ISSUE TITLE
Throttle/Debounce with Browserify

### ISSUE THREAD

**Issue by realph** [substack/node-browserify#1160]
I'm trying to get Ben Alman's [throttle/debounce script](https://github.com/cowboy/jquery-throttle-debounce/blob/master/jquery.ba-throttle-debounce.js) to play nice with Browserify, but I keep hitting a wall.

    var $ = require('jquery');

    // jQuery Throtttle/Debounce
    (function(window,undefined){
      ...
    })(this);

    function log( event ) {
      console.log( $(window).scrollTop(), event.timeStamp );
    };

    $(window).scroll( $.throttle( 250, log ) );

I'm requiring jQuery at the top of my file, but it keeps returning me a "Uncaught TypeError: undefined is not a function" error on this line:

    $(window).scroll( $.throttle( 250, log ) );

However, if I include both jQuery and my app.js file the traditional way with two `<script src="">` tags, before the closing body tag, the code works.

Am I doing something wrong here. Am I not understanding Browserify correctly?

Any help is appreciated. Thanks in advance!

**Comment by jmm** [comment]
If that first snippet is the file you're browserifying, `this` is not going to `=== window` there.

**Comment by realph** [comment]
@jmm I don't think I'm on the same page. Are you saying I need to define `this`?

**Comment by jmm** [comment]
The jQuery Throtttle/Debounce code you posted relies on being in the global scope in a browser with its usage of `this`. If you take code like this:

```js
(function(window,undefined){
  ...
})(this);
```
and browserify it, it will turn into code like this:

```js
function (require, module, exports) {
(function(window,undefined){
  ...
})(this);
}
```
On the assumption that you don't want to edit the actual script (even though it looks like maybe you're copying and pasting it), try this:

```js
(function () {
  // jQuery Throtttle/Debounce
  (function(window,undefined){
    ...
  })(this);
}).call(window);
```

**Comment by realph** [comment]
@jmm I've tried to simply change `this` to `window`, but assume because it's an older library it's expecting to run on a script level. Hmm... Can't figure a way around this.

**Comment by realph** [comment]
I've tried the above, but I still seem to be getting the same "undefined is not a function" error. The error in the console log seems to be pointing out that `$.throttle` is the problem.

    $(window).scroll( $.throttle( 250, log ) );

Is `$.throttle` perhaps not being defined outside the function? I'm fairly new to JS, and Browserify is slightly still confusing to me at the moment.

**Comment by jmm** [comment]
The other thing is that the script expects `window.jQuery` to be set. Is the jQuery that you're loading with `require('jquery')` doing that?

**Comment by realph** [comment]
How can I find that out? I'm just requiring jQuery from npm like I posted in the original question. Are you saying I'd need to set `window.jQuery` too? Are you suggesting something like this?

    var $ = require('jquery');
    window.$ = window.jQuery = require('jquery');

**Comment by jmm** [comment]
I didn't see where you said you got jquery from npm. Can you post the bundling script / CLI commands you're using?

**Comment by realph** [comment]
Yeah, sorry, I'm requiring jQuery from npm.

    // Bundle JS and minify
    gulp.task('js', function () {
      var browserified = transform(function(filename) {
        var b = browserify(filename);
        return b.bundle();
      });

      return gulp.src(['./src/js/app.js', './src/js/vendors/*.js'])
        .pipe(browserified)
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(uglify())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./_site/public/js'))
        .pipe(browserSync.reload({stream:true}));
    });

**Comment by jmm** [comment]
The real problem here is the way the plugin sets itself up. Try this:

```js
(function () {
  // entire plugin
}).call({jQuery: $});
```

You could alternatively try this:

```js
window.jQuery = $;
(function () {
  // entire plugin
}).call(window);
```

When browserifying the jQuery npm module it looks like it doesn't automatically attach itself to `window`.

**Comment by realph** [comment]
Thanks! Is there a reason the jQuery module doesn't attach itself to window and it has to be done manually?

**Comment by jmm** [comment]
I'm not sure what the reasoning is there. If it's loaded in a CommonJ-esque environment and there's a `window.document`, then it *doesn't* attach itself to `window`.
