### ISSUE TITLE
Using Fluidbox with Browserify

### ISSUE THREAD

**Issue by realph** [substack/node-browserify#1164]
So, I'm using Browserify on a project for the first time and I'm trying to use a plugin called [Fluidbox](https://github.com/terrymun/Fluidbox/blob/master/jquery.fluidbox.js). I've managed to get it working on my page, no console errors, but there's a weird visual bug that's happening. 

However, if I include the plugin the traditional way, with two script tags (jQuery and Fluidbox from cdnjs) it works perfectly. I figure it has something to do with the countless amounts of references to `this`, perhaps?

This is how I've got it set up:

**app.js**

    var $ = require('jquery');
    var fb = require('./vendors/fluidbox.js');

    fb();

    $('.gallery a[rel="lightbox"]').fluidbox({
       viewportFill: 0.9,
       immediateOpen: true
    });

**fluidbox.js**

    var jQuery = require('jquery');

    module.exports = function() {
      // Fluidbox plugin goes here
      ...
    };

Any help in working out what's wrong here would be appreciated. Thanks in advance!

**Comment by jmm** [comment]
What's the visual bug? It is the same versions of jQuery and Fluidbox with both loading methods (A) browserify B) `<script>` / CDN)?

**Comment by realph** [comment]
This is the visual bug I'm getting. The `.fluidbox-wrap`s are taller than the image inside it. See the illustration below:

![screen shot 2015-03-13 at 01 06 56](https://cloud.githubusercontent.com/assets/2334951/6641224/72aeccfa-c994-11e4-9a8b-96c0a77f4276.png)

I'm using the same versions. If I do it the traditional way, I load the scripts with cdnjs and I have an app.js which runs the plugin:

**app.js**

    $('.gallery a[rel="lightbox"]').fluidbox({
       viewportFill: 0.9,
       immediateOpen: true
    });

And it works perfectly. No taller-than-usual `.fluidbox-wrap`s.

**Comment by jmm** [comment]
Can you post minimal examples with / without browserify somewhere? I'm not immediately sure how browserify could cause this and it's probably going to be impossible to figure out what's happening without those examples.

**Comment by realph** [comment]
Well, this is embarrassing. I've setup a CodePen [over here](http://codepen.io/realph/pen/WbamaO), but I'm having the same issue with the large `.fluidbox-wrap`s. You reckon this proves Browserify isn't the problem?

**Comment by jmm** [comment]
> You reckon this proves Browserify isn't the problem?

It makes me even more skeptical that browserify has anything to do with it. In your codepen it looks like a `div` the same height as each image is being inserted following the image.

**Comment by jmm** [comment]
If this is still a problem please open a new issue with a minimal reproduction that isolates the cause to browserify.
