### ISSUE TITLE
npm WARN deprecated native-buffer-browserify@2.0.17

### ISSUE THREAD

**Issue by MAustinMMDP** [substack/node-browserify#1165]
FYI: 
npm WARN deprecated native-buffer-browserify@2.0.17: please use  (https://www.npmjs.org/package/buffer) instead. this module was
renamed.

**Comment by substack** [comment]
What version are you getting that message from? `find -name native-buffer-browserify` doesn't show anything under the latest dependency snapshot on 9.0.3.

**Comment by feross** [comment]
Yeah, this message would only get printed if your package (or one you're depending on) is using a really old version of browserify. In any case, it's not an error. Browserify has long stopped depending on the deprecated package :)
