### ISSUE TITLE
When running browserify command, "Cannot find module" if using wildcards in Windows

### ISSUE THREAD

**Issue by awvalenti** [substack/node-browserify#1170]
When I run on Windows:
* browserify *.js -o bundle.js

It says:
* Cannot find module 'C:\myproject\\*.js' from 'C:\myproject'

It also happens using \*\*/\*.js. It only happens on normal cmd, not on Git Bash, which simulates UNIX environment.

Seems to be the same problem as https://github.com/substack/node-browserify/issues/865. But I'm not using Azure environment.

**Comment by nikku** [comment]
Have never seen wildcards working using the browserify commandline. List all files explicitly instead.

**Comment by chad-autry** [comment]
I don't think listing files explicitly is an appropriate solution. In particular when building test bundles as mentioned in the hand book it is extremely handy.

Luckily, I think this is a fairly easy to solve problem. See my fork https://github.com/chad-autry/node-browserify/commit/9ff7c55cc67a7ddbc64f8e7270bcd75fcc72ce2f

That commit fixes things to me, though I am a bit lost on how to create a test case for it.

**Comment by traviscooper** [comment]
+1

**Comment by franleplant** [comment]
+1 for this! What is the state of the PR?

**Comment by substack** [comment]
It doesn't sound like it should be browserify's job to solve missing features in particular shells. There are thousands of shells on hundreds of platforms.

**Comment by franleplant** [comment]
@substack perhaps it could be nice to have a glob-cli that homogenizes those difference and improves portability and composition?



```shell
glob *.js | browserify -o output.js

#or perhaps

browserify (glob '*.js') -o output.js
```

I dont know Im just throwing an idea :)

**Comment by nmn** [comment]
I don't think browserify needs to support this feature.

**Comment by chad-autry** [comment]
So making a bit more noise,

I believe the changes I made to the pull request address the concerns about the code itself originally not being a good fit for browserify. There were no more follow up comments after the initial issues, I'm guessing it hasn't been re-reviewed.

So far as whether this change is a good fit for Browserify or not, the Browserify Handbook is currently incorrect. It states under the testing section

> Putting together all these steps, we can configure package.json with a test script:
>
>{
>  "name": "hundreder",
>  "version": "1.0.0",
>  "main": "index.js",
>  "devDependencies": {
>    "tape": "^2.13.1",
 >   "testling": "^1.6.1"
 > },
 > "scripts": {
 >   "test": "tape test/*.js",
 >   "test-browser": "browserify test/*.js | testlingify"
 > }
>}

That is not cross-platform compatible, and there is no good workaround on Windows. You can't do variable substitution in an npm script, and you can't pipe a list of files into browserify.

Piping a list of files into browserify would be franleplant's suggestion. While I'd accept it as a workaround, my pull request is already there and makes the handbook example cross platform compatible.

**Comment by Lucas-C** [comment]
What's the status of this issue ?
I'd really like this feature, thanks for taking the time to implement it @chad-autry

**Comment by karliky** [comment]
I'm having this problem in windows 10

**Comment by RyanZim** [comment]
@substack 

> It doesn't sound like it should be browserify's job to solve missing features in particular shells.

I respectfully disagree. I am quite surprised that browserify does not support this. For those of us that use npm as a build tool, libraries expanding globs is a must for cross-platform scripts. There is no good cross-platform workaround. Browserify already requires `glob` for other uses; it would be trivial to add this.

**Comment by substack** [comment]
Expanding globs is your shell's job. If you see a piece of shell code on the internet, you need to make sure it works with whatever shell you're using and port to your local shell as necessary. Some shells do not have many features, such as the default windows shell. Consider using a more featureful shell.

**Comment by RyanZim** [comment]
You're missing my point. npm scripts run on the system default shell. On windows that is the (bad) cmd.exe.

**Comment by chad-autry** [comment]
As I said in another issue closed as duplicate

The following usage from the handbook does not work on windows
```
"scripts": {
    "test": "tape test/*.js test/server/*.js",
    "test-browser": "browserify test/*.js test/browser/*.js | testlingify"
  }
```
glob is already in the dependencies list, and is used for the --ignore, --exclude, and --external options.

But whatever. I'd already given up on this PR. I may delete my fork once my own projects are converted to webpack. I suggest anyone interested pull the patch before then.

**Comment by terinjokes** [comment]
@substack since we've already have the glob dependency and we recognize
that the behavior on Windows is unfortunate, why not change this?

In an ideal world I would agree that this is outside the scope of
Browserify, but considering the circumstances I think we should merge this.

**Comment by aguynamedben** [comment]
Well that was a fun read
