### ISSUE TITLE
Browserify api generating undefined deps on ubuntu

### ISSUE THREAD

**Issue by onurkaracali** [substack/node-browserify#1176]
I Have 2 js modules, names : main.js and module.js.

main.js :
var k = require('./module');
var t = k(3,4);

module.js:
module.exports = function(a,b) {
    return a+b;
}
and i am running browserify in a js file that named build.js, I want to bundle this two js files and display output in stdout.
my build js is here, its very simple :

var browserify = require('browserify');
var b = browserify({
    basedir: './src/app/',
    entries: ['./main.js', './module.js']
});
b.bundle().pipe(process.stdout);

When browserify finishes bundle i see this output, and browserify generating undefined dependencies.
Here is output :

(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var k = require('./module');
var t = k(3,4);
},{"./module":undefined}],2:[function(require,module,exports){
module.exports = function(a,b) {
    return a+b;
}
},{}]},{},[1,2]);

As you can see, it generated -> {"./module":undefined}
iam using ^9.0.3 version of browserify

**Comment by jmm** [comment]
Thanks for your report. Please see https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify#markup and update your post accordingly.

**Comment by jmm** [comment]
@onurkaracali I'm closing this issue due to lack of feedback. If it's still a problem please open a new issue following the guidelines in [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify). Also, for a reproduction that requires several files please create a repo with the files if possible.
