### ISSUE TITLE
Q stops working with Browserify >= 8.1.0 due to nextTick changes

### ISSUE THREAD

**Issue by slorber** [substack/node-browserify#1179]
Q works fine with Browserify 8.0.3 but has serious problems since 8.1.0.
This is related to changes done in nextTick implementation of node-process: https://github.com/substack/node-browserify/pull/1018

Related Q issue: https://github.com/kriskowal/q/issues/669

I don't know who of Q or Browserify should fix this but this makes Q unreliable in production.

**Comment by slorber** [comment]
A PR is available here https://github.com/defunctzombie/node-process/pull/37

**Comment by slorber** [comment]
@substack @defunctzombie this can now be solved by uprading "process" dependency to 0.11 right?

**Comment by zertosh** [comment]
@slorber It's not just flipping the version. A couple of tests fail for the reasons in https://github.com/substack/insert-module-globals/pull/42 (under process to ^0.10.0). I'll try to get to it tmw.
