### ISSUE TITLE
Accept glob string for [entry files] 

### ISSUE THREAD

**Issue by chad-autry** [substack/node-browserify#1184]
browserify depends on the OS to expand the [entry files] in the command usage: browserify [entry files] {OPTIONS}

Thus the following usage from the handbook does not work on windows
```json
"scripts": {
    "test": "tape test/*.js test/server/*.js",
    "test-browser": "browserify test/*.js test/browser/*.js | testlingify"
  }
```

glob is already in the dependencies list, and is used for the --ignore, --exclude, and --external options.

**Comment by nikku** [comment]
Related to #1170

**Comment by chad-autry** [comment]
I agree, same issue. I will move there.
