### ISSUE TITLE
Npm published version 9.0.5 does not include index.js

### ISSUE THREAD

**Issue by benjroy** [substack/node-browserify#1188]
It exists in the tarball for the v9.0.5 tag in this repo, but when you 
```npm install browserify```, index.js is missing, effectively breaking any ```require('browserify');``` call.

```
ls -al node_modules/browserify/
total 136
drwxr-xr-x   12 benjamin  staff    408 Apr  2 17:41 .
drwxr-xr-x    4 benjamin  staff    136 Apr  2 17:41 ..
-rw-r--r--    1 benjamin  staff    116 Mar 13 19:39 .travis.yml
-rw-r--r--    1 benjamin  staff   2802 Dec 26 12:24 LICENSE
drwxr-xr-x    6 benjamin  staff    204 Apr  2 17:41 bin
-rw-r--r--    1 benjamin  staff  28346 Apr  2 16:48 changelog.markdown
drwxr-xr-x    5 benjamin  staff    170 Apr  2 17:41 example
drwxr-xr-x    5 benjamin  staff    170 Apr  2 17:41 lib
drwxr-xr-x   53 benjamin  staff   1802 Apr  2 17:41 node_modules
-rw-r--r--    1 benjamin  staff   3810 Apr  2 17:41 package.json
-rw-r--r--    1 benjamin  staff  24665 Mar 31 22:08 readme.markdown
drwxr-xr-x  170 benjamin  staff   5780 Apr  2 17:41 test
```

**Comment by benjroy** [comment]
grunt-browserify has browserify dependency at ^9.0.3, so it automatically installs v9.0.5.

My CI system is hosed until a working v9.0.6 is published.

**Comment by tetsuo** [comment]
:hankey:

**Comment by Myztiq** [comment]
:hankey:  :( Broke my builds

**Comment by SomeKittens** [comment]
Can confirm, broke our Grunt.

**Comment by tilgovi** [comment]
:tada:

**Comment by Nathan219** [comment]
Please fix this ASAP!

**Comment by stas-webdev** [comment]
I broke my brain trying to find my browserify module(
"Error: Cannot find module 'browserify'"

**Comment by stas-webdev** [comment]
terinjokes published a minute ago
9.0.6 is the latest of 436 releases

thanks for quick fixing

**Comment by benjroy** [comment]
Yep.  Builds are running again on my system.  9.0.6 fixed the issue.

Thanks so much for the fast fix. :+1:
