### ISSUE TITLE
9.0.6 : Cannot catch errors + have to call bundle() twice

### ISSUE THREAD

**Issue by cblavier** [substack/node-browserify#1194]
Hey, 

I have 2 issues in my gulp + watchify + browserify setup with the latest browserify build. Reverting back to browserify 9.0.4 fixed the issues:

- after any watchify update, I have to call `bundle()` twice to get my changes in the generated bundle
- I can no longer catch bundle() errors (with `on('error')`)

Here is the relevant piece of my Gulpfile: https://gist.github.com/cblavier/887346babc2ff173dfaf

Thanks,
Christian

**Comment by Trufi** [comment]
+1 and gulp + watchify + browserify is very slow in 9.0.6, but good in 9.0.3
