### ISSUE TITLE
9.0.6 breaks build

### ISSUE THREAD

**Issue by lambert-velir** [substack/node-browserify#1196]
I'm using gulp with browserify and the 9.0.6 breaks my build.  This is the error I'm getting:

```
_stream_readable.js:583
    var written = dest.write(chunk);
                       ^
TypeError: Object #<Readable> has no method 'write'
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at _stream_readable.js:560:7
    at process._tickCallback (node.js:415:13)
```
I fixed it by putting ```"browserify": "=9.0.4",``` in my package.json, but I just wanted to let people know that 9.0.6 (and 9.0.5) have breaking changes in it.

**Comment by terinjokes** [comment]
@lambert-velir please see https://github.com/substack/node-browserify/issues/1191 and https://github.com/substack/node-browserify/issues/1044 for some alternatives.

b.bundle() has never been documented as a writable stream, an internal refactor in a previous version leaked a writable stream that sometimes worked in simple cases (and failed in cryptic ways in more advance cases), and 9.0.5/9.0.6 restores the correct behavior.
