### ISSUE TITLE
Pushing a stream to 'wrap' in the internal pipeline broke in 9.0.5

### ISSUE THREAD

**Issue by mantoni** [substack/node-browserify#1200]
Making the [output bundle readonly](https://github.com/substack/node-browserify/pull/1187) seems to break a feature that is very important to Mochify (See issue https://github.com/mantoni/mochify.js/issues/80).

When I push a stream to `b.pipeline.get('wrap')`, the stream is not part of the browserify output. The pipeline modification is done before the call to `bundle()`.

Please advice if there is anything I can do to work around the issue.

**Comment by pyrsmk** [comment]
Probably the same problem that I have with browserify >9.0.2 and merging streams in gulp.

**Comment by terinjokes** [comment]
Making the output bundle read-only had no effect on `b.pipeline`, it is the same [labeled-stream-splicer](https://www.npmjs.com/package/labeled-stream-splicer) it's documented to be.

I tried creating a reproducible case (front the root directory of node-browserify), and was unable to reproduce your report, I got the expected amount of "hello world"s, and a single "hello, spawn".

See https://gist.github.com/terinjokes/0b198b330fabb52b6b5f

**Comment by mantoni** [comment]
@terinjokes Thanks for looking into this. The only reproducible example that I know currently is the Mochify test suite (https://github.com/mantoni/mochify.js). I nailed browserify to v9.0.4 to make the tests pass. Upgrading browserify to any newer version causes half the test suite to fail. Since the only change seems to be the one that makes the pipeline readonly, I suspected it must have something to do with that.

**Comment by jokeyrhyme** [comment]
I had to update the way I use gulp after browserify 9.0.5. I used the following recipe for hints:
https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-transforms.md

**Comment by erykpiast** [comment]
@jokeyrhyme, how do you do it now? I used to combine JSHint and Browserify in the way that doesn't work now because of read-only stream. Probably I should learn how streams work, but well... (lazy programmer mode on). Anyway, I do it like that:

```javascript
gulp.src(files)
        .pipe(jshint())
        .pipe(bundler.bundle())
        .pipe(source(bundleName))
        .pipe(gulp.dest(bundleDir))
```
Seemed reasonable until that breaking change...

**Comment by mantoni** [comment]
I worked around the issue by using the browserify pipeline directly: https://github.com/mantoni/mochify.js/commit/efaf1b3b4683cbcbdcb4e2dfcd8ee3565be2514e

This is fine in my case since I'm extending the pipeline anyway. Still this feels wrong to me.

**Comment by jokeyrhyme** [comment]
@erykpiast oh, that recipe I linked is working perfectly for me now: https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-transforms.md

The original version of that guide was what I started with ages ago, and that version of the guide no longer works after browserify 9.0.5: https://github.com/gulpjs/gulp/blob/064e2fceb96/docs/recipes/browserify-transforms.md

**Comment by erykpiast** [comment]
Ok, get it, thank you! I have a problem because of JSHint, so I guess I have to fix that in some other way.

**Comment by mantoni** [comment]
For reasons that are beyond my understanding, this is not an issue anymore with `9.0.8`. Closing.
