### ISSUE TITLE
Closure.js Support

### ISSUE THREAD

**Issue by johnryan** [substack/node-browserify#1216]
I tried using browserify with a the libphonenumber package which uses closure.js. When I require it the browser throws an error: 
```
Uncaught TypeError: fs.readFileSync is not a function
```
Is this a known limitation or is there a workaround for this?

**Comment by terinjokes** [comment]
Browserify with the `brfs` transform supports inlining `fs.readFileSync`. Unfortunately, closure.js's load_script uses readFileSync with dynamic paths, which `brfs` can not handle.

This is a known limitation.
