### ISSUE TITLE
Constructor signature: `files` *and* `opts`?

### ISSUE THREAD

**Issue by jmm** [substack/node-browserify#1221]
The documented constructor signature is `(files=[] or opts={})`, but in reality you can pass `files` **and** `opts` -- `(files, opts)` -- and I'm pretty sure in the wild people do that all the time. Is there a notion the 2-arg signature may go away, or can that be documented and supported? It's not a big deal, but it's a bit more convenient, particularly when you have a single entry file and are setting some options. It's already implemented and if that's likely to continue it would be nice to just document it.

**Comment by terinjokes** [comment]
I don't have any problems with documenting this behavior. @substack ?

**Comment by substack** [comment]
Documenting this would be great. I don't plan on changing any signatures, they seem to be working fine.

**Comment by jmm** [comment]
Thanks @terinjokes and @substack. Look good?: #1226
