### ISSUE TITLE
Don't run noParse files through transforms

### ISSUE THREAD

**Issue by jonrimmer** [substack/node-browserify#1227]
If files are included in noParse, they should be excluded from the transforms. If I want to avoid parsing a library like jQuery, then I don't want to send it through Babel or ngAnnotate either.

**Comment by jmm** [comment]
Is it *always* going to be the case that if you `noParse` a file you also don't want transforms run on it?

**Comment by JonRimmer** [comment]
Maybe? The only use-case given for noParse in the documentation is avoiding parsing of 3rd party libraries like jQuery and three.js (which is what I'm using it for), and it doesn't seem like you'd want to run transformations on those.

Are people using noParse for things that do need transforming? If so maybe finer control is need, such as a separate noTransform config parameter.

**Comment by zertosh** [comment]
I think the onus of determining what to transform or not should fall on the transform itself. Most (if not all) the transforms I've seen offer some form of whitelisting/blacklisting - including [babel](https://babeljs.io/docs/usage/options/)/babelify.

**Comment by dwelle** [comment]
I agree with @zertosh. I myself am using transforms when `noParse` is active, because I still want to babelify the file.

**Comment by jmm** [comment]
@jonrimmer Thanks for the suggestion, but at least for now this seems too opinionated, so I'm going to close. This could be reevaluated based on additional information.
