### ISSUE TITLE
Acorn all the things!

### ISSUE THREAD

**Issue by zertosh** [substack/node-browserify#1229]
* PR: https://github.com/substack/node-syntax-error/pull/8 - bumps acorn from ~0.9.0 to ^1.0.3
* PR: https://github.com/substack/node-detective/pull/46 - bumps acorn from ~0.9.0 to ^1.0.3
* Issue: https://github.com/substack/lexical-scope/issues/21 tracks updating astw from ~1.1.0 to what should be ^2.0.0 after https://github.com/substack/astw/pull/7
  * PR: https://github.com/substack/astw/pull/7 - switches from esprima^2.1.0 to acorn^1.0.3

I know it's a long shot to get all these merged, but I'm trying anyway. Now that acorn is 1.x.x it can float with ^. And should go some ways towards helping with the bloat discussed in https://github.com/substack/node-browserify/issues/707.

**Comment by zertosh** [comment]
All merged! :smile:

**Comment by substack** [comment]
All merged. Plus added you as a collaborator on all those packages plus pre-emptively to all the JSONStream dependencies.

**Comment by zertosh** [comment]
Thanks!
