### ISSUE TITLE
directories.lib support

### ISSUE THREAD

**Issue by kuraga** [substack/node-browserify#1234]
Good day!

I'm working on a JavaScript package, say `framework`. Its  distribution files are in `dist/` directory. I'm `browserify`ing my application uses `framework`: `var component = require('framework/component');`, it's trying to find `framework/component.js` file but not `framework/dist/component.js`.

As I know, `package.json`'s [`directories.lib`](https://docs.npmjs.com/files/package.json#directories-lib) option can help me. But seems like `browserify` ignores it.

Am I correct or no? Thanks.

**Comment by jmm** [comment]
I may just not know about it, but I've never heard of `directories.lib` being used or relevant in the context of browserify. Is this just an issue for testing your package while developing it?

**Comment by terinjokes** [comment]
@kuraga you need to have "component.js" in the root folder of `framework`, or use `require('framework/dist/component')`.

Neither Browserify nor Node uses directories.lib as part of resolving dependencies.
