### ISSUE TITLE
browserify + chrome extension's getBackgroundPage()

### ISSUE THREAD

**Issue by nschloe** [substack/node-browserify#1235]
I'm using browserify to manage a Chrome extension, and while in general it appears to work well, there's a problem that comes with browserify embedding the library code in the spaghetti carbonara that is
```
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
[...]
```
I noticed that, unlike advertised, e.g., [here](http://stackoverflow.com/a/9538625/353337), that you can't access variables defined in a background page (`chrome.extension.getBackgroundPage()`).

I'm not sure what kind of magic (if any) is behind `chrome.extension.getBackgroundPage()`, but maybe someone else has an idea.

**Comment by terinjokes** [comment]
@nschloe nothing in that snippet will change what exists in global scope, where the `chrome` variable would be found. That "spaghetti carbonara" can be view unpacked here: https://github.com/substack/browser-pack/blob/39fc68d8a3b4a6451ef2c50a5b93be08f3110bfa/prelude.js

Do you have a git repo we can clone to reproduce?

**Comment by nschloe** [comment]
> Do you have a git repo we can clone to reproduce?

@terinjokes For sure. I don't want to make this hard on you guys, but here is how you can reproduce it:

Clone https://github.com/paperhive/paperhive-frontend,
```
$ npm install && bower install && DEBUG=1 gulp
```
then open Chrome/Chromium, go to chrome://extensions/, enable developer mode, load unpacked extension from the `build/` directory created with gulp above.

Hopefully, a little icon will appear in your browser bar. Click it, in the popup click right, inspect element and console. There you see the literal output of `src/scripts/popup.js`, namely of
```
var bg = chrome.extension.getBackgroundPage();
console.log(bg);
console.log(bg.iii);
```
The last output is `undefined` (although `iii` is defined in `src/scripts/background.js`).

In contrast now, remove the spaghetti carbonara from `build/scripts/background.js` (that's `build' indeed), reload the extension, and see `123` in the console output instead of `undefined`.

**Comment by jmm** [comment]
Are you saying that you're getting `chrome.extension.getBackgroundPage()` but you just can access a prop (`iii`) on it? `chrome.extension.getBackgroundPage()` returns a window object, right? How is your `iii` variable declared? I'm wondering if this is just a run of the mill variable scoping issue?

**Comment by terinjokes** [comment]
I'm thinking the same thing, that you need to create `iii` as `global.iii`, otherwise you're creating the variable inside the module scope instead of the window's scope.

**Comment by nschloe** [comment]
@jmm @terinjokes Declaring `iii` as
```
global.iii = 123;
```
indeed leads to the expected behavior. Thanks for the hint!

Would you care to explain (or link to an explanation) about what the "spaghetti" does? Apparently one of its effects is proper namespace isolation here. Otherwise feel free to just close this one.

**Comment by jmm** [comment]
@nschloe excellent! That's the browser-pack prelude, which becomes the spaghetti you referenced when minified. It does things like setup the `require()` function used inside the bundle. But in any case, when you browserify a module it's wrapped in a function, so if it includes `var` statements (I assume you had `var iii = ...`), those will be scoped to that function, not global.

**Comment by nschloe** [comment]
Perfect explanation, thanks a lot!
