### ISSUE TITLE
Browserify + NodeWebkit - how to unblock the fs module? 

### ISSUE THREAD

**Issue by hawkerboy7** [substack/node-browserify#1241]
Hi.
Using `Nodewebkit (nw)` you can use the `fs` module (and others) on the 'client'-side (since `nw` allows you to access the 'server'-side from the DOM ~I hope I am saying this correctly~).

However (to stop error's on a regular client-side I guess) browserify resolves a require('fs') to an empty object. I want to disable this functionality for all modules like `fs`, how can this be achieved?

So outside the app.bundle.js the `require('fs');` call works fine but inside it returns `{}`
```javascript
// app.bundle.js


var fs = require(f's');
// fs works here

(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"/path/to/my/app/build/client/js/app.js":[function(require,module,exports){
var Client, Server, fs, start;

fs = require('fs');
console.log(fs);
// fs returns {}

window.$ = require('jquery');
window.jQuery = window.$;

// jQuery and others like underscore work fine

// The rest of the bundle....
```

**Comment by substack** [comment]
Check out the `--node` feature that landed in 10.1.0. Specifically, `--no-builtins` will turn off the `fs` shim. Or you can `--exclude fs`.

**Comment by hawkerboy7** [comment]
Thank you I will try that!

**Comment by dotbloup** [comment]
It would perhaps work to add 
```
externals: {
        
        'fs': 'commonjs fs'
    },
``` to the module.exports of webpack.config.js

This would exclude any require('fs') from the webpack job.
