### ISSUE TITLE
cannot install browserify using npm on os x 10.10

### ISSUE THREAD

**Issue by dszabo** [substack/node-browserify#1249]
I installed node and npm using this information: https://gist.github.com/DanHerbert/9520689
```node: v0.12.0
 npm: 2.9.0```

However, still, when I try to install browserify with `npm install -g browserify`, I get this:

```
bash-3.2$ npm install -g browserify
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/iwo/.node/bin/npm" "install" "-g" "browserify"
npm ERR! node v0.12.0
npm ERR! npm  v2.9.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: JSONStream@'>=1.0.3 <2.0.0'
```

Could someone please enlighten me? Thanks!

**Comment by terinjokes** [comment]
Thanks for your report. The recent `npm` update has grown an unexpected preference against module names with capital letters, and we're currently fixing the dependences.

**Comment by perfectsquircle** [comment]
+1

**Comment by zertosh** [comment]
Fixed now in browserify@10.1.2

**Comment by terinjokes** [comment]
Resolved in browserify@10.1.2. For older browserify releases, go back to npm@2.8.x for the time being.

**Comment by stevengill** [comment]
last few releases of cordova are all breaking now because of this. Using and older version of npm doesn't seem to help. Something on the registry must have changed.

**Comment by dszabo** [comment]
thanks for the quick fix

**Comment by zertosh** [comment]
<del>go back to npm@2.8.x for the time being.</del> It seems it affects more versions of npm. There is an ongoing discussion in https://github.com/substack/node-browserify/pull/1247.

browserify@10.1.2 works perfectly. It seems to only affect 5.0.0-10.1.1.
