### ISSUE TITLE
require("net") returns empty object

### ISSUE THREAD

**Issue by rickdog** [substack/node-browserify#1255]
require("net") returns an empty object.
I've verified that require("net") returns a valid module when used with node.
Is there a workaround for this?

**Comment by substack** [comment]
That's how it's supposed to work. Browsers don't have generic tcp implementations. The empty object is intended to prevent `require('net')` from failing on modules that otherwise work in the browser.

**Comment by darrrk** [comment]
Maybe would be cool to create browserify-net over [websockify](https://github.com/kanaka/websockify), which can pass TCP connection through WebSocket
