### ISSUE TITLE
Expose a `globalTransform` option in the constructor

### ISSUE THREAD

**Issue by peteschaffner** [substack/node-browserify#1267]
There is an option for `transform`, but not `globalTransform`. Was this by design?

**Comment by substack** [comment]
There's not a big reason for this. You can pass options in array form to get globals:

```
browserify({
    transform: [[ 'brfs', { global: true } ]]
})
```

**Comment by peteschaffner** [comment]
Oh good to know! I will close this since it is doable :)

**Comment by jmm** [comment]
Tracking documentation of this in #1224.
