### ISSUE TITLE
b.require('path/to/socket.io-client') issn't exposed as window.io

### ISSUE THREAD

**Issue by hawkerboy7** [substack/node-browserify#1270]
I am writing a module in which I want to add `socket.io-client` to the `app.bundle.js`.
If the browser opens / runs `app.bundle.js` I want `window.io` to contain `socket.io-client` as if I have written in my main file that get's bundled:
```coffeescript
window.io = require 'socket.io-client'
````

I used the following line: 
```coffeescript
b.require 'path/to/node_modules/socket.io-client', expose: 'io'
```
I think I don't understand the expose option correctly?
I also tried `expose: 'window.io'` with no luck.

**Comment by substack** [comment]
`b.require()` with `opts.expose = 'io'` means that when you `require('io')` you will get the socket.io-client library. `b.require()` also loads a package into the bundle even if you didn't require() it anywhere in any of the other files.

You only need the first part:

```
window.io = require 'socket.io-client'
```

I don't see why you have the second part.

**Comment by hawkerboy7** [comment]
Ahh ok thank you for the explaination. <br>
I'll try to explain why I need the second part:

My module "A" is a module that compiles `.coffee .less .jade` and supports `browserify` and `browser-sync` and some other things [de-builder](https://github.com/hawkerboy7/de-builder).
But `browser-sync` needs `socket.io-client` bound to `window.io`.

If someone installs my module "A" he might not need socket.io-client. So he or she __won't__ have 
```coffeescript
window.io = require 'socket.io-client'
```
So now browser-sync won't work anymore. Therefore I want to add `socket.io-client` to the `app.bundle.js` and also store it in `window.io`.
