### ISSUE TITLE
termlib - firefox gives syntax error but safari don't

### ISSUE THREAD

**Issue by colmsjo** [substack/node-browserify#1275]
I'm using termlib in an app. It has worked fine until I started to use browserify. Now Firefox gives a syntax error but Safari still works.

This is the compiled code: https://gist.github.com/colmsjo/9f16da5d219d47748557

Any suggestions?

**Comment by jmm** [comment]
What else does the error message say? What version of Firefox (including OS)?

**Comment by colmsjo** [comment]
OSX 10.10.3, Firefox version 36. It just says syntax error (in Swedish). There is also a 'not welfomred error' but I don't think it is related.

Here are the errors:
```
ej välformat termlib.js:1:1
syntaxfel term2bundle.js:1:1
```

**Comment by jmm** [comment]
Can you check if there's a BOM at the beginning of termlib?

**Comment by colmsjo** [comment]
What is a BOM?



// mvh / best regards

Jonas Colmsjö | jonas@gizur.com | +46-707-924402 | @colmsjo | www.gizur.com

**Comment by zertosh** [comment]
At least the uploaded file doesn't:

```
curl https://gist.githubusercontent.com/colmsjo/9f16da5d219d47748557/raw/867b57394d83bad322407f017f77a3fa9b70df12/gistfile1.txt -O
node -p 'require("fs").readFileSync("gistfile1.txt","utf8").match(/\ufeff/)'
```

@colmsjo BOM is the invisible character `\ufeff`. If you run your outfile file through uglify, and run that, do you still have the same problem?

**Comment by zertosh** [comment]
@colmsjo Also, can you try it without the source map?

**Comment by colmsjo** [comment]
It works without the source map.

**Comment by colmsjo** [comment]
I turned source maps on and uglify on and this also works.

**Comment by zertosh** [comment]
@colmsjo One of the things that recently changed was that sourcemaps got a [`charset`](https://github.com/thlorenz/inline-source-map/blob/fba10bb2b80e9236ce2c85d83f12322a1a717f5c/index.js#L104). Your sourcemap starts with:

```
//# sourceMappingURL=data:application/json;charset:utf-8;base64,....stuff...
```

can you trying manually changing it to:

```
//# sourceMappingURL=data:application/json;base64,....stuff...
```

and see if that works?

**Comment by colmsjo** [comment]
I think I found the cause. I cache the app in IndexedDB and then load it in the browser. I suspect that the problem is that I try to fetch the app before it has been fully saved. It works if I simply fetch it from IndexedDB without fetching it first. It also works with the smaller uglified version.
