### ISSUE TITLE
Either `process` or `fs` is not defined or empty using the bundle for node-webkit

### ISSUE THREAD

**Issue by hawkerboy7** [substack/node-browserify#1277]
I am using `browserify` to make a bundle which I am using for my `node-webkit` application.

I wanted to access `fs`. This resulted in `{}`. I was told to use `--no-builtins`. I am accessing the API directly so that means: `options.builtins = false;` This worked!

Now I have another problem. I want to access `process` but whenever I put in in my code I get the error: `Uncaught Error: Cannot find module '_process'`. I also have a few modules installed that also need to access `process` and now can't. So if I require one of those modules I get the same error.

So I tried some options setting them `true or false`:
```javascript
options.node
options.bare
options.commondir
options.builtins
options.insertGlobalVars
options.browserField
```
But I can't seem to get this simple example code working:
```javascript
fs = require('fs');
console.log(fs);
console.log(process);
```

Just to be clear:
```javascript
// Outside the bundle
fs = require('fs');
console.log(fs); -> Works
console.log(process); -> Works

// Inside the bundle
(function(){ // lots of bundle stuff
var fs;
fs = require('fs');
console.log(fs);
console.log(process);

// Either Uncaught Error: Cannot find module '_process'
// or
// fs == {} and then process Works
}
```

browserify 10.2.1

**Comment by hawkerboy7** [comment]
Anyone any idea's?

**Comment by hawkerboy7** [comment]
Solved with the following code, thanks to https://github.com/sedge

```javascript
var options = {
  insertGlobalVars: {
    process: function() { return; }
  }
};
```

**Comment by t128** [comment]
thx,

fixed my code too:
```
var fs = require('fs');
var browserify = require('browserify');
var babelify = require('babelify');
var insertGlobals = require('insert-module-globals');

browserify('./src/main.js', {
	builtins: false,
	commondir: false,
	insertGlobalVars: {
		__filename: insertGlobals.vars.__filename,
		__dirname: insertGlobals.vars.__dirname,
		process: function() {
			return;
		},
	},
	browserField: false,
})
	.transform(babelify.configure({optional: ['runtime']}))
	.bundle()
	.pipe(fs.createWriteStream('./build/app.js'));

```

**Comment by EvanCarroll** [comment]
options.node doesn't exist if it did, this wouldn't be an issue.
