### ISSUE TITLE
Assigning global.x is broken after updating

### ISSUE THREAD

**Issue by adam-lynch** [substack/node-browserify#1282]
After going from browserify 4.2.1 to 10.2.1, my global variable assignments like `global.x = 1` aren't working anymore. i.e. `x` doesn't exist in required files.

I've tried setting `opts.insertGlobals` to `true` but it doesn't help.

**Comment by zertosh** [comment]
Works for me. Can you provide a repro case? Here is what I did:

```
echo 'global.x = 1;' | browserify - -o built.js
echo '<script src="built.js"></script>' > index.html
```

Opened `index.html` in Chrome and `window.x === 1` is true.

**Comment by adam-lynch** [comment]
@zertosh thanks for the quick reply.

Apologies, this seems to be only a problem in [NW.js](https://github.com/nwjs/nw.js) and is fine in a real browser. I've created this repo to reproduce: https://github.com/adam-lynch/browserify-nw-global-problem. I guess it's because `global` and `window` exist already? 

It wouldn't surprise me if you came back and told me our code was relying on a browserify bug to work.

**Comment by zertosh** [comment]
I took a look at your repo (in the future please don't submit coffeescript nor gulp code - it just adds more debugging complexity). It seems that NW.js has a variable in the global scope called `global`, but it's not  the global object. The global object continues to be `window`, so that trips up the browserify [global shim](https://github.com/substack/insert-module-globals/blob/b247821160abf231580bd316f7c00efbe4498ebe/index.js#L14-L17). I don't know anything about NW.js, so I don't know how wise my solutions are for that environment, you should probably ask there, but here they are:

1. You can change the order of the typeof checks, by passing your own global shim that checks for `window`/`self` first, via `insertGlobalVars`. That's what the [old shim](https://github.com/substack/insert-module-globals/commit/60ed4986c6bbb2635bc46859fa2277c0469cb67a) did, and that's why it worked for you. It didn't check for `global`, but instead checked for `self` - which in NW.js is the global object (`self === window`).

2. The one I actually tried:

    ```coffee
        insertGlobalVars:
            global: () -> "Function('return this')()"
    ```
   
  That works, but I'm not sure if it's a good idea to grab the global object like that in NW.js.
  see http://stackoverflow.com/questions/3277182/how-to-get-the-global-object-in-javascript

**Comment by adam-lynch** [comment]
Interesting. 

So you're saying when we assigned something to `global.x` (with  `4.2.1`), it was just adding it to the `window`. Cool. So I guess then we hadn't thought about it much, we just assumed it was global everywhere. By everywhere I mean both of NW.js contexts; the Web and the Node context. `global: () -> "Function('return this')()"` sounds like it would work but I guess we shouldn't be doing this anyway in case we ever wanted to access something in the Node context. We should probably be more explicit about it and add some things to `global` and some to `window` or maybe even something else entirely. Sorry, thinking out loud here... Thanks!

**Comment by zertosh** [comment]
> So you're saying when we assigned something to `global.x` (with 4.2.1), it was just adding it to the window.

Yes, but it would be same in 10.2.1 if NW.js's `global === window`.

> `global: () -> "Function('return this')()"` sounds like it would work but I guess we shouldn't be doing this anyway in case we ever wanted to access something in the Node context.

That works everywhere (node.js, browsers, even nashorn). It's just that you're doing an `eval` and you might run into [Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/#eval-too) issues, if that's something you don't control on your host.

**Comment by jmm** [comment]
@zertosh 
> It seems that NW.js has a variable in the global scope called global, but it's not the global object.
> 
> You can change the order of the typeof checks, by passing your own global shim that checks for window/self first, via insertGlobalVars. That's what the old shim did

I've been thinking the ordering in that shim probably needs to be adjusted. See https://github.com/substack/node-browserify/issues/1189. It's the same situation as here, but in a regular browser (it's not specific to NW.js): if there's a `window.global` defined (which may happen just by virtue of a `<whatever id="global">` element in the document) when the bundle executes, then inside the bundle `global !== window`. As said in #1189, I'm thinking that perhaps the thing to do is check for `window` first, but something more specific like `window.document` or `window.document.{whatever}`.

**Comment by zertosh** [comment]
@jmm checking for `window.document` feels dangerous. I think checking for `self` first makes sense. Web Workers don't have a `window` but have a `self`. So, `self` then `global` then `window`?

**Comment by jmm** [comment]
@zertosh 
> checking for `window.document` feels dangerous.

How so?

> I think checking for `self` first makes sense. Web Workers don't have a `window` but have a `self`

What environment(s) is `self` for? It seemed like you were saying it's also for NW.js (which I know nothing about).

> So, `self` then `global` then `window`?

What about #1189? A random `global` or `self` global variable or `<el id="global">` or `<el id="self">` breaks `global` in the browser, where `window` is the global.

**Comment by zertosh** [comment]
>> checking for window.document feels dangerous.

> How so?

what we're supposed to be shimming is the global variable, not a DOM.

> What environment(s) is self for? It seemed like you were saying it's also for NW.js (which I know nothing about).

`self` is for [browsers](https://developer.mozilla.org/en-US/docs/Web/API/Window/self). NW.js provides the same environment as a browser. They're also trying to be node-compatible by providing the `global` variable that looks a lot like node's `global`, insofar as the properties it is has, but it lacks the reference equality with the _global_ variable.

> What about #1189? A random global or self global variable or <el id="global"> or <el id="self"> breaks global in the browser, where window is the global.

We can't account for every edge case - and every bad lib. Remember that you can always override the replacement value of `global` via `insertGlobalVars`, if you're in that 0.01%. So, `self` then `global` then `window`, optimizes for the common cases (browser then node) with a fallback to `window`.

**Comment by jmm** [comment]
@zertosh 
> `self` is for browsers.

It's coming back to me now, but oh wow, I forgot about that! Thanks for reminding me. I think I remember using that in the early 2000s when it made some difference in relation to interacting with windows opened via JS. Not sure if I've used or seen it anytime recently.

In any case, `window.self` is a `Replaceable` attribute, so testing for `self` is not a robust way to identify the global when considering the browser.
  
> NW.js provides the same environment as a browser. They're also trying to be node-compatible by providing the `global` variable that looks a lot like node's `global`, insofar as the properties it is has, but it lacks the reference equality with the `global` variable.

Thanks for the info. That sounds like a bit of a cluster. So the bottom line is that `window` should be the global in that environment?

> what we're supposed to be shimming is the global variable, not a DOM.

It doesn't have anything more to do with the DOM than accessing `window` in the first place does. `window` is part of DOM, not JavaScript. It's duck typing the host environment to get a more accurate cue which environment it is. Testing for presence of a `global` or `self` global variable can easily produce a false positive in the browser, like simply testing for `window` can produce a false positive in other environments. To be 100% clear, I'm suggesting something along these lines (but not necessarily literally this):

```js
window && window.document && window.document.implementation ? window
```

What specifically is the hazard in doing something like this?

> We can't account for every edge case - and every bad lib.

Of course, you're right. But I don't think this is *that* much of an edge case and it may not require doing anything too extreme to provide a more robust solution. I think this is enough of a gotcha that it's worth considering guarding against.

> Remember that you can always override the replacement value of `global` via `insertGlobalVars`, if you're in that 0.01%.

No one is going to, or should have to, do that preemptively. I think this is so easily broken in the real world that if there's a reasonable way to head it off it's worth doing.

> So, `self` then `global` then `window`, optimizes for the common cases (browser then node) with a fallback to `window`.

It's a moot point, but what's a scenario where you'd get to `window` in that scheme?

**Comment by adam-lynch** [comment]
@zertosh @jmm could one of you tell me or point me to what the current checks look like? Asking for https://github.com/trentm/node-bunyan/issues/301

**Comment by zertosh** [comment]
Simply that a global variable called `global` is referenced, and then the module is wrapped in an IIFE with the variable `global` coming into scope as an argument, with [this](https://github.com/substack/insert-module-globals/blob/cc99deeaf01de423838b2e96256230eb12e79ce5/index.js#L23-L28) value.

**Comment by zertosh** [comment]
...this is really hacky, but if whatever reason you can't turn off the globals transform, you can check for `global` but by not referencing it in the scope but by indirectly getting the global object and checking for it as a property on that: `Function('return this')().global`
