### ISSUE TITLE
Inserting "app" global throws error

### ISSUE THREAD

**Issue by adam-lynch** [substack/node-browserify#1283]
Version: 10.2.1

Usage:

```coffeescript
browserified = browserify
        entries: './example/index.coffee'
        extensions: ['.coffee']
        insertGlobals: true
        insertGlobalVars:
            app: ->
                app =
                    a: 1
                    b: 2
                return app

browserified.transform coffeeify

browserified.bundle()
    .pipe # gulp stuff
```

The error:

```shell
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parsing file /Users/adam/Code/GitHub/teamwork-chat-client/src/app/browser/scripts/index.coffee: Unexpected token (8:41)
  at Deps.parseDeps (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/module-deps/index.js:436:28)
  at fromSource (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/module-deps/index.js:375:44)
  at /Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/module-deps/index.js:369:17
  at ConcatStream.<anonymous> (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
  at ConcatStream.EventEmitter.emit (events.js:117:20)
  at finishMaybe (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
  at endWritable (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
  at ConcatStream.Writable.end (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
  at DuplexWrapper.onend (/Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
  at DuplexWrapper.g (events.js:180:16)
  at DuplexWrapper.EventEmitter.emit (events.js:117:20)
  at /Users/adam/Code/GitHub/teamwork-chat-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:934:16
  at process._tickDomainCallback (node.js:459:13)
```

If I try to inject an `app2` global instead, it bundles fine. I'm not sure why, I'm not sure where to look. I have some files named `app.coffee`, a directory named `app` (so I have requires which contain `..../app/....`), etc.

This might be related to #1282

**Comment by zertosh** [comment]
I'm not familiar with coffeescript, but I think you're returning the wrong type in for `app`. Check https://github.com/substack/insert-module-globals#insert-custom-globals. What you probably want to do is return `JSON.stringify({a: 1, b: 2})`.

This works for me:

```js
// app.js
console.log(app);
console.log(typeof app);
console.log(app.a);
```

```js
// build.js
var fs = require('fs');
var browserify = require('browserify');
var b = browserify(__dirname + '/app.js', {
  insertGlobalVars: {
    app: function() {
      return JSON.stringify({a: 1, b: 2});
    }
  }
});
b.bundle().pipe(fs.createWriteStream('app-built.js'));
```

```
node build.js
node -e 'require("./app-built.js");'
# output
{ a: 1, b: 2 }
object
1
```

**Comment by adam-lynch** [comment]
Again, thanks for the quick reply @zertosh :+1:.

Yeah, I think that might be the problem. I had looked over https://github.com/substack/insert-module-globals#insert-custom-globals already but must've only glanced. I saw the `Buffer` example and thought I could just return an object, not noticing that it was actually some browserify metadata.

After breaking down our code to a simpler example for #1282 and then applying this change, it works. You can see here if you like: https://github.com/adam-lynch/browserify-nw-global-problem/tree/insert-globals.

One small thing... the inserted variables aren't actually global, right? They're just global to the browserify bundle? Is it recommended to use `global.app = app` if I wanted to expose `app` or is there a better way via config or something?

**Comment by adam-lynch** [comment]
Interestingly as well, we have a certain pattern / flow of assigning / requiring which is broken if we use `insertGlobalVars` (I assume just because of how the global is inserted), i.e. a case where `app` doesn't exist. Previously we did a find and replace to insert `global.app = {a:1, ...}` and the pattern worked with that. If you're curious: https://github.com/adam-lynch/browserify-nw-global-problem/tree/insert_global_pattern

**Comment by zertosh** [comment]
glad it worked!

> One small thing... the inserted variables aren't actually global, right? They're just global to the browserify bundle? 

Each individual module that uses an inserted global gets wrapped in a closure, where the values are passed in via arguments. e.g.:

```js
// original
/*other code*/
console.log(app);
/*other code*/

// after insert-module-globals
(function(app) {
/*other code*/
console.log(app);
/*other code*/
}({a: 1, b: 2}))
```

> Is it recommended to use window.app = app if I wanted to expose app or is there a better way via config or something?

I think what you're asking is "how can anything that references `app` get the same `app` object, instead of it's own copy?" You could make a module with the "app" values, and let `insertGlobalVars` replace it with a `require` to it. So:

```js
// in my/project/globals/app.js
module.exports = {a: 1, b: 2};

// in your build
b = browserify({
  insertGlobalVars: {
    app: function() { return 'require("myAppGlobals")' }
  }
})
b.require(__dirname + '/my/project/globals/app.js', { expose: 'myAppGlobals' });
```

So then the wrapped modules would look like:

```js
// after insert-module-globals
(function(app) {
/*other code*/
console.log(app);
/*other code*/
}(require("myAppGlobals"));
```

It's important to use `expose` for the module that will house your "app" values because you need to be able to require it from any other module w/o knowing the relative path.

**Comment by adam-lynch** [comment]
>I think what you're asking is "how can anything that references app get the same app object, instead of it's own copy?" You could make a module with the "app" values, and let insertGlobalVars replace it with a require to it. So:

Actually, I just meant exposing it to stuff outside of the bundle; i.e. adding it to the `window`. But you answered a question I didn't know I needed to ask. I assumed it was all the same copy. (Maybe that's why the pattern I mentioned doesn't work; i.e. stuff added onto `app` weren't accessible in another file.) Thanks.

...actually I'm not sure is right. The way you phrased everything was like these app "values" would just be simple fixed values all originating from the same source. 1. We add all sorts of things onto our `app` in a lot of different files. 2. We create the original `app` object during our build so we'd have to either save it to disk or use streams to use `b.require`. I think we'll just go back to having `global.app = {}` in our `init.coffee` and a find + replace step in our gulp pipeline.

Thanks for the help.

**Comment by zertosh** [comment]
>  I assumed it was all the same copy.

It depends. If you use `insertGlobalVars: {app: function() { return '{"a":1,"b":2}'; }}`, then each module that references `app` will literally be wrapped in `(function(app) { /* your code */ }({"a":1,"b":2}))`. So every module gets its own of "app". But by using the `require("myAppGlobals")` pattern from above, they all get a reference to the "app" object.

> We create the original app object during our build so we'd have to either save it to disk or use streams to use `b.require`.

Hm, I guess I'm a bit confused by what you're trying to do - I'm inclined to think that `insertGlobalVars` is not what you're looking for. If you're generating some values during your build (like a git sha, or API key), which then you'd like to use in your app, I suggest you look at [envify](https://github.com/hughsk/envify). It inlines the values of `process.env.*` with the actual environment values or some predetermined object. Example:

```js
// in your gulpfile-ish
var b = browserify(/*stuff*/);
var envify = require('envify/custom');
b.transform(envify({
  API_KEY: '123',
  ASSET_SERVER: 'abc',
  COMPLEX: {a: 1, b: 2}
}));

// in your whatever.js
var apiKey = process.env.API_KEY;
console.log('http://' + process.env.ASSET_SERVER +
            '/?key=' + process.env.API_KEY);
if (process.env.COMPLEX !== process.env.COMPLEX) {
  // this will run because that's two instances of objects
  // so they are different
}

// after the transform
var apiKey = '123';
console.log('http://' + 'abc' +
            '/?key=' + '123');
if ({"a": 1, "b": 2} !== {"a": 1, "b": 2}) {
  // this will run because that's two instances of objects
  // so they are different
}
```

Notice that there is no wrapper - the values are actually inlined. Also notice that `COMPLEX` is the `JSON.stringify`ed version (I wouldn't do this w/o good reason).

Another strategy may be to have a single module with `module.exports = process.env.APP_OBJECT;`, and then require that throughout your code. I'm suggesting this because search and replace is error prone, envify actually looks at the AST.

**Comment by adam-lynch** [comment]
Thanks for that.

>Hm, I guess I'm a bit confused by what you're trying to do

It's not necessarily what we're trying to do but what we have done :see_no_evil:  haha. We inject an initial `app` object with some env stuff and our NW.js manifest (at `app.manifest`), then we tack all sorts of instances of classes, etc. onto it at runtime. We didn't properly understand what was happening when we did `global.app` either. Oh and we have some non-browserified stuff using `app` (i.e. via `window.app`) too. 

Ideally, we'd have structured things differently, separated things more cleanly, with multiple bundles and so on... but right now we have what we have. We'll start migrating towards a better structure (probably including using envify). P.S. using gulp-replace isn't so bad right now as we only use it for one thing (`window.app = {}`) which only exists in one place.

**Comment by zertosh** [comment]
> but right now we have what we have

sigh, I've been there... I've been there :disappointed: At least we know what's going on now. Feel free to open a new issue if anything else comes up.

**Comment by adam-lynch** [comment]
:+1:
