### ISSUE TITLE
`Error: EISDIR, read` error

### ISSUE THREAD

**Issue by olalonde** [substack/node-browserify#1284]
For some reason, browserify started throwing `Error: EISDIR, read` errors at me although it was working fine only minutes ago. I'm not really quite sure what changed but regardless I am getting this error now. Is there a cache I can clear somewhere? The file I want to browserify has a single `require('../')` in it. I tried to change it to `require('../index.js')` but getting the same error.

node 0.10.35

**Comment by zertosh** [comment]
@olalonde Can you be a bit more specific? Maybe a repro case?

**Comment by olalonde** [comment]
I would love to but I'm unable to reproduce it... I copied my project directory and the build works in the copied directory. Weird...

**Comment by zertosh** [comment]
well, case closed for lack of evidence then hehe

**Comment by olalonde** [comment]
Well, now: `touch test/index.js && browserify test/index.js` throws the same error. So it's not a problem inside the file... Maybe some invalid permissions on my path?

**Comment by zertosh** [comment]
I couldn't tell w/o more info, sorry

**Comment by olalonde** [comment]
I found the error... I had a `package.json` folder somewhere in a parent path, no idea how it got there.

**Comment by zertosh** [comment]
ah interesting. but why that error? can you show me the contents?

**Comment by olalonde** [comment]
You can copy-paste following script to reproduce:

```bash
mkdir btest
mkdir btest/package.json
mkdir btest/app
touch btest/app/index.js
cd btest
browserify app/index.js
```

Returns `Error: EISDIR, read`

Tested with browserify 10.2.1

**Comment by zertosh** [comment]
oh yeah that makes sense, `package.json` is actually a directory not a file

**Comment by olalonde** [comment]
Yeah, don't know how I ended up with a directory called `package.json` :( anyways, problem fixed now. Hopefully this will be helpful to someone some day :)
