### ISSUE TITLE
--no-browser-field flag not working

### ISSUE THREAD

**Issue by fynyky** [substack/node-browserify#1286]
When using the `--node` flag it correctly sets `argv.bare` to `true` and `argv.browserField` to `false`. However when using the `--no-browser-field` flag `argv.browserField` is `undefined`.

Discovered because `--node` was giving different behaviour than `--bare` and `--no-browser-field`

**Comment by substack** [comment]
It looks like internally it's using a camel cased version instead of a dashed version.

**Comment by substack** [comment]
Update: found it! There's a space in `'browserField '` in bin/args.js

**Comment by substack** [comment]
Fixed now in 10.2.3.
