### ISSUE TITLE
Linking local npm modules

### ISSUE THREAD

**Issue by eimfach** [substack/node-browserify#1299]
Since npm 2.0 you can link local npm modules in package.json:

    dependencies: {
      "core.module": "./modules/core"
    } 

If you run *npm install* these modules get installed into the *node_modules* folder.
I ask myself if browserify could manage to resolve these paths and include them into the build? So one would not need to *npm install* every time changes were made on this modules ?

**Comment by lelaurent** [comment]
That would seem like a nice feature!

**Comment by substack** [comment]
I think that feature is broken in npm v3, since I can't reproduce. I think it's best to leave this feature to npm, since node doesn't itself look at the package.json dependencies field and I think it's easier to form a mental model if browserify follows node closely.
