### ISSUE TITLE
net

### ISSUE THREAD

**Issue by darrrk** [substack/node-browserify#1302]
Maybe would be cool to create net shim over https://github.com/kanaka/websockify,
which can pass any TCP connection through WebSocket.

**Comment by substack** [comment]
You can do something like:

```
browserify -r websockify:net main.js
```

to map `net` to `websockify`.

**Comment by darrrk** [comment]
`websockify` not a `browserify` plugin and doesn't have nodejs/iojs compatible API of `net` module.
I create this issue for `net` module primarily, because want see it [in this list](https://github.com/substack/node-browserify#compatibility)
Maybe exists better solutions than `websockify`, that allow pass TCP through browser-compatible protocols.
With browserify `net` module you can build applications without backend, which can connect to PostgreSQL, Thrift, Redis e t. c.
It's cool!
