### ISSUE TITLE
sourceMapFile option - allow sourcemap paths relative to destination file

### ISSUE THREAD

**Issue by Rich-Harris** [substack/node-browserify#1303]
Hi all - background to this issue is https://github.com/Rich-Harris/sorcery/issues/15. It looks like the sourcemap paths browserify includes are relative to the project root, which causes problems if you're writing the generated bundle to somewhere else (like a `dist` folder). Would it be possible to have a `sourceMapFile` option (or similar) which is treated as the base for those relative paths? Alternatively, an option to generate absolute paths would work, though I suppose that's less broadly applicable.

Apologies if I've misunderstood the issue and there's an existing option or workaround!

**Comment by jmm** [comment]
@Rich-Harris I skimmed the issue and the readme and I don't 100% comprehend it right away, but let's see what we can figure out. You're talking about what values exactly, the `sources` elements? Those are fundamentally supposed to be URLs, not local paths, but perhaps you can work around that somehow.

**Comment by Rich-Harris** [comment]
Yep, the `sources` array. If I create `./bundle.js` from `./main.js` with browserify, and `./main.js` requires `"./foo"` and `"./bar"`, the `sources` array will list `foo.js` and `bar.js` which is fine because any further sourcemap processing will be able to find the original files. But if I create `./dist/bundle.js` the link is broken; subsequent tooling (whether it's responsible for generating a separate sourcemap file, composing sourcemap chains, determining which source files need to be deployed, or whatever) may look for `./dist/foo.js` and `./dist/bar.js`.

**Comment by jmm** [comment]
@Rich-Harris It sounds to me like that's trying to overload the intended purpose of the source map a lot. The `sources` elements are only supposed to be URLs that indicate where to request the source files relative to the location of the base (the source map, or by default the bundle URL). They also serve as labels for the files in the consumer (e.g. browser dev tools). You can set `sourceRoot` on a source map to provide the base for resolving relative `sources` values. Again, `sourceRoot` is intended to be a URL. Are you just wanting to be able to set `sourceRoot`?

**Comment by Rich-Harris** [comment]
Being able to control `sourceRoot` would probably suffice, now that you mention it - thanks.

> The `sources` elements are only supposed to be URLs that indicate where to request the source files relative to the location of the base

That's true - but a browser isn't the only place where `sources` is used (think of [source-map-support](https://github.com/evanw/node-source-map-support) for debugging in node.js - in that context, there's no distinction between a relative URL and a relative file path). For most purposes, the fact that `sourcesContent` is populated by browserify means that it's not a problem, but the fun starts when you have multiple sourcemap-generating transpilation steps, some of which may happen before browserify gets involved.

**Comment by jmm** [comment]
@Rich-Harris Yeah, I understand where you're coming from. The whole source mapping ecosystem still has a lot of kinks to work out. I think if you want this sooner rather than later, your best bet for now is probably to work up a plugin that does it using exorcist and perhaps some of @thlorenz's other source map related modules. I think you could probably hook in to the `wrap` pipeline phase to do it.

I don't think it's possible to specify `sourceRoot` right now. If you want that, I suggest you open a new feature request issue and reference this issue for context.

**Comment by Rich-Harris** [comment]
> The whole source mapping ecosystem still has a lot of kinks to work out.

Truth!

> I suggest you open a new feature request issue

[Done](https://github.com/substack/node-browserify/issues/1304). Thanks for looking into this

**Comment by jmm** [comment]
@Rich-Harris Thanks! I'm going to close this issue since #1304 is where the action will happen now.
