### ISSUE TITLE
ENOENT, open 'buffer' using --no-browser-field

### ISSUE THREAD

**Issue by xErik** [substack/node-browserify#1309]
(I am new to node and tried to solve this by going through the issues.)

### Setup

```
external-legacy-module  <-   my-wrapper-module    <-    my-application
                              standalone bundle.js       browserify pulling the 
                              by browserify              standalone bundle.js
```

### Context

I am trying to browserify a module (which wraps legacy code of an external bundle) as a standalone bundle. This standalone bundle works fine in the browser, including it via the `script` tag.

But I want to use it as a regular node module, too. Calling it from an application, using browserify, I figured that I need to provide the standalone bundle using the `browser field`. But this means that running browserify in the wrapper module itself needs to ignore the `browser field`. This results in an error.

### Config

Terminal (wrapper module):
```
browserify src/index.js --no-browser-field -g aliasify -s myHook -d -p [minifyify --no-map] -o build/bundle.js
Error: ENOENT, open 'buffer'
    at Error (native)
```
package.json (wrapper module):
```
"main": "./src/index.js",
[...]
"browser": "./build/bundle.js",
  "browserify": {
    "transform": [
      "aliasify"
    ]
  },
  "aliasify": {
    "aliases": {
      "fs": "./src/my-fs.js"
    }
  }
```

**Comment by jmm** [comment]
@xErik I'm a bit confused by your description:

> Calling it from an application, using browserify, I figured that I need to provide the standalone bundle using the browser field. But this means that running browserify in the wrapper module itself needs to ignore the browser field. This results in an error.

Can you please break that down differently?

In short, if your module will work in both node and the browser and you want to include it in a bundle, just `require()` it as usual. The `browser` field is for when you want to substitute a different, browser-specific version of the module instead of the regular node version.
