### ISSUE TITLE
Error: Cannot find module './object' : require('./standalonebundle.js')

### ISSUE THREAD

**Issue by xErik** [substack/node-browserify#1310]
(I am new to node.)

### Webapp

1. I generated a `standalonebundle.js`, which works fine in the browser via the `script` tag, via:

```
browserify src/index.js -g aliasify -s myHook -d -p [minifyify --no-map] -o build/standalonebundle.js
```

2. I copied it into another module, next to the source code in `./src`
3. I did 'require('./standalonebundle.js')' in `./src`
4. Starting my web-app (which gets browserified itself), I get the error:
````
events.js:85
      throw er; // Unhandled 'error' event

Error: Cannot find module './object' from '[path]/src
````

### Local test

1. I created a test.js with 'require('./standalonebundle.js')'
2. I get the error:

```
node test.js 

[path]my-browserified-0.1.18.js:2
typeof navigator||!/MSIE [1-9]\./.test(navigator.userAgent)){var t=e.document,
                                                                    ^
TypeError: Cannot read property 'document' of undefined
    at [path]my-browserified-0.1.18.js:2:232
```

The documentation states that it should be possible to include standalone bundles via browserify. I suppose I am doing something wrong.

(The reason I am not doing a usual `require('mymodule')` is that, `mymodule` wraps legacy code and aliasifies globally `fs` with `my-fs`. I don't want calling modules to be responsible for using aliasify globally on `mymodule`. Because a calling module should not be responsible for the inner workings of the module it calls.)

**Comment by jmm** [comment]
Hello @xErik.

If I understand you correctly, this is a known issue. See:

http://stackoverflow.com/questions/28078425/browserifying-libraries-that-were-themselves-browserified-relative-paths-error/28176927#28176927

https://github.com/substack/node-browserify/pull/1151

If that's correct you can use the workarounds in those posts for now, and please close this issue.

**Comment by xErik** [comment]
That works, thanks. Sorry, I didn't find that solution on github myself.

Workaround:
```
browserify({
  entries: ['./entry'],
  noParse: ['/abs/path/to/browserified-standalone.js'],
)
```

**Comment by jmm** [comment]
@xErik Great, thanks! That's ok. The discussion in #1151 is about making it a non-issue.
