### ISSUE TITLE
Why there isn't flag --bundle-external-only?

### ISSUE THREAD

**Issue by alekbarszczewski** [substack/node-browserify#1313]
There is a flag `--no-bundle-external` which restricts bundle requires to local files. Why there isn't flag `--bundle-external-only`? It would be very convenient when splitting code into `app.js` and `vendor.js` for example.

For now you have to know the list of external dependencies and call `.exclude(...)` when building `app.js` and `.require(...)` when building `vendor.js`.

**Comment by yaycmyk** [comment]
+1

I ended up writing a jsawk macro to handle this that you're welcome to use:

```shell
`cat package.json | jsawk 'return \"-r \" + Object.keys(this.dependencies).join(\" -r \")' | awk '{$1=\"\"; print $0}'`
```

used like:

```
{
    scripts: {
        "vendor": "browserify `cat package.json | jsawk 'return \"-r \" + Object.keys(this.dependencies).join(\" -r \")' | awk '{$1=\"\"; print $0}'` --colors | uglifyjs -mc > build/js/vendor.js"
    }
}
```

**Comment by substack** [comment]
This sort of feature can be handled in plugins and third-party tools. For example you can also check out [factor-bundle](https://npmjs.org/package/factor-bundle).

**Comment by dgerber** [comment]
Or just
```
browserify `node -p '"-r "+Object.keys(require("./package").dependencies).join(" -r ")'`
```
