### ISSUE TITLE
Ignore tag in source code

### ISSUE THREAD

**Issue by alexstrat** [substack/node-browserify#132]
Hi,

At some points in _amphibious_ modules, there is a fork in submodule require chain between browser-side and node-side code :

``` js
var util;

if(process.title === 'browser') {
  util = require('./util-browser.js');
} else {
  util = require('./util-node.js');
}
```

If no ignore options is specified, when browerify will hit this, it will bundle `util-browser.js` as far as `util-node.js`. However, bundling `util-node.js` and its dependencies is a waste of bandwidth and can even lead to build error when requiring a node core module. 

One way to avoid this is by specifying options during build, but it is often more convenient to embed these ignore options in the code. I [saw](https://github.com/astro/node-xmpp/blob/master/lib/xmpp/bosh.js#L7) indeed some developpers doing this kind of trick to prevent bundling `util-node.js` :

``` js
var util;

if(process.title === 'browser') {
  util = require('./util-browser.js');
} else {
  var path = './util-node.js';
  util = require(path);
}
```

But that remains a trick since a warning is raised by browserify. That's why I propose to ignore modules in bundle according to an ignore tag in comments preceding the require declaration :

``` js
var util;

if(process.title === 'browser') {
  util = require('./util-browser.js');
} else {
  //@browserify-ignore
  util = require('./util-node.js');
}
```

I planed to write an extension for this, but I think that parsing the code once again - after the AST paser did it - for finding few comments is a waste. Are you agree ? Do you think this can be added on the output of  the AST parser ?

_Note :_ maybe I am missing something and there is other options to prevent the bundle of node-specific code.. Could you explain how ?

**Comment by tech4GT** [comment]
Hello, So I just figured out a way to do this
```js
const nodeOnlyModule = eval('require')('module-name')
```
