### ISSUE TITLE
Bump insert-module-globals dependency.

### ISSUE THREAD

**Issue by tracker1** [substack/node-browserify#1320]
Suggest bumping `insert-module-globals` dependency to `~6.6.0` after the following pull request, or equivalent is accepted.

https://github.com/substack/insert-module-globals/pull/51

**Comment by substack** [comment]
That isn't necessary because the semver range for insert-module-globals is `^6.4.1`, which matches `6.6.0`.

https://github.com/substack/node-browserify/blob/f9c256174fe282f7a8ca619d7168161e8e208524/package.json#L46
