### ISSUE TITLE
Incremental build?

### ISSUE THREAD

**Issue by Julio-Guerra** [substack/node-browserify#1322]
Hi,
Browserify build time is very bad (e.g. react hello world takes seconds for me), and while I see solutions like browserify-incremental, I don't understand why it is not integrated to browserify?
Thanks

**Comment by jmm** [comment]
@Julio-Guerra The browserify philosophy seems to be to keep a light, focused core and allow a lot of customization via composition with other modules. Even the browserify "core" is split up into a bunch of separate packages like `module-deps` and `browser-pack`. Maintainability is one reason.

**Comment by mattdesl** [comment]
@Julio-Guerra have you seen [watchify](https://github.com/substack/watchify)?

I also have a higher level tool (on top of watchify) for rapid local development: [budo](https://github.com/mattdesl/budo). Reload time ends up being in the order of < 100 ms.
