### ISSUE TITLE
Colorized output should be enabled by default

### ISSUE THREAD

**Issue by yaycmyk** [substack/node-browserify#1323]
I was writing a transform for eslint and noticed that the colors from the formatter were being suppressed. It seems like colorized output is disabled by default, where the inverse should be true. There's an explicit `--no-colors` flag, so logically without that they should be on, no?

**Comment by substack** [comment]
browserify doesn't have anything to do with colors or colored output. I'm not sure where your issue is coming from.

**Comment by yaycmyk** [comment]
Hmm, something weird is going on then. I wrote a browserify transform that emits colored output for eslint and unless I specifically pass `--colors` to browserify, they are not shown.

**Comment by substack** [comment]
I think the issue must be upstream in eslint, which might read `process.argv` (which is kind of a bad idea). Possibly there is an option in the API to control colors. In your transform you can also accept options as the second argument.

**Comment by yaycmyk** [comment]
I agree that it's upstream, but I don't think it's eslint. For instance, if I use beefy to do live development, the eslint stuff comes in correctly-colored.

Anyway, thank you!

**Comment by yaycmyk** [comment]
For future generations - if console output is being piped and anything in the stalk is using chalk, it auto-disables colorization unless you override via argv flag: https://github.com/chalk/supports-color/blob/master/index.js#L22

Thanks @substack
