### ISSUE TITLE
symlink change in 10.2.5 is breaking our builds

### ISSUE THREAD

**Issue by marcello3d** [substack/node-browserify#1325]
Problem: 

1. We have two modules, `app` and `shared`
2. `shared` is symlinked into `app`
3. Both `app` and `shared` use a module `foo`, which is installed in `app/node_modules/foo` (but not `shared/node_modules`)
4. Now `shared` can't find `foo`

As far as I can tell, node.js doesn't have this problem.

**Comment by chrisirhc** [comment]
Just wondering, what do you mean `shared` can't find `foo`? Is there a specific error you're seeing? Or is `require()` broken and the browser is returned some `undefined` error?

**Comment by marcello3d** [comment]
The exact error was:
```
Running "browserify:app" (browserify) task
>> Error: Cannot find module 'foo' from 'shared'
Warning: Error running grunt-browserify. Use --force to continue.
```

The problem was due to `grunt-browserify` (that we depend on) depending on `browserify@^10.0.0`, so npm install pulled the latest browserify. We solved it by adding a pinned dependency on `browserify@10.2.4`, but it feels like a breaking change, not a patch.

**Comment by substack** [comment]
Here's my reproduction of the situation you've described, as best as I understand it:

``` sh
cd /tmp
mkdir symlink-test
cd symlink-test
mkdir -p app/node_modules/foo shared
ln -s ../../shared app/node_modules/shared
echo 'module.exports = 1234' > app/node_modules/foo/index.js
echo "module.exports = require('foo') * 2" > shared/index.js
echo "module.exports = require('shared') + require('foo')" > app/index.js
echo "console.log(require('./'))" > app/main.js
node app/main.js
```

but in node this gives the error:

```
module.js:339
    throw err;
          ^
Error: Cannot find module 'foo'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/symlink-test/shared/index.js:1:80)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

So I think browserify matches what happens in node here, unless I've missed something.

**Comment by marcello3d** [comment]
Test looks correct, thanks for that. I'm definitely mistaken. 

The actual scenario is more complicated (and hacky), but dependent on browserify's old (apparently incorrect) behavior. I'll look into your suggestions or simply revisiting the entire approach.

**Comment by substack** [comment]
To some, a bug. To others, a feature!

**Comment by cvlmtg** [comment]
Hi, I've hit the same problem. app with a module linked, I am forced to install React twice (under *app/node_modules/react* and *app/node_modules/linked_module/node_modules/react*) otherwise browserify can't complete its work. the problem here is that react (and flux and whatever) is included twice and initialized twice. this can break the app in some nasty ways (e.g. it suddenly has two dispatchers, with some store registered on one and some registered on the other). basically our app cannot work this way...

**Comment by ds82** [comment]
I'm in the exact same situation right now. How did you solved that in the end @marcello3d?

**Comment by marcello3d** [comment]
@ds82 I didn't, I'm still using the old pinned browserify for the project. :-)

**Comment by ds82** [comment]
@marcello3d damn, same here ;)

**Comment by cvlmtg** [comment]
this is how we solved the problem with symlinked modules:

```
app
  node_modules
    foo -> ../../foo
    react

foo
  node_modules
    react -> ../../app/node_modules/react
```

hope this helps
