### ISSUE TITLE
absolute path in output file

### ISSUE THREAD

**Issue by maiermic** [substack/node-browserify#1328]
If I bundle a script, that requires [jquery.transit](https://www.npmjs.com/package/jquery.transit) and [jquery](https://www.npmjs.com/package/jquery) with `browserify({fullPaths: false}).bundle(myFile)` my output file contains an absolute path: `<absolute path to my project>/node_modules/jQuery/dist/jquery.js`. It only contains the absolute path if I require both modules.

**Comment by jmm** [comment]
@maiermic How are those two files being incorporated into the bundle -- are they both `require()`'d from an entry file? What is the `myFile` argument to `bundle()` supposed to be -- the entry file? `bundle()` accepts a callback function.

**Comment by maiermic** [comment]
Yes. You should be able to reproduce this issue with this entry file:
```JavaScript
require('jQuery');
require('jquery.transit');
```

**Comment by jmm** [comment]
@maiermic I'm unable to reproduce that. What OS and node version?

Also, I highly recommend referencing modules by exact name. I.e. in `package.json` you have `jquery`, while you're `require()`ing it as `jQuery`.

BTW, what is that `fs` module? Why are you using that instead of the node core `fs` module?

**Comment by maiermic** [comment]
You are right. `fs` module in `package.json` is nonsense. But that did not cause this issue. It was `require('jQuery')`, which is a relic. I used package [jQuery](https://www.npmjs.com/package/jQuery) before I switched to [jquery](https://www.npmjs.com/package/jquery). If I use `require('jquery')` I don't get an absolute path in my output file. Thank you very much.

**Comment by maiermic** [comment]
I overlooked other modules that cause several absolute path entries in my output file:
```
/node_modules/es6-iterator/node_modules/es6-symbol/index.js
/node_modules/es6-iterator/node_modules/d/index.js
/node_modules/es6-iterator/node_modules/es5-ext/object/assign/index.js
/node_modules/es6-iterator/node_modules/es5-ext/object/assign/is-implemented.js
/node_modules/es6-iterator/node_modules/es5-ext/object/assign/shim.js
/node_modules/es6-iterator/node_modules/es5-ext/object/is-callable.js
/node_modules/es5-ext/object/keys/index.js
/node_modules/es5-ext/object/keys/is-implemented.js
/node_modules/es5-ext/object/keys/shim.js
/node_modules/es5-ext/object/normalize-options.js
/node_modules/es5-ext/object/valid-value.js
/node_modules/es5-ext/string/#/contains/index.js
/node_modules/es5-ext/string/#/contains/is-implemented.js
/node_modules/es5-ext/string/#/contains/shim.js
```

I use `OS X Yosemite, 10.10.3` and `node v0.10.32`. Can anyone reproduce this with

### index.js
```
require('es6-iterator')
require('es6-symbol')
```

### package.json
```
{
  "name": "unimportant",
  "version": "1.0.0",  
  "devDependencies": {
    "browserify": "^10.2.6"
  },
  "dependencies": {
    "es6-iterator": "^1.0.0",
    "es6-symbol": "^2.0.1"
  }
}
```

### build.js
```
const fs = require('fs');
const browserify = require('browserify');

browserify({fullPaths: false}).add('./index.js').bundle(function(err, buf) {
  fs.writeFileSync('./bundle.js', buf);
});
```
run `node build.js`

**Comment by jmm** [comment]
@maiermic Unfortunately I'm still unable to reproduce this (on linux). I have no `node_modules` strings in the bundle. Your directory structure looks something like this? (Where `somedir` is the `basedir` or `cwd` for the bundle.):

```
somedir/
+-- build.js
+-- index.js
+-- node_modules/
¦   +-- browserify/
¦   +-- es6-iterator/
¦   +-- es6-symbol/
¦   +-- jquery/
¦   +-- jquery.transit/
+-- package.json
```

**Comment by maiermic** [comment]
@jmm That's right. I also couldn't reproduce it on Windows 8.1. I will try to reproduce it on another Mac on Wednesday.

**Comment by maiermic** [comment]
In my previous tests I created `index.js`, `package.json` and `bundle.js` in my real project directory. Even so I replaced the content of my real project `package.json`, I did not delete the `node_modules` directory of my project. I tested it the same way on another Mac and got absolute paths, too. But if I create a test project from scratch with files mentioned above, I don't get absolute paths, unless I copy the `node_modules` directory of my real project directory to my test project directory. I will try to break it down into the list of packages that cause the problem.

**Comment by jmm** [comment]
@maiermic You might want to try this on both `node_modules` dirs (that is, within the parent dir of `node_modules`) to begin with to see what's different about the structure:

```sh
$ npm ls --depth=1
$ npm ls --depth=2
$ npm ls --depth=n
```

**Comment by maiermic** [comment]
It seems to me that the problem is caused due to incompatible package versions. In my case, `watchify` uses a different version of `browserify`:
```
├── browserify@6.3.4
└─┬ watchify@2.6.2
  └── browserify@9.0.8
```
Even though I didn't use `watchify` in my test project it existed a version in `node_modules` that caused problems with `browserify`. I updated both versions (`browserify@11.0.0` and `watchify@3.3.0`) and now I don't get any absolute paths in my output file.

Thanks for your help. It was hard to discover, but learning never stops :sweat_smile: :sweat_drops:

**Comment by jmm** [comment]
@maiermic Ok, you're welcome, I'm glad it's sorted out.

> but learning never stops

Indeed. I guess one of the morals of this story is when trying to reproduce something like this, always make sure to blow away `node_modules`.
