### ISSUE TITLE
Forced order for bundled output?

### ISSUE THREAD

**Issue by sondreb** [substack/node-browserify#1331]
Is it possible to force the order of a bundled output? I'm having issues that some libraries are bundled before their dependencies. Since I know the correct order, is there a way to make browserify respect the order in which they are defined in the .js file?

I have a "lib.js" that contains only require statements, e.g.:

```javascript
require('jquery');
require('angular');
require('./jquery.signalR.js');
```

Two issues:

1. the local require file is always appended to the top of the file, even before the require() statements in the bundle.

2. In the example above, Angular is included in the bundle before jQuery, and not after. The order is the same, no matter if I change the position in lib.js.

The bundle is built using this gulp task:

```javascript
gulp.task('build:lib:js', function () {

    var b = browserify('lib.js', {
        debug: false
    });

    return b.bundle()
        .pipe(source('lib.js'))
        .pipe(gulp.dest('scripts'))
        .pipe(vinylBuffer())
        .pipe(uglify({
            outSourceMap: false
        }))
        .pipe(rename({ suffix: '.min' }))
        .pipe(gulp.dest('scripts'));

});
```

I would like to avoid having to specify dependencies within the gulp script, that should be inside the lib.js.

**Comment by substack** [comment]
This isn't a problem. The order in which the dependencies appear in the bundle isn't the same as the order that those dependencies are evaluated. First your entry point is evaluated. Then when you `require()` a module, that module and its dependencies are evaluated, recursively traversing the `require()` calls. You shouldn't worry about the order that the files appear in the bundle output, that is a topologically sorted ordering so that bundle output will be the same every time to make builds deterministic.

**Comment by zoltanka** [comment]
What can I do when I doesn't load in the good order?
Because it doesn't
This is my gulpfile.
```
// gulpfile.js
let gulp = require('gulp'),
    babelify = require('babelify'),
    browserify = require('browserify'),
    buffer = require('vinyl-buffer'),
    source = require('vinyl-source-stream'),
    sourcemaps = require('gulp-sourcemaps'),
    uglify = require('gulp-uglify'),
    liveReload = require('gulp-livereload');

gulp.task('js', () => {
    let bundler = browserify({
        entries: [
            './resources/assets/js/main.js'
        ],
        debug: true
    });

    bundler.transform(babelify);

    bundler.bundle()
        .on('error', function (err) { console.error(err); })
        .pipe(source('./app.js'))
        // .pipe(buffer())
        // .pipe(sourcemaps.init({ loadMaps: true }))
        // .pipe(uglify()) // Use any gulp plugins you want now
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('public/js'));
});

gulp.task('watch', function() {
    liveReload.listen();

    gulp.watch('./resources/assets/js/**/*.js', ['js']);
});
```

And this is the first few lines of my main.js

```
// app.js
import $ from 'jquery/dist/jquery';
import bootstrap from 'bootstrap/dist/js/bootstrap';
```
