### ISSUE TITLE
The extensions option doesn't seem to be working

### ISSUE THREAD

**Issue by adjavaherian** [substack/node-browserify#1334]
This option seems to be totally ignored:

```javascript
  "browserify": {
    "extensions":  [".jsx", "jsx"],
    "transform": ["reactify" ]
  }
```

http://stackoverflow.com/questions/28159631/require-jsx-files-without-specifying-extension/28161749#28161749

**Comment by substack** [comment]
You can only configure the `transform` field from package.json.

**Comment by adjavaherian** [comment]
Got it, thanks.  Extensions work like so when using node api

```javascript
    var b = browserify({
        "debug": true,
        "extensions":  [".jsx", ".scss"]
    })
        .transform(babelify);
```
