### ISSUE TITLE
Question: Can I add create my own window object for browserify functions?

### ISSUE THREAD

**Issue by adjavaherian** [substack/node-browserify#1336]
I'm trying to use browserify to pack up all the modules for my React Application, but I want to be able to use the bundle on the server-side.  I know this is a stretch, but there's a few things I want to do during the browserify process and I'd rather write browserify transforms than webpack ones.  Anyway, when I try to run my bundle through express, I (obviously) get window reference errors.   So I was wondering if it would be a problem to use jsdom for my server-side window?  I tried something like this at the top of my entry file, but to no avail.

```javascript
var jsdom = require('jsdom').jsdom;
global.document = jsdom('<!doctype html><html><script></script><body></body></html>',{
    features: {
        ProcessExternalResources : ['script', 'iframe'],
        FetchExternalResources : ['script','img','css','frame','iframe','link'],
        MutationEvents: true,
        QuerySelector : true
    }
});
global.window = global.document.defaultView;
global.navigator = window.navigator;
```

Any suggestions?  Thanks.

**Comment by jmm** [comment]
@adjavaherian Thanks for your interest in browserify! This question is really outside the scope of the browserify issue tracker -- it's better suited to somewhere like stackoverflow. But fundamentally, yes, I don't see what would stop you from adding properties like `window|document `to `global` when running in node, although I'd expect some of that code to crash when run in the browser.
