### ISSUE TITLE
Streams3 all the things!

### ISSUE THREAD

**Issue by feross** [substack/node-browserify#1341]
There are lots of browserify dependencies (and `brfs` dependencies) that are still using old versions of `readable-stream`. We could make the install faster (and perhaps bundle sizes smaller), if we updated everything to `^2.0.0`.

```
$ npm outdated
readable-stream                1.0.33  1.0.33    2.0.2  brfs > static-module > readable-stream
readable-stream                1.1.13  1.1.13    2.0.2  browserify > labeled-stream-splicer > stream-splicer > readable-wrap > readable-stream
readable-stream                1.1.13  1.1.13    2.0.2  browserify > duplexer2 > readable-stream
readable-stream                1.1.13  1.1.13    2.0.2  browserify > labeled-stream-splicer > stream-splicer > readable-stream
readable-stream                1.1.13  1.1.13    2.0.2  browserify > read-only-stream > readable-stream
readable-stream                1.1.13  1.1.13    2.0.2  brfs > static-module > duplexer2 > readable-stream
readable-stream                1.1.13  1.1.13    2.0.2  browserify > read-only-stream > readable-wrap > readable-stream
```

**Comment by zertosh** [comment]
I started moving stuff over to streams3:

https://github.com/substack/stream-splicer/pull/10
https://github.com/substack/read-only-stream/pull/4
https://github.com/deoxxa/duplexer2/pull/12

I didn't bother updating "readable-wrap" because it's fix is already in streams3. So instead my PRs simply remove it.

Updating to concat-stream@~1.5.0 will bring with it streams3 (https://github.com/maxogden/concat-stream/pull/36). As well as updating to through2@^2.0.0

I'll have to see once these are merged in how the deps resolve to see what's missing. @substack how about merging the read-only-stream and stream-splicer (and updating labeled-stream-splicer) PRs?

**Comment by substack** [comment]
stream-splicer and read-only-stream updated

**Comment by zertosh** [comment]
cool! I've also got https://github.com/substack/module-deps/pull/97 and https://github.com/substack/stream-combiner2/pull/4, but they're both waiting on https://github.com/deoxxa/duplexer2/pull/12

**Comment by feross** [comment]
Would be nice to get all these packages updated in time for browserify 12.0.0. See: https://github.com/substack/node-browserify/issues/1398

**Comment by feross** [comment]
Cool, I think all outstanding PRs are merged so we should be completely streams3 for browserify 12, but we should verify with `npm outdated`.

**Comment by zertosh** [comment]
module-deps doesn't have the updated stream-combiner – when I update it, the tests fail. I can't look into this now, I'm at work :(

**Comment by zertosh** [comment]
module-deps@4.0.1 has all the streams3 updates

**Comment by jscissr** [comment]
It looks like this is now finished and the issue can be closed. :+1:

```
>npm outdated --depth 10
Package                Current  Wanted  Latest  Location
acorn                    1.2.2   1.2.2   2.6.4  browserify > syntax-error
acorn                    1.2.2   1.2.2   2.6.4  browserify > insert-module-globals > lexical-scope > astw
acorn                    1.2.2   1.2.2   2.6.4  browserify > module-deps > detective
array-filter             0.0.1   0.0.1   1.0.0  browserify > shell-quote
builtin-status-codes     1.0.0   1.0.0   2.0.0  browserify > stream-http
date-now                 0.1.4   0.1.4   1.0.1  browserify > console-browserify
glob                    5.0.15  5.0.15   6.0.1  browserify
json-stable-stringify    0.0.1   0.0.1   1.0.0  browserify > deps-sort > shasum
json-stable-stringify    0.0.1   0.0.1   1.0.0  browserify > shasum
os-browserify            0.1.2   0.1.2   0.2.0  browserify
source-map               0.4.2   0.4.2   0.5.3  browserify > browser-pack > combine-source-map
source-map               0.4.2   0.4.2   0.5.3  browserify > insert-module-globals > combine-source-map
source-map               0.4.2   0.4.4   0.5.3  browserify > insert-module-globals > combine-source-map > inline-source-map
source-map               0.4.2   0.4.4   0.5.3  browserify > browser-pack > combine-source-map > inline-source-map
```
