### ISSUE TITLE
Duplicate sub-dependencies are included when bundling

### ISSUE THREAD

**Issue by TimDaub** [substack/node-browserify#1342]
Hi,

we're managing a big web app and wondered why our final app bundle is so big. So to see what is actually required by browserify I did:

```browserify -e js/app.js --list > webapp-dependencies.txt```

I found that there are instances where sub-dependencies are bundled into the application multiple times:

```
/node_modules/react-router-bootstrap/node_modules/classnames/index.js -v ^2.0.0
/node_modules/react-bootstrap/node_modules/classnames/index.js - ^2.0.0
/node_modules/classnames/index.js - v 1.2.2
```

So since both react-router-bootstrap and react-bootstrap could (and maybe do) use the same version of classnames.js, I'm wondering why they're not bundled as one dependency.

I assume this is a bug, right?

**Comment by TimDaub** [comment]
Hello, ... is there anybody out there?

**Comment by jmm** [comment]
Hello @TimDaub 
> So since both react-router-bootstrap and react-bootstrap could (and maybe do) use the same version of classnames.js, I'm wondering why they're not bundled as one dependency.

Please see [saving bytes](https://github.com/substack/browserify-handbook#saving-bytes) in the handbook:

> browserify will not include the same exact file twice, but compatible versions may differ slightly. browserify is also not version-aware, it will include the versions of packages exactly as they are laid out in `node_modules/` according to the `require()` algorithm that node uses.

browserify is not going to figure out if they're supposed to be compatible. I think it is meant to dedupe them if the files are identical. Are any of the files you referenced identical? If not I suggest you `$ npm dedupe` and try bundling again.

**Comment by jmm** [comment]
Closing this because it's not clear that there's a `browserify` issue. If there's a `browserify` bug please open a new issue following the guidelines in [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify). Thanks!
