### ISSUE TITLE
Exposing module within the built file.

### ISSUE THREAD

**Issue by allouis** [substack/node-browserify#1352]
I'm trying to load a browserify built file into an app using requirejs, even using the `--standalone` option requirejs breaks and gives an unhelpful error message. I've noticed that built file returns a require function e.g.
```javascript
var require = (/* browserify bundle here */);
require("12"); // returns the module with index 12 as given by module-deps output
```
I'm currently using a brittle script to work out the index of the module I'd like to expose and feel like the transform should be done in the pipeline rather than after browserify writes to the file system.

Would it be possible to have some kind of expose flag that took certain modules, and used a given string rather than their index as the ID? 
Maybe something like `browserify -e main.js -o bundle.js --expose ./app.js:app`
```javascript
var require = (/* browserify bundle here */);
require("app"); // returns the "./app.js" module (relative to where browserify was run)
```

I'm happy to do the work and PR it but wondering if it's something you'd consider accepting. If not, is the browserify specific code anywhere so I can pipe through module-deps -> browser-pack -> browserify and intercept in the middle?

**Comment by substack** [comment]
I'm not sure about how requirejs might change things, but you can use `-r FILE:TARGET` to expose a name externally instead of referencing by ID:

```
echo "console.log('hello')" > app.js; cat <(browserify -r ./app.js:app) <(echo "require('app')") | node
hello
```

**Comment by allouis** [comment]
Ah I can't believe I missed that, this is perfect, thank you.
