### ISSUE TITLE
.require() with expose: true use backslashes on Windows

### ISSUE THREAD

**Issue by piranna** [substack/node-browserify#1358]
When using [.require()](https://github.com/substack/node-browserify#brequirefile-opts) method on Windows with the `expose:true` flag, the IDs are being generated with backslashes, like `/apps\\Call` instead of `/apps/Call`, so later they can't be found when `require()`ing them because they are not found. I think this is somewhat related to https://github.com/substack/node-browserify/pull/503/files and https://github.com/substack/node-browserify/pull/1096/files and probably the fix would be the same, just replace the backslashes previously to set the path at the browserify output.

**Comment by piranna** [comment]
Probably it would be also a good idea to sanitice this way all the paths to be sure they are only using slashes and not backslashes...

**Comment by piranna** [comment]
Taking a look on the code, I suspect the problem is at [this path.resolve()](https://github.com/substack/node-browserify/blob/f7e626ca75bd925a584f9b0fe8ff9d4b8e90f188/index.js#L165). I don't have a Windows machine here to try it, though :-(

**Comment by julian-maughan** [comment]
This issue is currently preventing me upgrading from a fairly old version of Browserify, so I'd be great to see it resolved. Hope the PR helps.

**Comment by substack** [comment]
Should be fixed in 12.0.2.

**Comment by githubVivek55** [comment]
this issue is still exist in windows for external dependencies section. Could anyone please help me how to resolve that..
