### ISSUE TITLE
Fails if a function named `delete` exists in the file

### ISSUE THREAD

**Issue by ibc** [substack/node-browserify#1364]
test.js:

```javascript
function delete() {
	console.log("delete");
}

module.exports = delete;
```

then:

```bash
$ browserify test.js

/tmp/test.js:1
function delete() {
         ^
ParseError: Unexpected token
```

There are also other ugly issues if browserify finds a function named `delete`, but the above one is the simplest one to show.

**Comment by jmm** [comment]
Hello @ibc. `delete` is a keyword, so this is a JS issue, not a Browserify issue.

**Comment by ibc** [comment]
Ok. It seems that `function delete() {}` is redefining the global `delete` function, so it breaks everything.
Thanks.
