### ISSUE TITLE
How to add a client-only devDependency?

### ISSUE THREAD

**Issue by donaldpipowitch** [substack/node-browserify#1369]
I'd like to drop Bower [for a long time](https://github.com/bower/bower/issues/1520#issuecomment-61799486) and regularly check for good migration paths. Today I stumbled upon @ryanflorence article about [Why We Should Stop Using Bower – And How to Do It](http://gofore.com/ohjelmistokehitys/stop-using-bower/) and we had [little conversation](https://twitter.com/PipoPeperoni/status/636759334664470528) about a feature I need and can't find a solution for: client-only `devDependencies`.

**What**

I'd like to add client-only `devDependencies`. As far as I understand `browserify` the `"browser"` field only let me add client-only `dependencies`, but not `devDependencies`.

**Why**

Say I'd like to develop an Angular app. I use [Karma](http://karma-runner.github.io/0.13/index.html) as my test runner which is configured in `devDependencies` in my `package.json`. I also need [angular-mocks](https://github.com/angular/bower-angular-mocks) for easier testing, which is currently configured in `devDependencies` in my `bower.json`.

This allows me to generate a generic {{karma.conf.js}} which I can (and do!) share in all our company projects - no matter what dependencies an app has. It looks a little bit like this:

````
// this will look for angular-mocks, but not Karma itself!
var dependencies = require('wiredep')({
    devDependencies: true
  }).js || [];

var karmaConfig = {
  // other config fields are placed here...

  // load all dependencies needed for testing, the app itself and all test specs
  files: dependencies.concat([
    'src/**/*.{js,html}',
    'tests/**/*_unit.js'
  ])
};

// expose config to karma
module.exports = function(config) {
  config.set(karmaConfig);
};
````

This just rocks. Every project can add and remove dependencies as needed and they never need to change the `karma.conf.js`. How can I do the same with `browserify`?

**Comment by mattdesl** [comment]
Maybe I don't really understand (I don't use karma or Angular), but browserify already supports the "browser" field with `devDependencies`.

Browserify doesn't know whether something in your node_modules is a dependency or devDependency, it will treat it the same way when bundling.

**Comment by donaldpipowitch** [comment]
Can you give me an example of how to list all devDeps only needed by the client?

**Comment by mattdesl** [comment]
I guess I don't understand what you're trying to do. None of these tools know whether a dependency is for the client or not, only that something is requiring it. For example, in [this module](https://github.com/Jam3/load-bmfont) only `testling` and `browserify` are needed for the browser tests.

**Comment by donaldpipowitch** [comment]
Than I guess browserify can't do what I want.

> I guess I don't understand what you're trying to do.

I want to load my dependencies in a Karma config. Karma only needs modules like angular-mock which I currently have declared in bower.json as a devDependency, but not sonething like Grunt which I could have in my package.json as a devDependency.

**Comment by substack** [comment]
browserify doesn't work this way. dependencies are devDependencies are something that npm takes care of, not browserify. With browserify, you give entry points which run similarly to doing `node foo.js` and every file that `foo.js` loads with `require()` gets bundled, recursively for every file required by foo.js and so on.

It looks like you're expecting to need a manifest file, which isn't necessary using browserify.

You'll probably want to use something like [karma-browserify](https://www.npmjs.com/package/karma-browserify) but I haven't used this tool. Using karma-browserify, you pass in your entry points to browserify like usual and it does the rest to pull in the appropriate dependencies.
