### ISSUE TITLE
tls   not in built ins

### ISSUE THREAD

**Issue by danieldeschamps** [substack/node-browserify#1376]
Why isn't tls and fs   in builtins.js ?

exports.fs = require.resolve('./_empty.js');
exports.tls = require.resolve('./_empty.js');

I need it!!!

**Comment by emilbayes** [comment]
What would you expect the behaviour of those to be in a browser environment? Shimming the behaviour of `fs` can be somewhat accomplished with `brfs` or `level-fs-browser`

**Comment by danieldeschamps** [comment]
Hi,

I need fs to read certificate files stored in the user's local file system.

Additionally, and more importantly, I need the tls object in order to
parse pkcs12 certificate file contents for digital signature.

**Comment by emilbayes** [comment]
You can't just read files from the users system like that. You might be able to use [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader), however this requires the user picking the files, and AFAIK there isn't a browserify `fs` compatible shim around it. You might write one yourself, defining the methods of `fs` in terms of `FileReader` and overriding `fs` in the `browser` field in `package.json`. See the [example here](https://github.com/substack/browserify-handbook#browser-field).

**Comment by danieldeschamps** [comment]
Ok, reading files is fine... I can find many ways on how to do that,
but what about the TLS object? I need it in order to parse the
certificates.

**Comment by feross** [comment]
@danieldeschamps How do you parse certificates with the tls package? The docs show that `tls` is only used to create TLS servers and sockets. `tls.Server` and `tls.TLSSocket` could never work in today's browser.

**Comment by danieldeschamps** [comment]
@feross: I parse certificats using Crypto, but crypto.createCredentials function is deprecated. This function is to be used within tls.createSecureContext.

https://nodejs.org/api/crypto.html#crypto_crypto_createcredentials_details

That why browserify should contain TLS.
