### ISSUE TITLE
Browserify cannot find module with 'require(module_name)'

### ISSUE THREAD

**Issue by franck-serot** [substack/node-browserify#1381]
Hi
I use generator-browserify (https://github.com/vincentmac/generator-browserify ) in order to create a HelloWorld sample.

I find a problem with browserify when I call the function require with the module name passed in a variable or a concat of strings.

For example,
main.js - the initial code generated from generator-browserify 
   'use strict';
   var App = require('./app.js');
   var app = new App();
   app.beep();
=> 
main.js - the following code allows to reproduce the problem.
   'use strict';
   var name = 'app';
   var App = require('./' + name + '.js');
   var app = new App();
   app.beep();

The code creates the following error code :
   Uncaught Error: Cannot find module './app.js'

Could you help me to understand and solve this problem ?

Thank you for your help.

Best regards,

Franck

**Comment by substack** [comment]
This is not something that browserify can support because it would have to execute your code to know what the values of variables are. Instead, you can use transforms and outside configuration to give browserify dynamic files to include.

Here's one transform for using dynamic expressions: https://www.npmjs.com/package/bulkify

**Comment by franck-serot** [comment]
Thank you for your response.
I try to use bulkify but I have the following error : 
Uncaught TypeError: fs.readdirSync is not a function

'use strict';
//var name = 'app';
//var App = require('./' + name + '.js');
var bulk = require('bulk-require');
console.log(__dirname);
var sections = bulk(__dirname, [ '*']);
console.log(sections);
var App = require('./app.js');
var app = new App();
app.beep();

Could you please explain me how to use it with browserify and give an example ?
Best regards,
Franck
