### ISSUE TITLE
Depending on a browserified module causes "module not found" errors

### ISSUE THREAD

**Issue by cjohansen** [substack/node-browserify#1383]
I have a module that I am trying to build with browserify. The module has a dependency, whose main export is a file that is also built with browserify. When I run browserify on the upstream module, it tries to resolve `require` statements *inside the distribution file of a dependency*. Because these point to files relative to the source of the dependency, they can't be found, and the build fails.

Example:

**lib**

```
dist.js
package.json
src/
  index.js
  other-file.js
```

`index.js` contains `require('./other-file')` and `package.json` contains `main: "dist.js"`.

**upstream**

```
package.json
index.js
node_modules
  lib
```

`index.js` contains `require('lib');`. Running browserify on it produces the error "can't find module './other-file' from 'lib'".

Is this by design or a bug? How do I get around it?

**Comment by jmm** [comment]
Hello @cjohansen. Thanks for your report. That is a known issue that is being discussed in #1151 (so I'm closing this, but feel free to discuss there). Current workarounds are also discussed there, and here: http://stackoverflow.com/questions/28078425/browserifying-libraries-that-were-themselves-browserified-relative-paths-error/28176927#28176927.

Is `lib` from npm? The publisher should have `derequire`'d it before publishing if the browserify bundle is intended to run in node, or else `main` should point to `src/index.js`.

**Comment by cjohansen** [comment]
Thanks! `derequire` seems to solve my current issue. Looking forward to browserify handling this automatically.

**Comment by jmm** [comment]
Great!
