### ISSUE TITLE
browserify applies transforms to npm linked modules

### ISSUE THREAD

**Issue by jayphelps** [substack/node-browserify#1386]
If you `npm link` a module into your browserify project, it incorrectly has transforms applied to it. This becomes a major issue particularly if the module you install relies on non-strict mode and you're using babelify, which inserts `"use strict"`, causing it to error.

Here's a repo to reproduce: https://github.com/jayphelps/browserify-bug. The major step to note in the README is that you must git clone the external module and `npm link` it for the bug to show.

Also note that very new versions of babel proactively transform certain strict mode code, like `this.foo` to `undefined.foo`. Don't let this confuse you.

**Comment by jmm** [comment]
Hmm, I wonder if this could be from #1318.

**Comment by jayphelps** [comment]
Cc/ @chrisirhc

**Comment by jmm** [comment]
Maybe related: #1365.

**Comment by chrisirhc** [comment]
Definitely sounds like it's related to #1365. If nobody else gets to this, I'll look into it later today.

**Comment by ivantsepp** [comment]
Ah thanks for linking me to this issue @jmm!

This matches the behavior I'm seeing. The babel transform is being applied to a symlinked node_module when it shouldn't be.

**Comment by chrisirhc** [comment]
I've come up with a quick hackish solution to resolve this (https://github.com/substack/module-deps/pull/99, #1392). It's up for comment and review.

**Comment by polkovnikov-ph** [comment]
Is there any workarounds for this issue except hand-patching `node_modules`? Build of my project fails because of this.

**Comment by jayphelps** [comment]
switch to webpack :trollface: that's what I did.

**Comment by polkovnikov-ph** [comment]
I've though about it for a long time :trollface:

**Comment by jmm** [comment]
Off with your heads!

@polkovnikov-ph I'm still working from the assumption that this is a result of #1318. Could you downgrade to `browserify@<10.2.5` for now if that resolves it? As you wrote in the other issue, Babel's `ignore` option is another possibility, but that could get messy.

**Comment by chrisirhc** [comment]
@jmm, it *is* caused by #1318. I've submitted a fix for this as I mentioned above.

**Comment by jmm** [comment]
@chrisirhc Ok, thanks for confirming and for the PR. I haven't had a real good look at either #1318 or the new PR and I hadn't seen you say whether or not it had resulted from #1318, so I wasn't sure.

**Comment by substack** [comment]
This is fixed in 12.0.1.

**Comment by kintel** [comment]
@substack See #1437 - I believe this should be reopened.

**Comment by TehShrike** [comment]
I encountered this issue when using browserify 12.0.1.
