### ISSUE TITLE
Browserify install error

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [substack/node-browserify#1388]
Hi,

this is the error I wanted to submit about the error I faced during the install

   4242 error System Windows_NT 6.2.9200
   4243 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program 
   Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"

   4244 error cwd c:\Program Files\WebServer\data\localweb\pseudodoodle
   4245 error node -v v0.10.26
   4246 error npm -v 1.4.3
   4247 error path c:\Program Files\WebServer\data\localweb\pseudodoodle\node_modules\cucumber\node_modules\browserify\index.js
   4248 error fstream_path c:\Program Files\WebServer\data\localweb\pseudodoodle\node_modules\cucumber\node_modules\browserify\index.js
   4249 error fstream_type File
   4250 error fstream_class FileWriter
   4251 error code ENOENT
   4252 error errno 34
   4253 error fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
   4253 error fstream_stack Object.oncomplete (fs.js:107:15)

Thank you for your help!

**Comment by shinnn** [comment]
@RokaFogtaCsukaFarka Regardless of this issue, you are using an ancient version of Node and npm. i strongly recommend to upgrade to Node v4.x and npm v3.x.

**Comment by feross** [comment]
npm probably doesn't have permission to write to the `c:\Program Files\WebServer\` folder. Also, like @shinnn said, you should update your version of node and npm.

Please comment if these weren't causing your issue and we can re-open this.
