### ISSUE TITLE
Release proposal: browserify 12.0.0

### ISSUE THREAD

**Issue by feross** [substack/node-browserify#1398]
Proposing a new major browserify release (12.0.0) with the following changes:

- MAJOR: bump stream-http to 2.0.0 (https://github.com/substack/node-browserify/pull/1384)
- travis: test on node 4.x not 4.0.0 (https://github.com/substack/node-browserify/pull/1396)
- doc: fix link to querystring (https://github.com/substack/node-browserify/pull/1393)
- buffer: enforce at least 3.4.3 to prevent old bug (https://github.com/substack/node-browserify/pull/1362)

Leaving this open for at least 5 days to solicit feedback. Are there any other important changes to include?

**Comment by zertosh** [comment]
:+1:

**Comment by terinjokes** [comment]
(y)

**Comment by askmatey** [comment]
:+1:

**Comment by substack** [comment]
We should add this module-deps ^4.0 in this upgrade https://github.com/substack/node-browserify/pull/1392 to fix a long-standing symlink transform issue.

**Comment by substack** [comment]
More cleanup for v12: https://github.com/substack/node-browserify/pull/1405

**Comment by zertosh** [comment]
Ok... I think we're all ready in https://github.com/substack/node-browserify/pull/1413.

**Comment by substack** [comment]
Published as 12.0.0. Thanks everyone!
