### ISSUE TITLE
Compiling Order

### ISSUE THREAD

**Issue by LongJeongS** [substack/node-browserify#1410]
This is my first time using browserify and I'm getting a little confused on the order of the files that are compiled. My understanding is that the files will be put into the the merged file in the order that we require the modules. I'm trying to `require(jquery)` and it looks like jquery code is being put into the merged file after all my other js code, so I'm getting `Uncaught ReferenceError: $ is not defined` in my js code. Im using browserify with gulp, rendr, and backbone. 

my gulp file for browserify:
```
var getBundler = function (globs) {

    var bundler, files;

    bundler = browserify({
        fullPaths : false,
        entries   : []
    });

    bundler.require('rendr-handlebars', { expose: 'rendr-handlebars'});
    bundler.require('handlebars', { expose: 'handlebars'});
    bundler.require('jquery', { expose : 'jquery' });

    globs.forEach(function (pattern) {
        files = glob.sync(pattern, { cwd : './' });
        files.forEach(function (file) {
            // it's nesessary for some app modules (e.g. 'app/app')
            // to be exposed otherwise rendr couldn't require them
            moduleName = file.replace(/.js$/, '')
            bundler.require('./' + file, { expose: moduleName});
        });
    });

    rendrModules.forEach(function (moduleName) {
        bundler.require(moduleName);
    });

    return bundler;
};

gulp.task('browserify:app', [ 'handlebars:compile' ], function () {

    var bundler = getBundler([ 'app/**/*.js' ]),
        options = { insertGlobals : false, debug : true };

    return bundler.bundle(options)
        .on('error', handleError)
        .pipe(plumber())
        .pipe(source('mergedAssets.js'))
        .pipe(gulp.dest('./public'));
});
```

I have also tried putting `require(jquery)` in the entry-level file.

**Comment by terinjokes** [comment]
The order the modules are bundled does not matter, since each module is wrapped to execute only after you require it.

You need to find what is using jQuery without requiring it, and ensure you add the `var $ = require('jquery');` line.

**Comment by LongJeongS** [comment]
ahh ok thanks, ill take a look again
