### ISSUE TITLE
Multi-level source maps

### ISSUE THREAD

**Issue by DudeNamedBen** [substack/node-browserify#1412]
Is there a way to have multi-level source maps with browserify?
I compile my project from ES 2015 to ES5 this produces a sourcemap.
It would be pretty neat if browserify could ingest that sourcemap to have correct mapping from ES 2015 -> ES5 -> Browserify -> Source

For example UlgifyJS2 supports this with a "--in-source-map" option.
https://github.com/mishoo/UglifyJS2

**Comment by zertosh** [comment]
Browserify already consumes inline source maps, so you get what you're looking for. If you're using babelify, just make sure you pass `sourceMap: true` to it:

```js
browserify({
  entries: [/*...*/],
  transform: [['babelify', {sourceMap: true}]]
})
```

**Comment by DudeNamedBen** [comment]
Thank you! I didn't know about inline source maps.
Works perfectly.

**Comment by zertosh** [comment]
:+1:
