### ISSUE TITLE
recommendation about switching to npm3

### ISSUE THREAD

**Issue by david-gang** [substack/node-browserify#1420]
Hi,

What is your view about switching to npm3 from the browserify point of view.
Would you recommend it, not recommend it or is your option neutral.
Would it somehow help browserify to make the job better, faster, less ram?

Thanks,
David

**Comment by substack** [comment]
npm 3 will create flatter dependency graphs by default, which makes it less likely that you'll get almost-duplicate packages in you bundle. It's a good idea to upgrade.
