### ISSUE TITLE
.jsx extensions not working after upgrade

### ISSUE THREAD

**Issue by MatthewHerbst** [substack/node-browserify#1427]
I recently upgraded Browserify from v10.2.4 to v12.0.1 and Babelify from v6.1.2 to v7.2.0

After the upgrade, when I run my build process I keep getting errors along the lines of:

```
[14:33:08] Error: Cannot find module './About' from '/Users/mherbst/Repos/data-validation-tool/src/client/components'
    at /Users/mherbst/Repos/data-validation-tool/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/mherbst/Repos/data-validation-tool/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/mherbst/Repos/data-validation-tool/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/mherbst/Repos/data-validation-tool/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

My file structure looks like:

**Example src/client/components/About.jsx**
```javascript
module.exports = React.createClass({...});
```
**Example src/client/components/index.js**
```javascript
module.exports = {
  About: require('./About')
};
```
**Example src/client/main.js**
```javascript
import {About, ...} from 'components';
...
...
...
```

This setup worked with the old version of Browserify. It breaks after the upgrade. Here is part of my build (Gulp pipeline):
**Part of src/gulpfile.js**
```javascript
var bundler = browserify({
  entries: ['client/main.js'],
  options: {
    debug: true,
    extensions: ['.jsx']
  },
  cache: {},
  packageCache: {}
});

bundler.transform(babelify, { presets: ["es2015", "react"] });
```

When I change **Example src/client/components/index.js** to
```javascript
module.exports = {
  About: require('./About.jsx')
};
```
it works, which is what makes me think it's a bug maybe. Is it, or did I miss something?

**Comment by jmm** [comment]
You overwrote `extensions` with `[".jsx"]`. You need `.js` in there too.

**Comment by MatthewHerbst** [comment]
@jmm the documentation states fairly clearly that anything in `extensions` will be additionally considered (emphasis mine):

> opts.extensions is an array of optional **extra extensions** for the module lookup machinery to use when the extension has not been specified. By default browserify considers only .js and .json files in such cases.

**Comment by jmm** [comment]
@MatthewHerbst yeah, sorry, my mistake. I'll have to take another look later.

**Comment by jmm** [comment]
@MatthewHerbst I was trying to answer this too quickly the first time and got confused (it's babelify where setting `extensions` overwrites them).

You're just passing the options incorrectly:

```js
var bundler = browserify({
  entries: ['client/main.js'],
  options: {
    debug: true,
    extensions: ['.jsx']
  },
  cache: {},
  packageCache: {}
});
```

You have `extensions` nested in an `options` property.


```js
var bundler = browserify({
  entries: ['client/main.js'],
  debug: true,
  extensions: ['.jsx'],
  cache: {},
  packageCache: {}
});
```

**Comment by MatthewHerbst** [comment]
@jmm it's the little things! That did indeed solve it, thanks!

I think what happened was that in the old version, I was making the call like:

```javascript
var bundler = browserify(path, { debug: true, extensions: ['.jsx'], cache: {}, packageCache: {} });
```

but after upgrading I saw the `watchify` docs that uses the new method and for whatever reason thought opts needs to be nested. Thanks again!

**Comment by jmm** [comment]
@MatthewHerbst Ok, great!
