### ISSUE TITLE
Crash when try replace local file with NPM module

### ISSUE THREAD

**Issue by IvanGoncharov** [substack/node-browserify#1435]
I'm trying to replace local file with NPM module using `browser` field in `package.json` and browserify simply crash.
I create simplified example as [repo](https://github.com/IvanGoncharov/browserify-bug).
If you run `$ browserify  index.js` it will crash with following error:
```
Error: ENOENT: no such file or directory, lstat '/home/ivang/dev/test_browserify/browserify-bug/esprima'
    at Error (native)
```
But if you do `cp node_modules/jsonpath/package.json.working node_modules/jsonpath/package.json` browserify work as expected.

**Comment by substack** [comment]
We've had this bug for a while and it would be good to fix it in the next release.

**Comment by substack** [comment]
This should now be fixed on a clean install of browserify that will pick up browser-resolve 1.11.0.
