### ISSUE TITLE
Setting stuff onto "this"

### ISSUE THREAD

**Issue by justinmchase** [substack/node-browserify#1438]
I have a 3rd party script that I'm browserifying and it appears to be assuming "this" is window. Something like this:

```
var Arrive = (function (window) {
   if (!window.MutationObserver) return;
   // other stuff...
})(this);

return Arrive;
```

The problem seems to be that when rolled up with browserify, "this" isn't window when its run. Is there an easy way for me to fix this?

**Comment by jeromecovington** [comment]
+1

**Comment by substack** [comment]
Put `(function () {` ... `})()` around the script. This isn't something that browserify should or can handle, since browserify copies the node semantics that `this === module.exports`.

**Comment by jeromecovington** [comment]
@substack - understood, and thanks for the clarification. Odd though, that this is working with browserify @10.2.1, vs. taking the update @12.0.1 after which these third parties cease to function...
