### ISSUE TITLE
browserify applies transforms to npm linked modules

### ISSUE THREAD

**Issue by kintel** [substack/node-browserify#1446]
Same bug as #1386, triggering for non-minimal use-cases:

If you npm link a module into your browserify project, it incorrectly has transforms applied to it, but only if a required module in the linked package requires another local module.

Opening new issue so it doesn't get lost as reopening closed issues require admin attention.
See #1437 for a failing testcase.

**Comment by TehShrike** [comment]
I encountered this issue when using browserify 12.0.1.

**Comment by sunjay** [comment]
I am also having this issue

**Comment by MellowMelon** [comment]
The PR referenced above is a possible solution. No changes to the browserify repo were needed to make the fix work.

**Comment by substack** [comment]
Fixed upstream with module-deps 4.0.5.

**Comment by TehShrike** [comment]
<3
