### ISSUE TITLE
--node working well, but {node: true} not working

### ISSUE THREAD

**Issue by winguse** [substack/node-browserify#1452]
I try to bundle up my express server into a single file, it works well when I try to use command

```
browserify server.js --node > _build/server.js
```

But when I try to use gulp, it does work with option {node: true}

```
gulp.task('build-server', () => {
	return browserify({
			entries: "server.js",
			node: true,
		})
		.pipe(gulp.dest("_build/"));
});
```

**Comment by terinjokes** [comment]
There is no `opts.node`. As noted in the README and in `browserify --help advanced` it's an alias for `opts.bare = true` and `opts.browserField = true`.

Your code should look like the following:

```javascript
browserify({
  entries: "server.js",
  bare: true,
  browserField: true
})
```
