### ISSUE TITLE
How can I pass json datas to my main file ?

### ISSUE THREAD

**Issue by JulienBonnin-ABTasty** [substack/node-browserify#1453]
Hello,

I have to compile a unique main.js file to a "./build/raw/" folder. The output is going to be a file name [account_id].js (And I have to generate multiple files with multiples ids).

Before launching Browserify with gulp, I get a json from my server, which is stored in a global variable in my gulpfile.js.

Is there a way for me to provide this json/variable to the javascript ? The issue is that the code in the main.js targetted by browserify NEED this json to be able to work :)

Thanks for helping, I searched for a loooong time before asking.

**Comment by terinjokes** [comment]
Have you taken a look at [`b.require`](https://github.com/substack/node-browserify#brequirefile-opts). It allows you to pass in a stream as a file (and you can provide a name), and then main.js can require the file you pass in for the account-specific information.

**Comment by JulienBonnin-ABTasty** [comment]
Hi,

Thanks, I found a solution by using concat with browserify to prefix my file with a global var declaration containing my json :)

I'll try to switch to your solution now. Thanks again.
