### ISSUE TITLE
Where does 'require' option come from? Why is it not covered in docs?

### ISSUE THREAD

**Issue by wzup** [substack/node-browserify#1478]
It is not an issue for me now, but a question, though actually it's muddying the line between the two.

There is no option `require` here in `opts` https://github.com/substack/node-browserify#browserifyfiles--opts. However I found examples where this option is used and even it is the only way to make Browserify do something.

```
    var vendors = [
        'jquery',
        'react/addons',
        'react-dom',
        'moment'
    ];

    // Pls, pay attention, [files] are not passed here. Compare: "browserify ([files], opts)"
    var b = browserify ({
        debug: true,
        noParse: vendors,
        transform: ['babelify'],
        // But pls pay attention to this require. What is this? 
        // Where does this `require` option come from? 
        require: vendors
    });

    b.bundle()
        .on('error', function(err) {
            console.log(err.message);
        })
        .pipe(source('vendors.js'))
        .pipe(gulp.dest('./js'));
```
Why there is no explanation in docs? What does this option do and where does it come from? From what external package?

**Comment by MellowMelon** [comment]
Your code snippet is equivalent to
```js
    var vendors = [
        'jquery',
        'react/addons',
        'react-dom',
        'moment'
    ];

    var b = browserify ({
        debug: true,
        noParse: vendors,
        transform: ['babelify'],
    });

    b.require(vendors)
        .bundle()
        .on('error', function(err) {
            console.log(err.message);
        })
        .pipe(source('vendors.js'))
        .pipe(gulp.dest('./js'));
```
`b.require` is the [API method](https://github.com/substack/node-browserify#brequirefile-opts) for obtaining [external requires](https://github.com/substack/node-browserify#external-requires).

You are correct that this is missing in the documentation.
