### ISSUE TITLE
Don't mess with Buffer.prototype (v13)

### ISSUE THREAD

**Issue by binarykitchen** [substack/node-browserify#1482]
https://github.com/feross/typedarray-to-buffer/issues/3 explains all.

With your latest version somehow this code gets modified from

```
function (arr) {
      arr.__proto__ = Buffer.prototype
      return arr
}
```

to

```
Buffer._augment
```

How come? It is breaking in my videomail app ...

**Comment by terinjokes** [comment]
Can you provide a reproducible demo on GitHub?

**Comment by binarykitchen** [comment]
Don't have a minified demo right now. And I am on the road. But here, try this:
1. git pull https://github.com/binarykitchen/videomail-client
2. in package.json, bump browserify from v12 to v13
3. run `npm install`
4. run `gulp examples`
5. open https://local.videomail-client.io:8080/
6. try the simple example, record something and see, in the console, that error is thrown

error is thrown 100% every time!

**Comment by binarykitchen** [comment]
any luck reproducing the above @terinjokes?

**Comment by terinjokes** [comment]
@binarykitchen No. In fact I didn't get notifications for either message, so I apologize for the lack of a response.

**Comment by terinjokes** [comment]
@binarykitchen your modules "audio-sample" and "canvas-to-buffer" don't have ranges on "typedarray-to-buffer" resulting in 3.0.4 being installed.

**Comment by binarykitchen** [comment]
oh f***, why is npm installing them flat and not hierarchical?

**Comment by terinjokes** [comment]
It is installing them hierarchical, thus your problem. :)
