### ISSUE TITLE
Syntax error always shows the same line: `throw er; // Unhandled 'error' event`

### ISSUE THREAD

**Issue by jamie-pate** [substack/node-browserify#1490]
Any syntax error seems to show the same error line which is not the source code that has contains error when using gulp + browserify.

I've seen many error reports that have the exact same thing and people are always perplexed as to what is actually wrong.

some variant of:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token
```

I've traced it to `Browserify.prototype._syntax` so far.

**Comment by jamie-pate** [comment]
This seems to at least output the correct file, but i'm not sure what stream is sanitizing err and removing the actual relevant info.
```
-        if (err) return this.emit('error', err);
+        if (err) return this.emit('error', new Error(err));
```

**Comment by terinjokes** [comment]
@jamie-pate Attach an error handler to the stream created by calling `bundle`, and you can query the SyntaxError's properties for what file contains the syntax error.

The error you originally report is node's default unhandled error output.

**Comment by jamie-pate** [comment]
Is there a way to make the portion that gets output `SyntaxError: Unexpected token` more robust so the default unhandled error handler is not so mysterious?
