### ISSUE TITLE
Error when running crypto.randomBytes() in IE 10 on Windows 8

### ISSUE THREAD

**Issue by jviotti** [substack/node-browserify#1493]
I get the following exception:

```
secure random number generation not supported by this browser. use chrome, FireFox or Internet Explorer 11
```

Is there a documented alternative?

**Comment by jviotti** [comment]
I've tracked this to https://github.com/crypto-browserify/randombytes:

```js
function oldBrowser () {
  throw new Error('secure random number generation not supported by this browser\nuse chrome, FireFox or Internet Explorer 11')
}
```

Is there any recommended crypto library alternative?

**Comment by terinjokes** [comment]
`crypto-browserify` uses `randombytes` which checks for `crypto.getRandomValues`. If you really need to use `crypto` in the browser, you're going to have to shim that yourself. I'm not sure how, but up to you.

**Comment by jviotti** [comment]
@terinjokes Fair enough, thanks for the information. I'll close this issue!
