### ISSUE TITLE
webkitMovementX and webkitMovementY listed as depricated

### ISSUE THREAD

**Issue by jayalter** [substack/node-browserify#1495]
When compiling into my Bundle.js file, Chrome for 
Windows Version 48.0.2564.97 reports the following warnings:

'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.

'webkitMovementX' is deprecated. Please use 'movementY' instead.
'webkitMovementY' is deprecated. Please use 'movementY' instead.

I am assuming this is coming from Browserify and simply wanted to let the devs know.

**Comment by substack** [comment]
This warning is triggered by a package you're loading. Browserify doesn't touch the DOM itself.
