### ISSUE TITLE
why not supporting simply require('lib/foo.js')  instead of require('./lib/foo.js')

### ISSUE THREAD

**Issue by cauburtin** [substack/node-browserify#1497]
I find the former simpler and quicker but it doesn't work, while the latter does

**Comment by ssube** [comment]
Are you requiring a file using a relative path or part of a separate module?

The `require('lib/foo.js')` syntax will try to find the `foo.js` file in the `lib` Node module (`node_modules/lib/foo.js`), according to the [Node module spec](https://nodejs.org/api/modules.html#modules_all_together).

The `require('./lib/foo.js')` syntax will resolve the current directory, append `lib` and `foo.js`, and attempt to load that file (see the same spec page).

**Comment by cauburtin** [comment]
thanks ok
