### ISSUE TITLE
Arrow functions not parsed correctly in some cases

### ISSUE THREAD

**Issue by ags131** [substack/node-browserify#1499]
I have been using ES6 extensively lately and have encountered a bug in browserify which prevents my scripts from being bundled properly. 
I generally have a line of code in my functions that defines callbacks as a noop if not supplied (For fire and forget usage)
With arrow functions, I've found this to cause unexpected token errors.
example file below demonstrats the problem.
```javascript
class Test {
	test1(cb){
		// Works
		var noop = ()=>{}
		cb = cb || noop
	}
	test2(cb){
		// Works
		cb = cb || (()=>{})
	}
	test3(cb){
		// ParseError: Unexpected token
		cb = cb || ()=>{}
	}
}
```

**Comment by jmm** [comment]
Hello @ags131. That is correct -- `test3()` is invalid. `ArrowFunction` is an `AssignmentExpression`

**Comment by ags131** [comment]
How is it invalid when node itself parses and runs it fine?

**Comment by jmm** [comment]
Version `x` of Node is just version `y` of V8, *a* parser, which can have bugs. Sounds like that's the case here. In any case, [Acorn](https://github.com/ternjs/acorn) is doing the parsing in Browserify, so if there were a bug on the Browserify end it'd be there and that'd be the place to report it. But note that I think it's invalid.

**Comment by jmm** [comment]
Closing for the reasons stated. This correctly fails to parse in more recent V8 (though the error messages are odd).
