### ISSUE TITLE
Pipe a readable stream into browserify

### ISSUE THREAD

**Issue by wesleytodd** [substack/node-browserify#1514]
Is there a way to pipe an already existing stream into a browserify instance?  Here is an example of my use case:

```javascript
fs.createReadStream('./my-entry-script.js')
  .pipe(through2(function () {
    // Some transform that pulls some meta data about the file and possibly
    // preforms modifications on the content 
  }))
  .pipe(browserify())
  .pipe(someOutputStream);
```

I looked into the [pipeline stuff here](https://github.com/substack/node-browserify/blob/master/index.js#L128-L156) but did not see an easy way to hook into this.  I would be willing to open up a PR to take a stab at this if there is not already something to handle this situation, just wanted to start a discussion before working on it :)

Also, FWIW, I know there are ways to solve the exact use case above, but this is for integrating browserify into a larger ecosystem of stream based transforms for content management type app I am working on.  So I know there are probably ways to solve the exact problem above with a concat stream and buffer, but I would really like to be able to do the duplex stream like above.

**Comment by wesleytodd** [comment]
I did manage to get a working solution, but I think there are some issues, and it is certainly hacked on top of browserify, so any help would be appreciated.  Here is my implementation for reference: https://github.com/wesleytodd/rufio-filter-browserify/blob/master/index.js

**Comment by zoubin** [comment]
```js
browserify({ entries : [fs.createReadStream('./my-entry-script.js')] })
  .bundle()
  .pipe(someOutputStream)

```

**Comment by wesleytodd** [comment]
@zoubin That is what I was saying in my last paragraph, I understand that I can pass the stream as an entry/file, but I would like to be able to easily `pipe` to the browserify stream like my code shows.  I am making a transform stream that can be optionally composed together in a larger system.  So I would really like a simple api to pipe the entry file contents to a browserify instance.

The link I posted showed how I was able to wrap browserify in a `through2` stream transform, but it seems like a nice addition would be some method for the code example I posted above.

**Comment by zoubin** [comment]
@wesleytodd Oh, I see.
I have been using [reduce-js](https://github.com/reducejs/reduce-js) with browserify and gulp.
It does similar things but only work with streams like `gulp.src`.
You can use [vinyl-source-stream](https://github.com/hughsk/vinyl-source-stream) to adapt:

```js
var source = require('vinyl-source-stream')
var browserify = require('browserify')
var reduce = require('reduce-js')

var file = 'my-entry-script.js'
fs.createReadStream(file)
  .pipe(source(file))
  .pipe(reduce.bundle(browserify(), 'bundle.js'))
  // followed by streams like those processed by gulp plugins
  .pipe(someOutputStream);

```

**Comment by wesleytodd** [comment]
Thanks @zoubin I will take a look at those modules to see if I can find the best way.

I am still wondering if there is a way to do it with just browserify.  Or if there would be interest in adding a method if it doesn't exist now.

**Comment by substack** [comment]
This can be achieved with existing browserify functionality, so I would rather not add another method.

**Comment by wesleytodd** [comment]
@substack I am glad to hear that it is possible.  Is my linked solution what you mean?  Or is there a less hacky way?

If you can tell me the recommended solution I will try to find a place for it in the docs so anyone else with this question can easily find the answer.  Thanks!!
