### ISSUE TITLE
browser field and browserify transform field in package.json to .browserifyrc

### ISSUE THREAD

**Issue by petamoriken** [substack/node-browserify#1515]
Browserify fields in `package.json` is useful.
If they can be written in `.browserifyrc` like `.eslintrc`, `.babelrc`, it's more useful.

**Comment by substack** [comment]
I think it's better to put these in `package.json` because package.json is already read for every module as part of the module resolution algorithm. Adding another file to check for every file in the dependency graph would slow things down a lot.
