### ISSUE TITLE
absolute path from the build invocation, require('/config/stuff.json')

### ISSUE THREAD

**Issue by cauburtin** [substack/node-browserify#1518]
I've read about relative path hell https://github.com/substack/node-browserify/issues/635, and would like to make browserify work with a few absolute paths to replace the `require('../../../../config/stuff.json')` in `require('/config/stuff.json')`

Why couldn't browserify keep a reference to the path where it is initiated and use it for the '/some/path' ?

**Comment by jmm** [comment]
@cauburtin That's explained in the issue you linked to :) https://github.com/substack/node-browserify/issues/635#issuecomment-34383767. For what you want see http://stackoverflow.com/a/27609116. You might alternatively be able to use `NODE_PATH` (on which case you might need to drop the leading `/`).

**Comment by cauburtin** [comment]
yes, thanks I remember seeing that question too, and your answer there.

But that config folder is just containing 2 files, it's at the root of an inner app inside the global project (with all the node_modules), I wouldn't feel good to index config with node_modules, it's something that goes with that app, not an external dependency at all

**Comment by jmm** [comment]
@cauburtin I think it's cumbersome that local stuff and dependencies installed via the package manager aren't more distinct, but that's how the node module system works (where a leading `/` means it's an absolute path). Node is agnostic to how something got in `node_modules`. Anyway, if you want that and you only need it for Browserify bundling and not node, you can do it with `pathmodify`, which is a wrapper around a custom `module-deps` resolver function (setting that directly isn't properly exposed via Browserify right now.)
