### ISSUE TITLE
./a.js vs ../a.js

### ISSUE THREAD

**Issue by polkovnikov-ph** [substack/node-browserify#1533]
Why does Browserify create two module instances (i.e. they have non-equal `exports` objects) for each of the relative paths to a module?

**Comment by mderijcke** [comment]
If you can make a gist of your bundle I am willing to take a look for you if you want.

**Comment by northerncodemky** [comment]
Is there any difference in casing in your example? e.g. `../foo/A.js` vs `./foo/a.js`? I've encountered an issue with this (which lead to bugs in `foo instanceof A` type code as `foo` was created with an `A` considered not equal to the `A` on the right-hand side (despite being imported from the same module), so the test failed. I wrote [browserify-fixcase-transform](https://github.com/northerncodemky/browserify-fixcase-transform) to fix-up instances of this.

**Comment by polkovnikov-ph** [comment]
@northerncodemky Casing could be an issue there, as I'm developing in the Windows environment, and could've made such mistake (though it's quite unlikely). I couldn't find my saved repro case, so I think this issue should be closed.
