### ISSUE TITLE
Browserify require a node_module returns "not found"

### ISSUE THREAD

**Issue by Khorkhe** [substack/node-browserify#1541]
I have installed a node module "jquery.fancytree" using npm:
`npm install --save jquery.fancytree`

The correct version and files were listed inside node_modules and package.json.
I added in my js a require to this module:
`var fancytree = require('jquery.fancytree');`

but get the following error, which seems to look for local assets and not npm modules (maybe because it did not find in node_modules): 

`events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'jquery.fancytree' from '/Users/georges/Desktop/KMS/kms/app/assets/javascripts'
    at /Users/georges/Desktop/KMS/kms/node_modules/resolve/lib/async.js:46:17
    at process (/Users/georges/Desktop/KMS/kms/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/georges/Desktop/KMS/kms/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/georges/Desktop/KMS/kms/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/georges/Desktop/KMS/kms/node_modules/resolve/lib/async.js:92:31)
    at /Users/georges/Desktop/KMS/kms/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)`

Tried duplicating the folder without a dot '.' in the name thinking that was the problem, but no.

Any ideas what is going on?
Thanks!

**Comment by mderijcke** [comment]
Are you using Browserify from the command line or a task runner / code?

It seems like it's either not traversing upwards your directory structure correctly or npm install picked a weird location.

Maybe first make sure `/Users/georges/Desktop/KMS/kms/node_modules/jquery.fancytree` exists? (npm can be weird sometimes)

**Comment by Khorkhe** [comment]
Hi @mderijcke 
I am using Browserify's require inside my javascript, then use gulp to generate the final JS files.  I checked that the folder "jquery.fancytree" exists inside the directory. 

For testing purposes, i copied:
`/Users/georges/Desktop/KMS/kms/node_modules/jquery.fancytree`
here:
`/Users/georges/Desktop/KMS/kms/node_modules/fancytree`

...to see if i could find it under different folder name.  It did not work.

**Comment by mderijcke** [comment]
I managed to reproduce this problem. And the problem is rather silly.

jquery.fancytree does not define a `main` variable in their `package.json`. Instead you have to use `require('jquery.fancytree/dist/jquery.fancytree')` or `require('jquery.fancytree/dist/jquery.fancytree-all')` in your code.

Optionally you could decide to open an issue over at https://github.com/mar10/fancytree but that's really up to you.

**Comment by Khorkhe** [comment]
Ha, thanks for that!
