### ISSUE TITLE
Accept dependencies file for external and require options

### ISSUE THREAD

**Issue by donkeysharp** [substack/node-browserify#1546]
For projects I create both a `vendor.js` and `app.js` files that contain third-party libraries and application's code respectively. I prefer using npm scripts for build process. I have the next scripts in my `package.json` that do this job:

```
...
"scripts": {
  "build:app": "browserify  index.js -x dependency1 -x dependency2 ... -x dependencyN -t [ babelify --presets [es2015 react] ] | uglifyjs -mc -o dist/app.min.js",
  "build:vendor": "browserify -r dependency1 -r dependency2 ... -x dependencyN -o dist/vendor.js"
},
...
```

It works, but as dependencies increase or decrease, it's kind of annoying to maintain `build:app` and `build:vendor` scripts.
A non-cli solution I'm working on (but I'm not sure of it) is to create `build_vendor.js` and `build_app.js` so I use browserify's API. It works but when I need to use something like uglify I have to use it's API too losing all command line I would've liked to have.
I was wondering if there is a way to pass, let's say a `dependencies.json` file to --external and --require options so `dependencies.json` looks something like:

```
[
   "dependency1",
   "dependency2",
   ...
   "dependencyN"
]
```

And scripts will be something like:

```
...
"scripts": {
  "build:app": "browserify index.js --external dependencies.json -o dist/app.js",
  "build:vendor": "browserify --require dependencies.json -o dist/vendor.js"
},
...
```

Would it be worth for a PR? If it would, where should I start or what browserify dependency should I fork to code this PR?

Thanks in advance

**Comment by mderijcke** [comment]
You shouldn't need a PR. You can just write a script that uses the browserify api and instead of writing to a file you pipe browserify to process.stdout.

This way you can still pipe the output of your script to uglify or derequire. Essentially you're writing your own version of the browserify executable, which you could look at for inspiration.

**Comment by hugoduraes** [comment]
@donkeysharp have you come up with a solution for this? I'm also bundling external dependencies to a `vendor.js` file and I couldn't find a way to do it without having to maintain a list of external dependencies. I would like to have a way that could help me listing all the external dependencies.

**Comment by donkeysharp** [comment]
Sorry I forgot to close this issue.
@mderijcke you are right a bit more of reading about browserify api was the trick. @hugoduraes I created a file where I do the same as command line using browserify API, I'm still maintaining a list of external dependencies but they are inside this file, and my call to this site is cleaner.
