### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mrdulin** [substack/node-browserify#1556]
I want to build the `bundle` files to `dist` directory
![image](https://cloud.githubusercontent.com/assets/17866683/15138681/0c18cbd4-16c4-11e6-8e2c-d1f90d7c2608.png)

but when i run `npm run build`, the console give me these:

![image](https://cloud.githubusercontent.com/assets/17866683/15138697/2c7b3ace-16c4-11e6-8060-c16665c3526e.png)

Did I do something wrong?

**Comment by terinjokes** [comment]
Browserify doesn't automatically create the output directory, you'll have to do so yourself before you run the build.

The `mkdirp` module is a fast way to do this across operating systems. Once included in your dependencies and installed, you can do something like `"build": "mkdirp dist && browserify …"` in your package.json

**Comment by mrdulin** [comment]
@terinjokes 
Thanks! It works

**Comment by jcpst** [comment]
Is there a reason [this pull request](https://github.com/substack/node-browserify/pull/995) was never reviewed or merged?

It would be very nice if Browserify created the output directory.
