### ISSUE TITLE
For loop include() - Module not found

### ISSUE THREAD

**Issue by odin3** [substack/node-browserify#1573]
I have a code:
```
var filters = [
        'currency',
        'string',
        'array',
        'math',
        'json',
        'capitalize',
        'toLower',
        'toUpper'
    ];

for(var c = 0; c < filters.length; c++) {
   require('./filters/'+filter+'.js');
}
```

In browser is see: **Module not found: [my path to one of modules list]**

This code is working perfectly on Node.js, also if I use one by one require manually, it's works on browser.

**Comment by terinjokes** [comment]
@odin3 Browserify doesn't run your code to determine what should be required and bundled, but instead looks at the files. If your requires don't look like `require('./filters/currency.js')` browserify is not going to see them.

You have a few options:

1. Call `require` individually for each file. This is the simplest option.
2. Keep your code the same, but require each file during the build (via the `--require` CLI flag, or the `b.require()` function).
3. Use a Browserify transform [bulkify](https://github.com/substack/bulkify) along with [bulk-require](https://www.npmjs.com/package/bulk-require).
