### ISSUE TITLE
Substituting module as a builtin module

### ISSUE THREAD

**Issue by alexjeffburke** [substack/node-browserify#1575]
Hi,

I have been trying to build a bundle where a particular core module is swapped out for something else i.e. I need require('net') to return something particular after bundling. There is a mention that this is possible on a shim intended for use with browserify, but I honestly can't find how to make this happen.

Would greatly appreciate any hints.

Thanks, Alex J Burke.

**Comment by MellowMelon** [comment]
Have you looked at [aliasify](https://github.com/benbria/aliasify)?

**Comment by terinjokes** [comment]
The documentation for Browserify lists the following option:

> opts.builtins sets the list of built-ins to use, which by default is set in lib/builtins.js in this distribution.

You can `require('browserify/lib/builtins')` and extend the object to add a replacement for `net`.

```javascript
var builtins = require('browserify/lib/builtins');
var browserify = require('browserify');

var b = browserify('./entry', {
  builtins: Object.assign({}, builtins, {
    net: {
      isIP: function () {}
    }
  })
});

b.bundle().pipe(process.stdout);
```

**Comment by alexjeffburke** [comment]
Hi, appreciate the suggestions - I did see that note about builtins in the documentation but it wasn't at all clear to me how to use it in practice. And it seems that in aliasify I've also potentially got options :) Thx
