### ISSUE TITLE
can't use require('express')

### ISSUE THREAD

**Issue by neocris** [substack/node-browserify#1588]
hi. i'm trying to do this in a js file which later i bundle with browserify and insert in client-side html:

```
var http = require('http')
var express = require('express');
var exp = express();
```
it's using browserify port of node's native http module and npm express module, but it gives me an `TypeError: http.IncomingMessage is undefined` on the `require('express')` statement. what's going on? i'm guessing that i can't use express locally because it needs some node apparatus not provided by browserify bindings, namely listening on ports and such, is that it?

**Comment by substack** [comment]
browserify's http implementation only includes the client part of http, not the server implementation. The core http server in node extends the tcp server implementation, so that won't work in browsers by default.
