### ISSUE TITLE
Programmable API alternative to --ingore-missing?

### ISSUE THREAD

**Issue by XWhatevs** [substack/node-browserify#1595]
When using the Browserify CLI to bundle files, you can use the `--ignore-missing` flag to ignore all missing dependencies in the file. 

What is the programmable API alternative to that? The `opts` object doesn't seem to have an alternative either, and I couldn't find anything in the documentation. 

Thanks.

**Comment by blahah** [comment]
The CLI uses an undocumented option: https://github.com/substack/node-browserify/blob/master/bin/args.js#L114

So the programmatic equivalent is:

```js
const browserify = require('browserify')({ ignoreMissing: false })
```
