### ISSUE TITLE
What does browser-specific shim mean?

### ISSUE THREAD

**Issue by sophieyoung717** [substack/node-browserify#1599]
Hi,

When you require() any of _**http**_ modules, you will get a browser-specific shim.

What does browser-specific shim mean?

If I ran the output file of browserify, it will not work. Is there way to make it work? Thanks.

**Comment by chinedufn** [comment]
Hey @sophieyoung717 ,

`require` in browserify is meant to replicate `require` in node as closely as possible

When you require `http`, `crypto`, `process`, `fs` or any of the other node core modules in node you'll get a dependency that would never work properly (or at all) in the browser.

So in browserify, these dependencies get replaced with "browser-specific" shims that will actually work in your browser.

For example: When you `require('http')` in the browser, you get [this http shim](https://github.com/substack/http-browserify)

If you `require('http')` in node, you get the [core http module](https://nodejs.org/api/http.html) which isn't suited for a browser.
