### ISSUE TITLE
How to call modules after converted by browserify?

### ISSUE THREAD

**Issue by lhf552004** [substack/node-browserify#1610]
Dear @substack , sorry to ask this foolish question, but I'm a new one for browserify, I 'm confused for the question for a long time. 
Here is my test.js  which run at server normally

```
var init = function() {
console.log("here2");
}
exports.init = init;
```

Now I want use this module at front end, so I converted it with browserify:
`browserify test.js > bundle.js`

Then I add it to my html, but I can't not call my init function.

```
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>

<script src="bundle.js"></script>
<script>
    init();
</script>
</head>
<body>

</body>
</html>
```

I found similar question on google, but the answser change the module. This is not I want. I want my init function.
http://stackoverflow.com/questions/36510404/cannot-call-modules-function-after-browserify/
Please help me who is confused about browserify,

**Comment by chinedufn** [comment]
Hey @lhf552004,

I wouldn't recommend it, but if for some reason you really needed to call your `init` function from outside of your browserify bundle... try:

```
// Inside of your test.js
window.init = init
```

Then your code example above should work.

---

Granted, you should rarely need or want to do something like this. I'd suggest taking a look at the [node modules api documentation](https://nodejs.org/api/modules.html) to better understand how to use your init function from outside of that `test.js` file

Cheers!

**Comment by terinjokes** [comment]
You may also be interested in the "--standalone" flag that generates a UMD bundle with a name that you specify.
