### ISSUE TITLE
Unable to install browserify

### ISSUE THREAD

**Issue by naveenjafer** [substack/node-browserify#1621]
While trying to install browserify I run into the following issue 
`npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: esprima-six@~0.0.3
npm ERR! Valid install targets:
npm ERR! 1.0.2, 1.0.1, 1.0.0
`
I have the latest npm version as you can see. Any ideas what might be causing this? esprima-six is not a direct dependency of browserify.

**Comment by terinjokes** [comment]
@naveenjafer Version 3 of npm attempts to build an idealized tree for all your dependencies, including the one you're currently installing, then attempts to make the tree on disk match. Literally any module you have install could be pulling in an `esprima-six` dependency that now fails.

There is no `esprima-six` dependency anywhere underneath Browserify.
