### ISSUE TITLE
[discussion] Reducing the size of your browserify builds

### ISSUE THREAD

**Issue by fergiemcdowall** [substack/node-browserify#1630]
So you have browserified your code, and the resulting bundle is much bigger that you would like. What steps do you go through to make it smaller?

**Comment by chinedufn** [comment]
Hey Fergus,

Usually:

- minify with [uglifyjs2](https://github.com/mishoo/UglifyJS2)
- gzip
- If you happen to have any large deps, use [browserify-shim](https://github.com/thlorenz/browserify-shim) to load them from a CDN (instead of bundling them)

**Comment by terinjokes** [comment]
Thanks @chinedufn! One other thing, to visualize what's taking up space in a bundle, check out [disc](https://github.com/hughsk/disc).
