### ISSUE TITLE
Using less in browserify

### ISSUE THREAD

**Issue by roberthartung** [substack/node-browserify#1634]
I would like to write an application that uses the less compiler at **runtime**. When using

```js
var less = require('less');
```

browserify fails at `require('./utils');` from within the less node package. I discovered that when I add the following line to my script, I can use the internal less-browser *package*:

```js
var b = browserify('app.js');
b.require('./node_modules/less/lib/less-browser/', {'expose': 'less'});
```

Then I only need to do the following in *app.js*

```
var less = require('less');
var lessc = less(window, {});
lessc.render('@mycolor: #f00; .body { background-color: @mycolor; }').then((css) => {
  console.log('less.css', css);
});
```

**Comment by substack** [comment]
You could submit a patch upstream to the less project. Less could put that directory in its package.json as the "browser" field:

``` json
"browser": "less/lib/less-browser"
```

Anyhow this is a less bug, not a browserify issue necessarily.

**Comment by roberthartung** [comment]
less already has a browser field, so they probably won't change it!

```
"browser": "./dist/less.js"
```
