### ISSUE TITLE
Edge 35 issue and stream-http

### ISSUE THREAD

**Issue by ecoslado** [substack/node-browserify#1644]
I've recently fixed an issue related with stream-http. GET requests via http library doesn't work on Edge 35. Would you upgrade stream-http dependency in browserify to get this change?

**Comment by terinjokes** [comment]
@jhiesey Is there a change to `stream-http` we need to pull in? I don't recall seeing a PR for one.

**Comment by jhiesey** [comment]
I believe this is the relevant one: https://github.com/jhiesey/stream-http/pull/54

**Comment by terinjokes** [comment]
@jhiesey Ah thanks

@ecoslado Looks like if you reinstall browserify you'll get this change.

**Comment by ecoslado** [comment]
thanks a lot  :)
