### ISSUE TITLE
"Cannot find module" exception for "virtual" Vinyl 2.0.0 files

### ISSUE THREAD

**Issue by marionebl** [substack/node-browserify#1646]
### Actual
When fed a `Vinyl` [2.0.0](https://github.com/gulpjs/vinyl/releases/tag/v2.0.0) file that does not exist on disk, browserify throws an error with message `Cannot find module ${moduleId} from ${opts.base}`. With `Vinyl` at version 1.2.0 no error ist thrown.

### Expected
No error is thrown for non-existing `Vinyl` [2.0.0](https://github.com/gulpjs/vinyl/releases/tag/v2.0.0) files

### Steps to reproduce

```
npm install vinyl@2.0.0
npm install browserify@13.1.1
```

```js
// test.js
const browserify = require('browserify');

const bundler = browserify();
const file = new Vinyl({
  contents: new Buffer('/* beep. boop.*/'),
  file: 'beep-boop.js'
});

bundler.add(file);
bundler.bundle(function(error, results) {
	if (error) {
		throw error;
	}
	console.log(results);
});
```

```shell
node test.js
```

Thrown error:
```
Cannot find module 'beep-boop.js' from '~~'"
      ~~/node_modules/resolve/lib/async.js:46:17
    process (~~/node_modules/resolve/lib/async.js:173:43)
    ondir (~~/node_modules/resolve/lib/async.js:188:17)
    load (~~/node_modules/resolve/lib/async.js:69:43)
    onex (~~/node_modules/resolve/lib/async.js:92:31)
    ~~/node_modules/resolve/lib/async.js:22:47
```

### Analysis
`Vinyl` removed the `.pipe` method from file objects with version [2.0.0](https://github.com/gulpjs/vinyl/releases/tag/v2.0.0): ([Issue](https://github.com/gulpjs/vinyl/issues/107) | [Commit](https://github.com/gulpjs/vinyl/commit/91073b49fd4fdd056e69610077836e970b1299c0)). This causes the `isStream` utility in browserify ([source](https://github.com/substack/node-browserify/blob/10b93d8e27be696655beaf7cda57c81c96f95367/index.js#L795)) to return `false` for `Vinyl` files as of version 2.0. In turn browserify does not the enter the `isStream(input) === true` branches at [L42](https://github.com/substack/node-browserify/blob/10b93d8e27be696655beaf7cda57c81c96f95367/index.js#L42) and [L131](https://github.com/substack/node-browserify/blob/10b93d8e27be696655beaf7cda57c81c96f95367/index.js#L131), causing fs io that did not occur with `Vinyl` 2.0.0 files. For files that actually do not exist on disk errors are throw.

### Way forward
I'd be happy to contribute a PR for this but I am not sure on how to go forward – does browserify explicitly supports `Vinyl` files at all? Does this warrant extra code branches for `Vinyl` files?

**Comment by terinjokes** [comment]
No, Browserify does not support `Vinyl` instances. The fact it worked before was incidental, and it seems the developers decided they didn't want to continue supporting that implementation.

As you can see from the code, browserify expects a string for the file path or a `Stream` as inputs to the `require` method. You should either not create Vinyl files (if you're creating them, as in the example) and pass the file path or extract the `contents` property. If the latter, make sure to also pass in [`opts.file`](https://github.com/substack/node-browserify/blob/10b93d8e27be696655beaf7cda57c81c96f95367/index.js#L135).
