### ISSUE TITLE
Propagate events to vinyl stream

### ISSUE THREAD

**Issue by falsandtru** [substack/node-browserify#1653]
I want to handle error events after processing with pipes.

```js
function compile() {
  return browserify()
    .bundle()
    .pipe(source(`${pkg.name}.js`))
    .pipe(buffer())
    .on("error", err => done = console.log(err + '')) // <- here
    .once("error", function () {
      this.once("finish", () => process.exit(1));
    });
}
```

But it is impossible because Browserify doesn't propagate events to vinyl stream. Then Browserify throws `throw er; // Unhandled 'error' event`. So I need to write like the following code.

```js
function compile() {
  let done = true;
  return browserify()
    .bundle()
    .on("error", err => done = console.log(err + '')) // <- here
    .pipe(source(`${pkg.name}.js`))
    .pipe(buffer())
    .once("finish", () => done || process.exit(1));
}
```

Could you propagate events?

**Comment by falsandtru** [comment]
The actual case is here. Compile errors of TypeScript cannot handle after other processing.

```js
function compile(paths) {
  let done = true;
  return browserify({
      basedir: '.',
      debug: false,
      entries: Object.values(paths).map(p => glob.sync(p)),
      bundleExternal: false,
      cache: {},
      packageCache: {}
    })
    .require(`./${pkg.name}.ts`, { expose: pkg.name })
    .plugin(tsify, require('./tsconfig.json').compilerOptions)
    .bundle()
    .on("error", err => done = console.log(err + ''))
    .pipe(source(`${pkg.name}.js`))
    .pipe(buffer())
    .pipe($.derequire())
    .once("finish", () => done || process.exit(1));
}
```

https://github.com/falsandtru/pjax-api/blob/master/gulpfile.js

**Comment by MellowMelon** [comment]
This is a behavior of NodeJS streams more generally. See https://github.com/nodejs/readable-stream/issues/129 for some info. In short, error event forwarding unlikely to become default behavior. There are userland solutions like [pump](https://github.com/mafintosh/pump), although the syntax required is a bit saddening.

Closing since this isn't browserify specifically.

**Comment by falsandtru** [comment]
Thanks for the info!
