### ISSUE TITLE
No error output when running tests with browserify

### ISSUE THREAD

**Issue by binarykitchen** [substack/node-browserify#1659]
Unit tests of my npm library https://github.com/binarykitchen/videomail-client fail on travis ci each time (https://travis-ci.org/binarykitchen/videomail-client) and there's not much information why.

Also have asked a dev from travis to reproduce this on a docker image. Here the Gist log
https://gist.github.com/BanzaiMan/0450b14967f6677a68f253781586a058

Doesn't say much either. Is browserify somehow hiding the real error? Command to run test `browserify test/**/*.test.js --debug | tape-run --render=tap-spec`

Hope anyone has a clue?

**Comment by substack** [comment]
browserify would print an error. Maybe tape-run is eating an error or hasn't been set up propertly? Your travis.yml file looks like it's doing what tape-run recommends, so I don't know what it could be.

**Comment by binarykitchen** [comment]
thx @substack 

... @juliangruber hello there, do you think you could have a look and confirm if this smells like a tape-run issue? if so, then i ll move this ticket over to your repo at https://github.com/juliangruber/tape-run

**Comment by juliangruber** [comment]
hm. does this happen without the tap-spec renderer too?

**Comment by juliangruber** [comment]
feel free to move it over to tape-run, i don't think this is a browserify issue

**Comment by binarykitchen** [comment]
thanks fellas, moved to https://github.com/juliangruber/tape-run/issues/48
