### ISSUE TITLE
Upgrade acorn in dependencies

### ISSUE THREAD

**Issue by timwis** [substack/node-browserify#1667]
I was hoping to use `async/await` now that it's fully supported by Chrome (without browser flags), but browserify was giving me a syntax error. @pluma helped point me to acorn and the various dependencies that depend on it. I've submitted pull requests to upgrade the acorn version used by all the node-browserify dependencies I could find.

* substack/astw#10
* substack/browser-unpack#15
* substack/node-detective#67
* substack/node-syntax-error#18

`npm test` passes in all repos. Let me know if I missed one and I'm happy to submit another PR.

**Comment by martinwebrant** [comment]
Note that ecmaVersion default to 7(2016) in acorn and that some packages like detective gives it's own default 6(2015) instead of acorns. You need 8(2017) for async/await.

**Comment by pfrazee** [comment]
Can we get this merged?

**Comment by substack** [comment]
Everything is up to date. On a clean install of browserify you should be able to use async/await.

**Comment by timwis** [comment]
Verified! Thanks :)
