### ISSUE TITLE
latest release include 'v' prefix in release tag

### ISSUE THREAD

**Issue by MylesBorins** [substack/node-browserify#1679]
All previous releases did not include the `v` prefix in the tag, `v14.0.0` is the first and breaks the pattern of no prefix e.g. `13.3.0`.

**Comment by gdams** [comment]
It is worth noting that this is not an issue with citgm as the above PR will fix it from our end but we don't want to make a change that you guys will then revert to with the next release

**Comment by feross** [comment]
I'll fix this later today, by deleting the current tag and creating a new one, when I'm at my computer (unless someone else gets to it first).

**Comment by gdams** [comment]
thanks, please close this issue when this has been rectified

**Comment by feross** [comment]
This is fixed now.
