### ISSUE TITLE
Can't seem to ignore requires that start with '.'

### ISSUE THREAD

**Issue by cpboyd** [substack/node-browserify#1681]
If the `ignore` starts with a '.', then special changes are made:
```javascript
Browserify.prototype.ignore = function (file, opts) {
    if (!opts) opts = {};
    var basedir = defined(opts.basedir, process.cwd());

    // Handle relative paths
    if (file[0] === '.') {
        this._ignore.push(path.resolve(basedir, file));
    }
    else {
        this._ignore.push(file);
    }
    return this;
};
```

But these are not then applied when using it as a filter.
E.g.:
`browserify('path/to/file.js').ignore('./test.js')` doesn't seem to work if `file.js` contains `require('./test.js')`

I have a work-around by simply adding a check that replicates the ignore's `resolve` transform.
```javascript
    mopts.resolve = function (id, parent, cb) {
      // Handle relative paths
        if (id[0] === '.') {
          if (self._ignore.indexOf(path.resolve(basedir, id)) >= 0) return cb(null, paths.empty, {});
        }
        if (self._ignore.indexOf(id) >= 0) return cb(null, paths.empty, {});
```

**Comment by pushred** [comment]
Are you also passing `basedir` as an option to the ignore method? This defaults to `process.cwd()` which could be throwing off the path resolution (you can log out the value pushed to `_ignore` to confirm.

**Comment by cpboyd** [comment]
I've tried using `basedir` as an option.

I've also tried using `ignore()` with a completely relative path (without the '.') as well as the full absolute path to the file.

Neither seems to have any impact on the `require()` calls that start with `.`

**Comment by cpboyd** [comment]
For reference, I'm trying to use gulp to have a custom build of chart.js:
https://github.com/chartjs/Chart.js/blob/master/src/chart.js

**Comment by pushred** [comment]
To confirm, you passed basedir to the ignore method, not just the Browserify instance? I was pretty confused myself but was clear when I had a look at the source you posted above, note that there isn't a fallback to `this._options` — the options are only what you pass to the method.

Aside from this it's up to node's [Path.resolve](https://nodejs.org/api/path.html#path_path_resolve_paths) method to construct your paths, which will need to resolve to the correct locations of the files to ignore. I think something like this should work unless I'm misunderstanding how ignore actually works:

```js
browserify.ignore(path.join(process.cwd(), 'node_modules', 'chart.js'), './core/core.tooltip')
```

Alternately you can also use [`require.resolve('moduleName')`](https://nodejs.org/api/modules.html#modules_all_together) to get absolute paths to the Chart.js modules.

**Comment by cpboyd** [comment]
@pushred I had not, until now.
However, that didn't really seem to change much.

Ultimately, it seems that I simply needed to add the '.js' to the end and the ignores work perfectly since it's referencing the file rather than the `require()` itself.
