### ISSUE TITLE
Question: "Process" object becomes a browser process instead of a node process 

### ISSUE THREAD

**Issue by TifPun** [substack/node-browserify#1698]
Hi, 

I am trying to use the `process` in my "browserified" node app, and I am not able to get the process to work correctly. If I should post this question somewhere else please redirect me.

The following code snippet is a simplified version of what I am trying to do in my node app (file name: server.js)

```
var readline = require("readline");
var process = require("process");
var Big = require("big.js");  // A module that I want to bundle with my app

// create an interface to read user input from the command prompt
 process.stdin.setEncoding("utf8");
  var rl = readline.createInterface({
    input: process.stdin,
    terminal: false
  });

// capture the user input then do some calculation
  rl.on("line", function(line){
    // Use Big for some calculation
  });

```

My code works fine if I just call `node server.js`. However, after I bundle the code by calling `browserify server.js -o bundle.js`, now if I call `node bundle.js` I would get the following error which indicates that process doesn't have stdin:

```
process.stdin.setEncoding("utf8");
              ^

TypeError: Cannot read property 'setEncoding' of undefined
    at Object.__dirname.3.process (/Users/tp/coursera/bundle.js:221:15)
    at s (/Users/tp/coursera/bundle.js:1:316)
    at e (/Users/tp/coursera/bundle.js:1:487)
    at Object.<anonymous> (/Users/tp/coursera/bundle.js:1:505)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
 ```

 I compared the `process` variable when I ran the code from the raw server.js file, vs. my bundled bundle.js file and noticed a huge difference between the two processes. The main difference is that the process from the raw server.js is a **Node** process, while the process from the bundled file is a **browser** process. 

I read about the [Process section on the handbook](https://github.com/substack/browserify-handbook#process) and tried some solutions mentioned on some issues (e.g. [this one](https://github.com/substack/node-browserify/issues/1277)) in this repo, but they didn't seem to work for me. I feel like I am not understanding some fundamental concepts correctly. I'll appreciate it if someone could help point me out of what I have misunderstood.

---
In case you want more info of what I am trying to do: 
I am taking a online course which requires me to use Node.js for my assignment. My program needs to read input from the command prompt then do some calculation. I have to submit a single .js file for the grader to work. After some research it seems that browserify will be the way to go for bundling my modules and external modules.

Thanks again

**Comment by substack** [comment]
Try compiling with `--node`:

    browserify server.js --node > bundle.js

**Comment by TifPun** [comment]
THANK YOU @substack , it works for me!!! 

I did a bit more reading about the --node (and its associated flags: `--bare`, `--no-browser-field`. So my understanding now is... since I am trying to run my bundle.js file as a node app/"node process" using`node bundle.js`, that's why I need the --node flag when calling browserify. If, on the other hand, I am trying to load the bundle file on an HTML page, then the flag won't be needed because I am running it on a "browser process". Can you please let me know if this is a correct understanding?

THANK YOU again!! Your help is the best thing happened to me today :)

**Comment by substack** [comment]
Yes that's a correct understanding. The usual way to use browserify is to run code in the browser but sometimes it makes sense to compile bundles for node or electron.

**Comment by Tif-P-HK** [comment]
Thanks again @substack !
