### ISSUE TITLE
browserify field flags to switch behavior based on dev/prod/...

### ISSUE THREAD

**Issue by serapath** [substack/node-browserify#1706]
Browserify has the awesome feature, that every dependency can specify it's own transforms in a "browserify" field in it's `package.json` :+1: 

**My issue:**
* While I'm developing I run watchify and don't need minification or extensive testing or transpilation of modern es6 code and beyond and I want my pipelin to be fast.
* When I'm building for production, I want minification and transpilation es6toes5 for legacy browser support and a separate source maps file and so on...

**Idea:**
Is it or would it be possible to switch the behavior of a module's "browserify pipeline" as defined in it's "browserify field" based on environment variables or alternatively based on spec?

**I would be willing to try to come up with an implementation and a pull request - but i first want to make sure if this would be acceptable and if so - what would be the best way** :-)

**Comment by MellowMelon** [comment]
To ignore the transform/browserify fields of other package.json files, pass `transformKey: false` when constructing the browserify object.

This was very recently added and apparently not documented. Check the [last commit](https://github.com/substack/node-browserify/commit/bf061d8d8cd7769c3a74ef4569d7adda60ef3f4f) that changed this repository's index.js. That commit also has a test you can look at.

**Comment by serapath** [comment]
I don't want to ignore the transform of browserify fields of other package.json files. It's awesome and i like it.

I just would like to customize the transforms listed in each projects package.json based on environment variables, e.g. production, development, staging, ...

For example, in `"production"` i want to do minification or polyfilling or a lot of more things that i might need in order to support old browsers and improve performance, etc...

In  `"development"` i dont care to minify or to polyfill, because i'm developing on a modern browser. So i'd like to skip a lot of transforms to speed up the build process, because i want to live-reload on every file save and that should be fast.

babel for example seems to support something like `env options` https://babeljs.io/docs/usage/babelrc/

Otherwise, I am just wondering if such a feature would fit with browserify and if not if maybe things can be done differently or in other places, so that there is no need for those flags.

**Comment by serapath** [comment]
Here you go - changedt he proposal from above slightly to use:
* `browserify index.js --transform-key=production > bundle.js`

This is probably better than camelcase...

**Comment by serapath** [comment]
ok got merged. perfect :-)
