### ISSUE TITLE
Cannot bundle when it includes an already bundled module

### ISSUE THREAD

**Issue by binarykitchen** [substack/node-browserify#1745]
In package A I am bundling with latest browserify + babelify library code written in ES6 into its `/dist/a.js` file whichi is also defined in the `main` entry of its package.json. And it's published like that to npm along with its source code in the `/src` folder.

Now, in another project B, I am requiring that package A in the app code and browserify all together before running the app B. And here it fails, it cannot resolve some dependencies A is having.

Makes me wonder if it's good practice to browserify another bundle which already has been browserified?

(on a side note, it does not happen when `main` in package.json is pointing to the source code entry instead of the dist file. So that confirms it's a bundling issue.)

**Comment by zdychacek** [comment]
Hi,

published NPM packages should not be bundled to allow bundlers like Browserify or Webpack or NodeJS runtime consuming them. You can't `require` already bundled module. Packages published to NPM should be bundler agnostic.

You should publish your package with "dist" code transpiled to ES5 using Babel and optionally with ES2015+ source code.

**Comment by binarykitchen** [comment]
right, i figured that out but then, found a cool solution: just bundle with the `standalone` option, use the `derequire` plugin afterwards et voila, you can put that in `/dist` and publish on npm. another project can `require()` it and browserify all over again without problems. works! standalone + derequire is the trick.
