### ISSUE TITLE
How to run Browserify after installing it locally?

### ISSUE THREAD

**Issue by RichardJECooke** [substack/node-browserify#1750]
Hi, first time Browserify user. How do I install it with npm locally and run it, as opposed to using -g?  I don't want it to affect the other projects and packages on my system.

I installed it locally but cannot see the `browserify` command mentioned in the documentation:
![untitled](https://user-images.githubusercontent.com/5468805/28935724-c62e2c2a-7885-11e7-8960-8a61de39afc9.png)

**Comment by substack** [comment]
npm should have made .bin/browserify. Can you try again and also post the version of npm you're using?

**Comment by RichardJECooke** [comment]
Weird. I ran `npm uninstall browserify && npm install browserify` again and now it's there! 
Ok, thanks.
