### ISSUE TITLE
No information on what transforms are available

### ISSUE THREAD

**Issue by jmax315** [substack/node-browserify#2085]
There is literally no information on what transforms are packaged with browserify.
Apparently there used to be a wiki page? Can this information be resurrected somewhere, please?

**Comment by ljharb** [comment]
I've restored the wiki, but I'm not sure if there's any transforms listed.

**Comment by jmax315** [comment]
Yup, you put back exactly what I was looking for: https://github.com/browserify/browserify/wiki/list-of-transforms

Thank you very much.
