### ISSUE TITLE
transformers require using extension in require() invocations

### ISSUE THREAD

**Issue by pmuellr** [substack/node-browserify#326]
This is awful.

I enjoy having the freedom of writing in CoffeeScript or JavaScript, and making use of the require() hack in node to load .coffee files automagically.  Or, if I want, compile to JS.  Code works either way.

If I want to use transformers, now I need to reference CoffeeScript modules with a ".coffee" extension in the require() parameter, which means compiling to JS won't work anymore.

Seems like what needs to happen is:
- transformers should indicate extensions they consider valid module source
- those extensions should be taken into account when resolving modules

**Comment by deadlyicon** [comment]
@pmuellr it sounds like you're suggesting the following command

```sh
npm install coffeeify --save --extension .coffee --transform coffeeify
```
which does yields the following error:

```
npm ERR! addLocal Could not install /Users/deadlyicon/Work/progwiki.com/.coffee
```

Can you be more clean?

Thanks!

**Comment by deadlyicon** [comment]
This is what I needed to do to get require sans .coffee to work

```coffee
web.get '/app.js', (req, res) ->
  res.setHeader('content-type', 'application/javascript')
  b = browserify(__dirname + '/app/index')
  b._extensions.push('.coffee')
  b = b.transform('coffeeify').bundle()
  b.on('error', console.error)
  b.pipe(res)
```

note the `b._extensions.push('.coffee')`

**Comment by pmuellr** [comment]
@deadlyicon, I think you've combined the `npm install` with a browserify invocation, in the 2nd most comment.  My reading is 

1. install `coffeeify` via `npm install coffeeify`
2. when you invoke `browserify`, use the `--extension .coffee --transform coffeeify` options.

I've not used `browserify` dynamically, as your previous comment suggests, so can't offer any help there.

**Comment by deadlyicon** [comment]
Thank you @pmuellr
