### ISSUE TITLE
source maps should be exportable to file

### ISSUE THREAD

**Issue by matthiasg** [substack/node-browserify#339]
while i appreciate the recent addition of the --debug option to add source maps into the file as base64 it would be nice to have an option of writing it to a file instead. 

If that where possible tools like uglify js could use it as an input to create their own source maps on top and we could have source maps all the way back from minified code to the original sources.

**Comment by polkovnikov-ph** [comment]
I'm not sure if `exorcist` will quite cut it, because there're important tools like `watchify`, and it's not very obvious how to use `exorcist` with them. Personally I'd prefer a `browserify` plugin solution.
