### ISSUE TITLE
Unicode characters get messed up

### ISSUE THREAD

**Issue by esamattis** [substack/node-browserify#349]
For example d3.js uses some weird unicode characters as variable names:
https://github.com/mbostock/d3/blob/91d35b4205d4ef150c61c415b7379404bced7267/d3.js#L1283

Browserify outputs this as

```
var Ï€ = Math.PI, Îµ = 1e-6, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;
```

Which is syntax error.

Terrible practice by d3, but this should not break Browserify.

**Comment by jtremback** [comment]
Ha!

**Comment by zbjornson** [comment]
In case this helps anyone in the future: on Windows using powershell (posh git/git shell), redirecting browserify's output with `>` mucks up utf8 characters. Instead, use `-o`: `browserify [entry files] -o outputfile.js`.
