### ISSUE TITLE
Browserify a Browserified module

### ISSUE THREAD

**Issue by jackcviers** [substack/node-browserify#374]
So I have three modules to use in an app in a browser.

`module-b` depends on `module-a`.

`module-a` depends on `Handlebars` and is composed of several individual internal dependencies, relatively required as in the documentation. `module-a`'s foo.js requires bar.js, like so:

```
var Handlebars = require('handlebars');
var bar = require('./bar.js');
```

I browserify `module-a`. I run it through tests, and everything is good and index.js is produced and it contains foo, bar, and Handlebars and the exports look good and are tested via the requires in the test, so, I `npm link module-a`.

I go to `module-b` and `npm link module-a`, which installs a symlink in the node_modules folder of `module-b`.

When I browserify `module-b`, which has a statement of `var module-a = require('module-a');`, I get a bunch of browserify errors, like the following:

```
Error: module "./handlebars/base" not found from "/home/blah/Development/module-b/node_modules/module-a/index.js"
```

This seems strange, since `module-a` is already browserified.  I've tried with `-r module-a`, `-x module-a`, `--ignore-missing`, `-i 'handlebars'`. Browserify just keeps spitting out the same error. I assume that it would fail for `module-a's` internal `./bar.js` dependency as well, but it dies before it even gets that far.

Is this expected behavior, is it a bug, or am I not configuring the cli call to browserify correctly?

**Comment by jmm** [comment]
@ajkochanowicz At least as a temporary workaround, can you use `opts.noParse`? So using @jackcviers' scenario, browserify `module-a` as standalone. In `module-b` `require('module-a')`, and browserify `module-b` like so:

```js
browserify({
  entries: ['./entry'],
  noParse: ['/abs/path/to/module-a-including-extension.js'],
)
```
The `noParse` values currently appear to be sensitive to how the path is indicated. In my quick testing, the absolute path with extension was the ticket. It may depend how you `require()` `module-a` though -- there are currently a lot of issues with resolving and matching up paths specified in various places.

**Comment by tchannel** [comment]
@jmm thanks for the `noParse` suggestion! this helped me clear up an issue with a third-party module that was not built standalone

**Comment by jmm** [comment]
@tchannel Cool, thanks!

FYI everybody on this thread, how to solve the "browserify a browserified module" case is being discussed in #1151.
