### ISSUE TITLE
Support for lazy evaluation.

### ISSUE THREAD

**Issue by bigeasy** [substack/node-browserify#458]
Wondering if this behavior is already supported and if not if it would be at all desirable:
- [Lazy evaluation of CommonJS modules](http://calendar.perfplanet.com/2011/lazy-evaluation-of-commonjs-modules/)

// cc @tobie

**Comment by kentor** [comment]
Watchify + sourcemaps takes around 1 second to rebuild. I tried out webpack + eval-source-maps and that takes 400ms to rebuild. Is it the eval source maps that's making it faster? Would be nice to have lazy evaluation in browserify...
