### ISSUE TITLE
module.require isn't present

### ISSUE THREAD

**Issue by fb55** [substack/node-browserify#475]
In node.js, `module.require` is the basis for the `require` function. Browserify instead directly hands the `require` function over, without exposing any functionality as `module.require`.

I'm trying to browserify a module that uses [defaultable](https://github.com/iriscouch/defaultable), which heavily depends on the behavior of node.

It would be awesome if `module.require` could be at least a reference to the `require` function.

**Comment by montamal** [comment]
This is still an issue. https://github.com/browserify/browser-pack/pull/19

**Comment by Avaq** [comment]
Apollo Server also uses `module.require`:

https://github.com/apollographql/apollo-server/blob/bbcedd9fdc05a32104433f8d472c73a2f05aa51a/packages/apollo-server-core/src/utils/createSHA.ts#L5-L7
