### ISSUE TITLE
Support for node-webkit

### ISSUE THREAD

**Issue by JPGygax68** [substack/node-browserify#481]
The following are suggestions.

The node-webkit project fuses NodeJS and webkit into a single runtime environment.

This makes it easy to require() modules intended for Node, which will (mostly) work. Sometimes though, you want to load modules into the browser "aspect" of node-webkit, and browserify is great for that. However, there are two problems:

1) browserify's require() hides the one provided by the NodeJS aspect of node-webkit.
(This can be worked around by simply putting all the node-dependent modules before the browserify-generated bundle)

2) browserify generates a "process" object that hides the one provided by the NodeJS aspect of node-webkit.
(This can be worked around as well, by assigning the original process object to a global variable.)

Even though work-arounds exist for both issues, I think it would be better if browserify could be told to a) provide its require() method under a different name and b) refrain from generating its own process object.

Other than that, thanks for providing a great tool!

**Comment by gregorym** [comment]
I'm still seeing this issue, especially when a dependency requires a node module.
