### ISSUE TITLE
Recursive transforms

### ISSUE THREAD

**Issue by allouis** [substack/node-browserify#501]
No ability to use -t recursively, found this issue with having Backbone.View's referencing their template.hbs files. When all in root directory hbsfy works fine, however when views are listed as depenecies and so in node_modules/modulename/ or  node_modules/modulename/node_module/submodulename this fails. 

How difficult would it be to implement recursive transforms? Can see this being a nice addition

**Comment by jampekka** [comment]
So ad-hoc. :'(
