### ISSUE TITLE
Alias (= require with expose option) include the file alias file in bundle in anycase 

### ISSUE THREAD

**Issue by alexstrat** [substack/node-browserify#510]
Following #290,  "aliasing" a module can be done with:

```js
b.require(__dirname + '/client-side-fs.js', { expose: 'fs' });
b.add('entry.js')
````

That makes the file `/client-side-fs.js` be bundled and used as `fs`.

However, wether `entry.js` (or dependencies) uses `fs` or not, `/client-side-fs.js` gets bundled in any case.

I guess that's an expected behavior. However, is there a way to declare `/client-side-fs.js` as an alias of `fs` and not bundle it if `fs` is not used? Shouldn't be an option?

**Comment by terinjokes** [comment]
I would suggest doing

```javascript
var builtins = Object.assign({}, require('browserify/lib/builtins'), {
  fs: 'path/to/client-side-fs'
});

var b = browserify({
  builtins: builtins
});
```

This would change the alias used for the builtin "fs" for all modules, and is cleaner than a per-package browser field.
