### ISSUE TITLE
require declaration syntax / closure compiler

### ISSUE THREAD

**Issue by shenanigans** [substack/node-browserify#580]
One of the "fun" things about Closure Compiler on Advanced Optimizations is managing externs when you can't compile the whole page in one package. A really easy way to make Browserify's output play nicer with Closure is to simply update the way it sets the require variable, from `require=` to `window["require"]=`. It's then possible (and easy) to write a library for compilation by Browserify/ClosureAO by simply using a string literal to set all names that should not be changed.

``` javascript
module.exports = {
    minifed:        internalFunc,
    "notMinified":  exportFunc
};
```

or

``` javascript
myClass.prototype.unassumingTask = unimportantStuffFunc;
myClass.prototype["doImportantStuff"] = importantStuffFunc;
```

The only thing preventing this stress-free use of Advanced Optimizations right now is the syntax for setting "require". Temporarily I'm wrapping my output to correct it (and another couple leading/trailing patches for output I found to be missing)

``` javascript
(function(){ var 

  // Browserify output here

; window["require"] = require;})();
```

**Comment by BlueHotDog** [comment]
still having trouble working with closure compiler+browserify
any news on adding good support for that?

**Comment by shenanigans** [comment]
I forgot to pay attention to this issue. @substack that's not a solution, closure still minifies when it finds `window.require =`. It absolutely positively must be a String literal.

This time I had better luck figuring out where the string in question comes from and [patched it](https://github.com/shenanigans/browser-pack/commit/74cca6e01025b3bb081c1f4c42bc5c6717c7e87d) however, to get Master to work at all I had to rename `prelude.js` to `_prelude.js` and I dunno what's up with that.

**Comment by tellnes** [comment]
@shenanigans: https://github.com/substack/browser-pack/pull/73 should have the side effect of fixing this also.
