### ISSUE TITLE
support pattern for --ignore

### ISSUE THREAD

**Issue by avetisk** [substack/node-browserify#591]
Would be great to ignore patterns, such as './lib-cov/_' (or using Regex './lib-cov/._').

**Comment by revington** [comment]
TL;DR globs work, the problem is your lib-cov dir does not exist when the globs are expanded.

Assuming you have an ./index.js like
```
module.exports = process.env.BLAH_COV ? require('./lib-cov/blah') : require('./lib/blah');   
``` 

`lib-cov` does not exist when you run browserify. Then the expanded globs don't cover that directory. And therefore they are not added to `_ignore`.
