### ISSUE TITLE
Relative url to sources and non-base64 source maps

### ISSUE THREAD

**Issue by Sean-Der** [substack/node-browserify#603]
I was reading this  Issue #322  and can't seem to find any follow up discussion.

Are there still plans to expand the options for sourcemaps?

Is there anyway right now I could have relative paths to my sources? Right now the path is localhost/(full-path-to-file) I could make a symlink, but that seems like a waste.

**Comment by brettz9** [comment]
Relative path concern is raised in open issue #663
