### ISSUE TITLE
Transforms not applied to named dependencies?

### ISSUE THREAD

**Issue by bclinkinbeard** [substack/node-browserify#605]
I am using [partialify](https://github.com/bclinkinbeard/partialify) as a transform to allow me to `require()` HTML files. It works fine as long as the `require('./some.html')` call is in a file that is `require()'ed via file path, but if it's required by name the HTML gets parsed directly and throws an error. Guessing it's the same root issue as #600.

**Comment by nmn** [comment]
@thlorenz I would love to be able to apply transforms to some of the modules in node_modules manually.

Perhaps something like this:
```
"browserify": {
    "dependencies": [
        "moduleName: ["brfs"]
    ]
    "transform": [ "brfs" ]
  }
```
