### ISSUE TITLE
Allow to have dots on names and namespaces

### ISSUE THREAD

**Issue by piranna** [substack/node-browserify#606]
According to http://wiki.commonjs.org/wiki/Packages/1.0, dots are allowed to be used on CommonJS packages names. This change use slashes (that's a not allowed character) to be used as namespaces separator and restored the previous behaviour by just removing the dots. An alternative, more compliant option would be to allow to use them in the namespaces names, but this would require to access to them using brackets instead of object notation.

A proposal for UMD is available as a pull request at https://github.com/ForbesLindesay/umd/pull/13

**Comment by terinjokes** [comment]
I going to close this with the same advice given in the linked thread.
