### ISSUE TITLE
Why is the prelude obfuscated in Browserify output?

### ISSUE THREAD

**Issue by callumlocke** [substack/node-browserify#623]
Browserify output starts with this:

``` javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require==
"function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new 
Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(
f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}
return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<
r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
'use strict';
```

Since the inlined modules themselves are unminified, I still need to run the whole bundle through a minifier for production anyway.

So... why obfuscate the prelude like this? Why not print it out with proper formatting and variable names, so curious devs can better understand how a Browserify bundle works?

**Comment by deostroll** [comment]
Any way to unminify the prelude part?

**Comment by terinjokes** [comment]
Sure. Here it is and even with comments. https://github.com/substack/browser-pack/blob/master/prelude.js

**Comment by deostroll** [comment]
No. I mean I want the prelude unminified in my browserified output

**Comment by henrypenny** [comment]
It would be helpful to be able to use an unminified standard prelude whilst debugging errors in one's configuration. It would be a lot easier to simply switch of the minification of the prelude off rather than create a new unminified version. Especially for browserify noobs like me.
