### ISSUE TITLE
module.id is undefined and causing ZeroClipboard to break

### ISSUE THREAD

**Issue by focusaurus** [substack/node-browserify#630]
It seems current browserify leaves `module.id` undefined in a browserified module. I determined this just by `console.log(module.id)` in the browser. Digging around a bit it looks like maybe earlier browserify versions had this. In any case, missing `module.id` causes issues with trying to install zeroclipboard through npm, bundle it with browserify, and run it in a browser. See [zeroclipboard issue 332](https://github.com/zeroclipboard/zeroclipboard/issues/332) for reference.

**Comment by felixfbecker** [comment]
Why does it add overhead? `module.id` is equivalent to `__filename` in Node. Angular 2 uses `module.id` a lot for example. Please reconsider.
