### ISSUE TITLE
Standalone option makes browserify 10x slower 

### ISSUE THREAD

**Issue by mourner** [substack/node-browserify#633]
``` bash
$ browserify -v
3.24.11

$ time browserify app.js # without standalone
...
real    0m0.616s
user    0m0.565s
sys 0m0.060s

$ time browserify app.js -s app # with standalone
...
real    0m6.525s
user    0m6.389s
sys 0m0.179s
```

What could make such a huge difference in performance? In theory it shouldn't affect it much, right? It's just a small chunk of code for UMD added...

**Comment by zertosh** [comment]
FWIW, derequire@2.0.0 is super fast now (see https://github.com/calvinmetcalf/derequire/pull/26)
