### ISSUE TITLE
Issue creating 2 bundles in sequence...

### ISSUE THREAD

**Issue by nicroto** [substack/node-browserify#637]
```javascript
function produceBundles( filePath1, filePath2, callback ) {
	var b = browserify();

	b.add( filePath1 );
	var readable = b.bundle();
	var data = "";
	readable.on('data', function(chunk) {
		data += chunk;
	});
	readable.on( 'end', function() {
		var bundle1 = data;
		data = "";

		// should I be creating a new instance?
		b = browserify();

		b.add( filePath2 );
		readable = b.bundle();
		readable.on( 'data', function(chunk) {
			data += chunk;
		} );
		readable.on( 'end', function() {
			var bundle2 = data;
			callback( bundle1, bundle2 );
		} );
	} );
}
```
I am trying to use the API of browserify for creating of multiple bundles consequently.
The first bundle is produced as expected, but the second one... the 'data' event on the stream that .bundle() returns is never fired.

Am I doing something wrong?

Thanks.

**Comment by terinjokes** [comment]
@nicroto You didn't mention what version of Browserify you were using. I gave it a quick look, and it seems fine, does it still not work in Browserify 9?

And yes, you should be creating a new instance for the second bundle.

**Comment by nicroto** [comment]
It does work with latest. Thank you @terinjokes!
