### ISSUE TITLE
How to deal with optional dependencies ?

### ISSUE THREAD

**Issue by MoOx** [substack/node-browserify#653]
I'm using Backbone & Backbone.native (as a jQuery replacement).
But with browserify, I'm having an issue [just here](https://github.com/jashkenas/backbone/blob/6ccc1583e7f27098f3970143475aab1f9713f341/backbone.js#L21)

`try { $ = require('jquery'); } catch(e) {}`

I don't want jQuery, so for now I just use this really dirty workaround:

```
mkdir ./node_modules/jquery && ln -s ../backbone.native/backbone.native.js ./node_modules/jquery/index.js
```

Any idea how to handle that ?

**Comment by dy** [comment]
Dynamic require also works in this case:

```js
try { var jq = 'jquery'; $ = require(jq); } catch(e) {}
```

Also there is [browserify-optional](https://github.com/devongovett/browserify-optional) transform (ES5 only and no source maps though).

Probably a flag to skip not found deps would be more elegant solution.

**Comment by dy** [comment]
@goto-bus-stop as far as I get there is no way to set flags in “browserify” field, right? Is there any sense in transform, forwarding its flags to browserify?
