### ISSUE TITLE
Quotation mark in regexp stops checking file

### ISSUE THREAD

**Issue by Kildyt** [substack/node-browserify#660]
Hi,

It looks like quotation mark (`"`) put in regular expression stops finding `regular` expressions.

* * *

**Steps to reproduce**
1. Create a temporary file with `.js` extension and copy this code
```javascript
/"/, require('assert');
```
2. Run `browserify`on the file with no options.

**Result**
Temporary file in bundle with no dependencies.

**Expected result**
Bundle file with included `assert` module.

**Comment by terinjokes** [comment]
The (still open) pull request @shuhei linked to notwithstanding, this is resolved with at least 9.0.8. A few version back Browserify changed how it found requires, and I suspect it would have been resolved then.
