### ISSUE TITLE
Browserify as a NodeJS app packager/uglifier

### ISSUE THREAD

**Issue by mgcrea** [substack/node-browserify#691]
I was looking for a way to "secure" NodeJS source files (basically a NodeApp running in stores on some removable media), wondered if somehow this might be possible with browserify?

I'm looking to concat any required local files then uglify the whole to end up with a single script to start my whole app (npm packages should not be included). Could be a nice addition to the project (looks like it would require to deactivate some features), maybe with flags, like `--target-node --uglify`?

Thanks!

**Comment by terinjokes** [comment]
This can probably be done with the command line flag `--bare`.
