### ISSUE TITLE
node 0.6 and 0.8

### ISSUE THREAD

**Issue by ljharb** [substack/node-browserify#720]
It looks like the latest browserify (via covert) breaks on node 0.6 and 0.8, although it works in node 0.4. I'm seeing Travis failures on many modules. Example: https://travis-ci.org/caolan/forms/jobs/22476731

It seems like testing tools need to work on as wide a version range as possible - can this be fixed?

**Comment by terinjokes** [comment]
As of now, the latest npm in the 1.4.x series is installed on 0.8 and above.
