### ISSUE TITLE
Allow b.external() to accept an array of files

### ISSUE THREAD

**Issue by powmedia** [substack/node-browserify#729]
I have several external dependencies I don't want to include in the main bundle; would be great if b.external() took an array of files/modules to leave out.

**Comment by davidtheclark** [comment]
Currently this is working for me in v8.1.0 -- both for `external()` and `require()`. Has it been fixed?

**Comment by peter-mouland** [comment]
works for me in v9

**Comment by devel-pa** [comment]
Stopped working from 9.0.1 to 9.0.4

**Comment by ahutchings** [comment]
This can be closed. Array support was added in https://github.com/substack/node-browserify/commit/b94b20da0d039f79c14bc361e7aaf6b4958e14a9.
