### ISSUE TITLE
a problem of '--debug' option

### ISSUE THREAD

**Issue by AnnieCyl** [substack/node-browserify#753]
When I built my bundle using `--debug` options, I got messy code with Chinese characters in source maps, like this:
![qq20140520143417](https://cloud.githubusercontent.com/assets/2242335/3023552/c9fd5b52-dfe8-11e3-84d1-a62c29557fe3.png)

All my js files are UTF-8. Here is my command:
`browserify --debug -r ./main.js > bundle.js`

But it is all normal in the bundle.js:
![2](https://cloud.githubusercontent.com/assets/2242335/3023561/e73dc0f8-dfe8-11e3-8550-143a837eeec6.png)

This problem only happens when I look into the separated source files.
How can I fix it?

**Comment by terinjokes** [comment]
https://github.com/thlorenz/inline-source-map/issues/6#issuecomment-96078718

**Comment by csbun** [comment]
update [combine-source-map](https://github.com/thlorenz/combine-source-map) to [0.7.1](https://github.com/thlorenz/combine-source-map/issues/18)

**Comment by csbun** [comment]
upgate `combine-source-map` to [0.7.1](https://github.com/thlorenz/combine-source-map/issues/18) in `browser-pack` since `inline-source-map` fixed it on [0.6.0](https://github.com/thlorenz/inline-source-map/pull/13)
