### ISSUE TITLE
`e.code == 'MODULE_NOT_FOUND'`

### ISSUE THREAD

**Issue by jbenet** [substack/node-browserify#760]
1. Normally, browserify will error out when it cannot find a module, but it (correctly) doesn't fail when the require is dynamic.
2. Many modules attempt to load optional modules, catching `e.code == 'MODULE_NOT_FOUND'` to fallback gracefully to something else.
3. Browserify's error does not include `e.code = 'MODULE_NOT_FOUND` (at least in chrome 34)

Proof at http://bl.ocks.org/jbenet/63bdbb52294c9858a959

I'm currently catching such an error using:

``` js
function (err) {
  return err.code == 'MODULE_NOT_FOUND' // node
    || err.toString().match(/Cannot find module/); //browserify
}
```

But, it would be great if Browserify included the code, as [lots of people use it](https://github.com/search?q=.code+%3D%3D+MODULE_NOT_FOUND&type=Code&ref=searchresults). Happy to PR, but not sure where the error is coming from. So far I see: https://github.com/substack/node-browserify/blob/df8d3b5a6766a85393a57c10ed49c7582e77e81c/index.js#L738 (potentially patch it in there?)

Is the error coming from `resolve` (https://github.com/substack/node-resolve/blob/591e359faf5e2eb9c7f5cc86c9ac389c43d961e8/lib/sync.js#L32)? Doesn't seem to have the " from ... " part.

**Comment by mikermcneil** [comment]
@substack Thank you!
