### ISSUE TITLE
Document how to avoid relative paths hell

### ISSUE THREAD

**Issue by slorber** [substack/node-browserify#767]
The `paths` option, that  forwards to https://github.com/defunctzombie/node-browser-resolve is not documented here

In my browserify app, for my private JS code, I don't want to use relative paths because it's annoying when you move some code from one place to another to have to update all the relative paths.
See http://stackoverflow.com/a/23608416/82609

It seems the paths option permits to make available your own js files like normal node modules.
As far as I have seen it works pretty fine and the browserify app is being build without using relative paths.

The problem is that in my paths folders I have JSX React files that must be compiled to JS before being integrated by browserify.
It seems browserify doesn't transform these files unless I reference them with their relative paths.
I don't know if this is a bug or an intended behavior.
I think it could be nice, for each path, to specify if we want it to be transformed by browserify or not.
Currently my browserify bundle contains raw uncompiled JSX code, and it breaks at runtime.

Until now I did not find any clear solution on how to handle the `relative paths everywhere` problem. I think it's a pretty common problem that can be really annoying on large code base when refactoring. It's also solved easily with requirejs so I guess it would be nice to document how to do it with browserify.

**Comment by serapath** [comment]
@scamden 
**My projects look like:**
* **moduleName/**
  * **node_modules/** // `npm install` goes here
  * *package.json*
  * **SOURCE/**
    * **node_modules/** // custom code goes here (potential candidates for new **npm modules**)
      * *_config.js* // my only place for relative **require**'s (e.g. `package.json`)
    * *index.js*
  * *.gitignore*

In order to exclude `./node_modules` but include `./node_modules/SOURCE`
I do in:
```
#  [.gitignore]
node_modules
!SOURCE/node_modules
```

**Comment by scamden** [comment]
ya i did that, but i just found it confusing to have src in node_modules
directories

**Comment by marrs** [comment]
@serapath That solution is already looking complicated and it doesn't show where your unit test code would go.  

If NODE_PATH is a thing that's not going anywhere and already works then it seems a bit silly to discourage people from using it.  I really don't care about performance.  I'm already linting the entire codebase, running unit tests, who knows what else besides.

**Comment by rjdlee** [comment]
How do you guys deal with browserify/ babelify caching the files in the node_modules?
