### ISSUE TITLE
`noParse` in package.json of dependency

### ISSUE THREAD

**Issue by dminkovsky** [substack/node-browserify#794]
I have a module—call it module "A"—that npm-depends on jQuery. I'd like to specify that jQuery not be parsed whenever "A" is included in a Browserify bundle. "A" is required a lot in my application's AST, so it would be a huge savings to have "A"'s jQuery not parsed whenever "A" is looked up by `module-deps`. How can I make this happen?

I've tried adding 

```
"browserify": {
  "noParse": [ "node_modules/jquery/dist/jquery" ]
}
```

to "A"'s `package.json`, but it doesn't seem to improve performance. (I've tried stepping through bundling runs but I'm very new to the codebase and am not quickly figuring out the precise flow). Based on my understanding so far, though, there doesn't seem to be a way to add the `noParse` to `browserify`'s `opts`, because `noParse` there has to be absolute.

**Comment by stevenvachon** [comment]
Hmm, webpack has a `noParse` field in package.json
