### ISSUE TITLE
Unable to prevent Buffer transforms

### ISSUE THREAD

**Issue by foxx** [substack/node-browserify#817]
If browserify detects the `Buffer` global is used, it will forcibly include all the Buffer libs;

```
$ browserify src/js/app.js --list
../buffer/node_modules/ieee754/index.js
../buffer/node_modules/base64-js/lib/b64.js
../buffer/index.js
```

However this is undesired for our use case, specifically an external library which makes reference to `Buffer` but doesn't actually use it and won't hard fail if it doesn't exist.

I've attempted to do;

```
$ browserify src/js/app.js --no-builtins --no-bundle-external
```

However this doesn't stop the output from doing require('buffer'), it just doesn't include it, and as such the code fails to run. See partial output;

```
function (Buffer){
var lol = new Buffer();
}).call(this,require("buffer").Buffer)
},{}]},{},[1])(app)
```

I've spent an hour trawling through source code but cannot figure out where this functionality even take places, any help would be appreciated. At the very least, this deserves a docs update and/or a patch. Happy to contribute.

**Comment by zbjornson** [comment]
`--ignore buffer` is stubbing it, but it's still automatically adding `require("buffer").Buffer` in the IIFEs wrapping the modules that use Buffer (and that we don't want to support in the browser). `buffer.Buffer` is undefined. Instead using `--detect-globals false` worked (as would, I imagine, modifying `--insert-global-vars`, if you need to include other globals). Not sure if there's a better way or if we're doing something wrong?
