### ISSUE TITLE
Fails when package.json starts with a BOM

### ISSUE THREAD

**Issue by ForbesLindesay** [substack/node-browserify#846]
node.js & npm handle Byte Order Marks (BOMs) at the start of files, but browserify doesn't seem to do so.

If you have a package.json that starts with a byte order mark, you get the slightly cryptic error:

```
Error: SyntaxError: Unexpected token ∩╗┐ while parsing json file C:package.json
```

**Comment by patapron** [comment]
I´ve de same problem, but my browserify version is latest and I´n executing the gulp task by visual studio. Some idea?
