### ISSUE TITLE
browserify opts.insertGlobalVars does nothing

### ISSUE THREAD

**Issue by adam-lynch** [substack/node-browserify#847]
```coffeescript
browserified = browserify entryFilePath,
    extensions: ['.coffee']
    insertGlobalVars: 
        x: 'hello world'

browserified.transform coffeeify,
    global: true

browserified.bundle
    extensions: ['.coffee']
```

Then `x` doesn't exist. 

Any ideas?

---

browserify: `4.2.1`
node: `0.10.20`
npm: `1.3.11`
windows: `8.1`

**Comment by ankurp** [comment]
Is this resolved?

**Comment by jmm** [comment]
Current browserify documentation:
> `opts.insertGlobalVars` will be passed to [insert-module-globals](http://npmjs.org/package/insert-module-globals) as the `opts.vars` parameter.

Current insert-module-globals documentation:
> `insert-module-globals` can also insert arbitary globals into files. Pass in an object of functions as the `vars` option.

In your example you're passing a string as the value, not a function. I know this is an old issue and perhaps it behaved or was documented differently at the time. @adam-lynch @niksy @ankurp plesae comment on whether that resolves the issue for you.

Thanks
