### ISSUE TITLE
Need to expose all modules based on extension

### ISSUE THREAD

**Issue by w0rm** [substack/node-browserify#856]
I need to expose all modules based on extension when combining bundle. I have tried this, but it didn't work (got me `[Error: write after end]` for each file).

```
.on('file', function (file, id) {
      if (id.substr(id.length - 4, 4) === 'nunj') b.require(id)
})
```

Is there any other way to hook into pipeline where `b.require` can be called for each file?

P.S. need this to overcome [a problem with nunjucksify](https://github.com/rotundasoftware/nunjucksify/issues/2)

**Comment by jmm** [comment]
@w0rm It looks like you solved your problem another way, but are you still interested in what you originally asked about, being able to expose all modules with a certain file extension?
