### ISSUE TITLE
Cannot find module '...\src\*.js', windows

### ISSUE THREAD

**Issue by dy** [substack/node-browserify#865]
When I run `browserify src/*.js` in windows terminal I get:

``` shell
Error: Cannot find module 'C:\Users\dmitry\Dropbox\Projects\mod\src\*.js' from 'C:\Users\dmitry\Dropbox\Projects\mod'
    at C:\Users\dmitry\Dropbox\Projects\mod\node_modules\browserify\node_modules\resolve\lib\async.js:42:25
    at load (C:\Users\dmitry\Dropbox\Projects\mod\node_modules\browserify\node_modules\resolve\lib\async.js:60:43)
    at C:\Users\dmitry\Dropbox\Projects\mod\node_modules\browserify\node_modules\resolve\lib\async.js:66:22
    at C:\Users\dmitry\Dropbox\Projects\mod\node_modules\browserify\node_modules\resolve\lib\async.js:21:47
    at Object.oncomplete (fs.js:107:15)
```

The same happens if I call `npm run build`, where `build` is `browserify src/*.js > dist/bundle.js`.
If I use an alternate terminal (git bash), everything works fine, but I still can’t fix the npm task.

I could think that wildcards are badly parsed in windows, but `cat src/*.js > dist/mod.js`, works alright.

**Comment by awvalenti** [comment]
@dfcreative, I believe that's not the issue, since I had the same problem outside Windows Azure. Opened https://github.com/substack/node-browserify/issues/1170.
