### ISSUE TITLE
Browser field substitution for subfolder dependency

### ISSUE THREAD

**Issue by oncletom** [substack/node-browserify#900]
Hello,

here is what I want to achieve.

```js
// index.js
var ajax = require('foo/ajax');

ajax.get('…', function(response) { … });
```

Whereas the `node_modules/foo/package.json` contains:

```js
{
  "name": "foo",
  "browserify": {
    "transform": [
      "deamdify"
    ]
  },
  "browser": {
    "foo/ajax": "./src/ajax.js"
  },
  "dependencies": {
    "deamdify": "~0.1.1"
  }
}
```

And `node_modules/foo/src/ajax.js` looks like:

```js
define([ './core' ], function(core){
  // …

  return ajax;
});
```

However when I run `browserify index.js -o bundle.js` I get the following error:

```
Error: Cannot find module 'foo/ajax' from '/path/to/project'
```

Is it normal? Any hint to make this working — unless this is not supposed to work like that.

Thanks :-)

**Comment by substack** [comment]
This can be done with:

```
"browser": {
  "./ajax": "./src/ajax.js"
}
```

then outside consumers can `require('foo/ajax')`. I've added this case to the test suite under test/browser_field_resolve/{k,l}.js and many fixes landed in https://github.com/defunctzombie/node-browser-resolve/pull/75
