### ISSUE TITLE
Can't expose require created with Readable stream

### ISSUE THREAD

**Issue by lukekarrys** [substack/node-browserify#908]
I'm trying to add a readable stream to a bundle and then require it by the exposed name in `main.js`.

**main.js**
```js
var bar = require('m1');
```

The following code produces an error `Error: Cannot find module 'm1'`.
```js
var Browserify = require('browserify');
var Readable = require('stream').Readable;

function stringStream(content) {
    var s = new Readable();
    s.push(content);
    s.push(null);
    return s;
}

var b = new Browserify();
b.require(stringStream('module.exports = 5'), {basedir: '.', expose: 'm1'});
b.add('./main.js');
b.bundle().pipe(process.stdout);
```

Should this work?

**Comment by terinjokes** [comment]
@lukekarrys You've correctly exposed the module, and Browserify will use it when generating the bundle.

The error you're getting "Error: Cannot find module 'm1'" comes from `module-deps` which implements the node module resolution algorithm, and searches for "m1" in the node_modules directories, as well as by looking at the "browser" field in package.json. It doesn't know about any other modules you're dynamically generating and handing to Browserify.

What I recommend is to inform `module-deps` that it shouldn't attempt to resolve the module by using `b.exclude('m1');`. I've written up an example, with a few extra notes, [in a Gist](https://gist.github.com/terinjokes/9e95ea98d41919266fbb).

**Comment by lukekarrys** [comment]
Thank you @terinjokes! That is soooo helpful :tada: 

I'm gonna go ahead and close this since I now get that the issue isn't in browserify.

**Comment by terinjokes** [comment]
> That is soooo helpful :tada:

I try, and often fail, to provide helpful answers. I regret when I don't, but glad to have made you happy here. :smile:
