### ISSUE TITLE
Browserify command not found

### ISSUE THREAD

**Issue by jeremyfourna** [substack/node-browserify#916]
Hello,

I just installed browserify via **sudo npm install -g browserify** but when I run
### browserify -r ./app/collections/movies.js:movies \ -r ./app/models/movie.js:movie > static/bundle.js

The terminal answer but **browserify : command not found**

Can someone explain to me what I did wrong ?

Thank you in advance,

**Comment by donhamiltoniii** [comment]
@substack You are my hero. I've been searching for an answer to this for two days.
