### ISSUE TITLE
When using AMD loader and browserify simultaneously, UMD libs not working.

### ISSUE THREAD

**Issue by dnarushevich** [substack/node-browserify#934]
I have Browserify compiled bundle, with backbone included inside of it, and Backbone lib has this UMD:
```javascript
  // Set up Backbone appropriately for the environment. Start with AMD.
  if (typeof define === 'function' && define.amd) {
    define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
      // Export global even in AMD case in case this script is loaded with
      // others that may still expect a global Backbone.
      root.Backbone = factory(root, exports, _, $);
    });

  // Next for Node.js or CommonJS. jQuery may not be needed as a module.
  } else if (typeof exports !== 'undefined') {
    var _ = require('underscore');
    factory(root, exports, _);

  // Finally, as a browser global.
  } else {
    root.Backbone = factory(root, {}, root._, (root.jQuery || root.Zepto || root.ender || root.$));
  }
```

My code loads such bundle with RequireJS.
Define() function is defined in global namespace, and backbone decides to use AMD definition, instead of CommonJS. And because of that calling require("backbone") somewhere inside of bundled code we get empty object in return.

Many libs use exactly this UMD format, so modifying sources to fix that is not a good idea.

As a solution could be overriding most common global functions like define(), require() to undefined inside of a bundle's wrapper function, so UMD would see local define, instead of global.

**Comment by plumlee** [comment]
@thlorenz Can you elaborate more - are you saying the solution is to shim any module that already wraps itself with UMD?
