### ISSUE TITLE
Warn about cyclic/circular requires

### ISSUE THREAD

**Issue by dizzib** [substack/node-browserify#961]
Would be useful if browserify could detect this scenario and issue a warning or error. This is because I'm trying to avoid such dubious scenarios in my code.

foo.js    require('./bar');
bar.js    require('./baz');
baz.js    require('./foo');

btw thanks for such a great tool!

**Comment by dutzi** [comment]
I also just spent ~2 hours debugging what @flying-sheep described. 

1. When I started converting my (client-side) code to NPM modules I read a little about cyclic dependencies and decided I would just avoid it.
2. It all worked fine for >2 months.
3. Today I accidentally introduced a cyclic dependency which caused this behavior.

**Comment by substack** [comment]
browserify just does the same thing as node. It's not browserify's place to add extra warnings.

**Comment by ibc** [comment]
Export first. Define later. No cyclic dependency problems. Explained
somewhere above.
This is about Node require() rather than about browserify.

**Comment by flying-sheep** [comment]
“node does a dumb thing so there’s absolutely no reason to do better”

i don’t get this logic at all…

**Comment by ibc** [comment]
@flying-sheep definitely you don't want to understand. How `require()` works is defined by CommonJS, and Node uses it, and so does browserify. Period. You cannot change the behavior of `require()` because you may introduce bugs in existing code that rely on the CommonJS behavior.

Again: export first and define later. If you want to see a complex and big JS client library doing exactly that take a look to [JsSIP](https://github.com/versatica/JsSIP). No one cyclic dependency problem.

**Comment by feross** [comment]
@flying-sheep File a bug on joyent/node or iojs, get it fixed there, and browserify will follow suit.

**Comment by ibc** [comment]
A bug about what? about a bad usage of `require()`?  :)

**Comment by flying-sheep** [comment]
> definitely you don't want to understand

i do though. at no place the spec says “the implementation must not emit warnings when returning an incomplete module object as a result of a circular dependency”, so we could totally do that.

> A bug about what? about a bad usage of `require()`? :)

now you’re just being an asshole. i’m talking about helping users to prevent that kind of bug, and you know that.

**Comment by feross** [comment]
@flying-sheep The right place to get this behavior changed is at the source. If it's changed there, browserify will follow suit.
