### ISSUE TITLE
browserify -r with npm installed module does not run transforms

### ISSUE THREAD

**Issue by deitch** [substack/node-browserify#975]
If I try to transform a file that was installed via `npm`, the transform does not run. Simple example: if I want to run `browserify-shim` on `angular`, so I can do:

````JavaScript
var angular = require('angular');
````

````JavaScript
{
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "angular":"./node_modules/angular/angular.js"
  },
  "browserify-shim": {
    "angular": {
      "exports": "angular"
    }
  },
  "dependencies": {
    "browserify-shim": "~3.x.x",
    "angular": "~1.3.1"
  }
}
````

Then I run:

````
npm install
browserify -r angular -o vendor.js
`````

The transform will **not** run. Of course, it also happens if I do not include a `browser` override for `angular` and just let it use the `npm` installation directly.

I dug pretty deeply, it looks like that when it runs `getTransforms()` in module-deps LL429-443, the `pkg` that is passed is *not* my application's `package.json` (above), which has the transforms configured, but rather the `package.json` from `angular`, which of course has no transformations, since these are done for my project.

**Comment by bendrucker** [comment]
@deitch Can this be closed? I think the local-only default for transforms with the option to run globally is well documented. This will all work once Angular is well behaved. 

https://github.com/angular/angular.js/pull/10732

**Comment by deitch** [comment]
@bendrucker it looks like the `global` option is a feasible workaround. Go ahead.

**Comment by bendrucker** [comment]
Not a collab, you'd need to close it :)

**Comment by deitch** [comment]
Oops. :-)

**Comment by codeviking** [comment]
@deitch @bjfletcher Is there a way to specify the global flag with the package.json?

**Comment by bendrucker** [comment]
No, that's not compatible with the way Browserify works. Only transforms can be defined from the package and they specifically cannot be defined as global. Nor can plugins be set from the package.

**Comment by codeviking** [comment]
Well, I don't have access to the code to `.transform` -- I'm left to either write my own buildfile (and thus not use a standard one distributed across teams), or do this:

```
<script>window.global = window;</script>
<script src="/main.js"></script>
```

That hack works, but admittedly is nasty.

Thanks -- I just thought I'd post my work-around for others as well.
